# Dependency updates for GitHub Actions and npm
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
version: 2
updates:
  - package-ecosystem: maven
    directory: /backend
    schedule:
      interval: weekly
    commit-message:
      prefix: "Backend"
      include: "scope"
