/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddressGroupComponent: typeof import('./src/components/grouping/AddressGroupComponent.vue')['default']
    AutoCompleteInputComponent: typeof import('./src/components/forms/AutoCompleteInputComponent.vue')['default']
    BButton: typeof import('bootstrap-vue-3')['BButton']
    BDropdown: typeof import('bootstrap-vue-3')['BDropdown']
    BDropdownDivider: typeof import('bootstrap-vue-3')['BDropdownDivider']
    BDropdownItem: typeof import('bootstrap-vue-3')['BDropdownItem']
    BFormGroup: typeof import('bootstrap-vue-3')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-3')['BFormInput']
    BFormRadio: typeof import('bootstrap-vue-3')['BFormRadio']
    BPopover: typeof import('bootstrap-vue-3')['BPopover']
    BTab: typeof import('bootstrap-vue-3')['BTab']
    BTabs: typeof import('bootstrap-vue-3')['BTabs']
    ContactGroupComponent: typeof import('./src/components/grouping/ContactGroupComponent.vue')['default']
    DataFetcher: typeof import('./src/components/DataFetcher.vue')['default']
    DropdownInputComponent: typeof import('./src/components/forms/DropdownInputComponent.vue')['default']
    MultiselectInputComponent: typeof import('./src/components/forms/MultiselectInputComponent.vue')['default']
    RadioInputComponent: typeof import('./src/components/forms/RadioInputComponent.vue')['default']
    TextInputComponent: typeof import('./src/components/forms/TextInputComponent.vue')['default']
    WizardTabComponent: typeof import('./src/components/wizard/WizardTabComponent.vue')['default']
    WizardWrapperComponent: typeof import('./src/components/wizard/WizardWrapperComponent.vue')['default']
  }
}
