/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddressGroupComponent: typeof import('./src/components/grouping/AddressGroupComponent.vue')['default']
    AutoCompleteInputComponent: typeof import('./src/components/forms/AutoCompleteInputComponent.vue')['default']
    ComboBoxInputComponent: typeof import('./src/components/forms/ComboBoxInputComponent.vue')['default']
    ContactGroupComponent: typeof import('./src/components/grouping/ContactGroupComponent.vue')['default']
    DataFetcher: typeof import('./src/components/DataFetcher.vue')['default']
    DateInputComponent: typeof import('./src/components/forms/DateInputComponent/index.vue')['default']
    DateInputPart: typeof import('./src/components/forms/DateInputComponent/DateInputPart.vue')['default']
    DropdownInputComponent: typeof import('./src/components/forms/DropdownInputComponent.vue')['default']
    ErrorNotificationGroupingComponent: typeof import('./src/components/grouping/ErrorNotificationGroupingComponent.vue')['default']
    FuzzyMatchNotificationGroupingComponent: typeof import('./src/components/grouping/FuzzyMatchNotificationGroupingComponent.vue')['default']
    LoadingOverlayComponent: typeof import('./src/components/LoadingOverlayComponent.vue')['default']
    MainHeaderComponent: typeof import('./src/components/MainHeaderComponent.vue')['default']
    MultiselectInputComponent: typeof import('./src/components/forms/MultiselectInputComponent.vue')['default']
    RadioInputComponent: typeof import('./src/components/forms/RadioInputComponent.vue')['default']
    ReadOnlyComponent: typeof import('./src/components/forms/ReadOnlyComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleCheckboxInputComponent: typeof import('./src/components/forms/SimpleCheckboxInputComponent.vue')['default']
    StaffContactGroupComponent: typeof import('./src/components/grouping/StaffContactGroupComponent.vue')['default']
    StaffDetailsLocationGroupComponent: typeof import('./src/components/grouping/StaffDetailsLocationGroupComponent.vue')['default']
    StaffLocationGroupComponent: typeof import('./src/components/grouping/StaffLocationGroupComponent.vue')['default']
    TextareaInputComponent: typeof import('./src/components/forms/TextareaInputComponent.vue')['default']
    TextInputComponent: typeof import('./src/components/forms/TextInputComponent.vue')['default']
    ToggleComponent: typeof import('./src/components/forms/ToggleComponent.vue')['default']
    UserProfileComponent: typeof import('./src/components/UserProfileComponent.vue')['default']
  }
}
