apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAME}
  annotations:
    description: "Nr-Old-Growth"
    tags: "nrfc"
    iconClass: icon-js
labels:
  app: ${NAME}-${ZONE}
  app.kubernetes.io/part-of: ${NAME}-${ZONE}
parameters:
  - name: NAME
    description: Module name
    value: nr-forest-client
  - name: COMPONENT
    description: Component name
    value: frontend
  - name: ZONE
    description: Deployment zone, e.g. pr-### or prod
    required: true
  - name: IMAGE_TAG
    description: Image tag to use
    value: latest
  - name: DOMAIN
    value: apps.silver.devops.gov.bc.ca
  - name: REGISTRY
    description: Container registry to import from (internal is image-registry.openshift-image-registry.svc:5000)
    value: ghcr.io
  - name: PROMOTE
    description: Image (namespace/name:tag) to promote/import
    value: bcgov/nr-old-growth:prod-frontend
  - name: CPU_REQUEST
    value: 10m
  - name: CPU_LIMIT
    value: 25m
  - name: MEMORY_REQUEST
    value: 50Mi
  - name: MEMORY_LIMIT
    value: 50Mi
  - name: VITE_NODE_ENV
    value: ""
  - name: VITE_KEYCLOAK_URL
    value: https://loginproxy.gov.bc.ca/auth
  - name: VITE_KEYCLOAK_CLIENT_ID
    value: ""
  - name: LOG_LEVEL
    description: Caddy log level (debug, info, warn, error, panic, fatal)
    value: "info"
  - name: URL
    description: Deployment URL
    required: true
  - name: GREEN_DOMAIN
    description: Green domain
    required: true
  - name: COGNITO_REGION
    description: Cognito region information
    required: true
  - name: COGNITO_CLIENT_ID
    description: Cognito client id
    required: true
  - name: COGNITO_USER_POOL
    description: Cognito user pool id
    required: true
  - name: COGNITO_DOMAIN
    description: Cognito domain
    required: true
  - name: COGNITO_ENVIRONMENT
    description: Cognito environment
    required: true
  - name: COGNITO_REDIRECT_URI
    description: Cognito redirect url once logged in
    required: true
  - name: COGNITO_LOGOUT_URI
    description: Cognito redirect url once logged out
    required: true
objects:
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      labels:
        app: ${NAME}-${ZONE}
      name: ${NAME}-${ZONE}-${COMPONENT}
    spec:
      lookupPolicy:
        local: false
      tags:
        - name: ${IMAGE_TAG}
          from:
            kind: DockerImage
            name: ${REGISTRY}/${PROMOTE}
          referencePolicy:
            type: Local
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      labels:
        app: ${NAME}-${ZONE}
      name: ${NAME}-${ZONE}-${COMPONENT}
    data:
      config.js: |
        window.localStorage.setItem('VITE_BACKEND_URL', 'https://${NAME}-${ZONE}-backend.${DOMAIN}');
        window.localStorage.setItem('VITE_FRONTEND_URL', 'https://${URL}');
        window.localStorage.setItem('VITE_NODE_ENV', '${VITE_NODE_ENV}');
        window.localStorage.setItem('VITE_GREEN_DOMAIN', '${GREEN_DOMAIN}');        
        window.localStorage.setItem('VITE_AWS_COGNITO_REGION','${COGNITO_REGION}');
        window.localStorage.setItem('VITE_AWS_COGNITO_POOL_ID','${COGNITO_USER_POOL}');
        window.localStorage.setItem('VITE_AWS_COGNITO_CLIENT_ID','${COGNITO_CLIENT_ID}');
        window.localStorage.setItem('VITE_AWS_COGNITO_DOMAIN','${COGNITO_DOMAIN}');
        window.localStorage.setItem('VITE_AWS_COGNITO_LOGOUT_CHAIN_URL','${COGNITO_LOGOUT_URI}');
        window.localStorage.setItem('VITE_AWS_COGNITO_ENVIRONMENT','${COGNITO_ENVIRONMENT}');
  - kind: DeploymentConfig
    apiVersion: v1    
    metadata:
      labels:
        app: ${NAME}-${ZONE}
      name: ${NAME}-${ZONE}-${COMPONENT}
    spec:
      replicas: 1
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${NAME}
            from:
              kind: ImageStreamTag
              name: ${NAME}-${ZONE}-${COMPONENT}:${IMAGE_TAG}
      selector:
        deploymentconfig: ${NAME}-${ZONE}-${COMPONENT}
      strategy:
        type: Rolling
      template:
        metadata:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "3000"
            prometheus.io/path: "/metrics"
          labels:
            app: ${NAME}-${ZONE}
            deploymentconfig: ${NAME}-${ZONE}-${COMPONENT}
        spec:
          volumes:
            - name: env-config
              configMap:
                name: ${NAME}-${ZONE}-${COMPONENT}
          containers:
            - image: ${NAME}-${ZONE}-${COMPONENT}:${IMAGE_TAG}
              securityContext:
                capabilities:
                  add: ["NET_BIND_SERVICE"]
              env:
                - name: LOG_LEVEL
                  value: ${LOG_LEVEL}
              imagePullPolicy: Always
              name: ${NAME}
              volumeMounts:
                - name: env-config
                  mountPath: /srv/data
              ports:
                - containerPort: 3000
                  protocol: TCP
              resources:
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
              readinessProbe:
                httpGet:
                  path: /
                  port: 3000
                  scheme: HTTP
                initialDelaySeconds: 15
                periodSeconds: 30
                timeoutSeconds: 1
              livenessProbe:
                successThreshold: 1
                failureThreshold: 3
                httpGet:
                  path: /
                  port: 3000
                  scheme: HTTP
                initialDelaySeconds: 15
                periodSeconds: 30
                timeoutSeconds: 5
  - kind: Service
    apiVersion: v1    
    metadata:
      labels:
        app: ${NAME}-${ZONE}
      name: ${NAME}-${ZONE}-${COMPONENT}
    spec:
      ports:
        - name: 3000-tcp
          protocol: TCP
          port: 80
          targetPort: 3000
      selector:
        deploymentconfig: ${NAME}-${ZONE}-${COMPONENT}
  - kind: Route
    apiVersion: route.openshift.io/v1    
    metadata:
      labels:
        app: ${NAME}-${ZONE}
      name: ${NAME}-${ZONE}-${COMPONENT}
    spec:
      host: ${URL}
      port:
        targetPort: 3000-tcp
      to:
        kind: Service
        name: ${NAME}-${ZONE}-${COMPONENT}
        weight: 100
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
