apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: ${NAME}-${ZONE}
  app.kubernetes.io/part-of: ${NAME}-${ZONE}
parameters:
  - name: NAME
    description: Module name
    value: nr-forest-client
  - name: COMPONENT
    description: Component name
    value: backend
  - name: ZONE
    description: Deployment zone, e.g. pr-### or prod
    required: true
  - name: TAG
    description: Image tag; e.g. PR number, latest or prod
    required: true
  - name: REGISTRY
    description: Container registry to import from (internal is image-registry.openshift-image-registry.svc:5000)
    value: ghcr.io
  - name: ORG
    description: Organization name
    value: bcgov
  - name: DOMAIN
    value: apps.silver.devops.gov.bc.ca
  - name: REGISTRY
    description: Container registry to import from (internal is image-registry.openshift-image-registry.svc:5000)
    value: ghcr.io
  - name: CHES_TOKEN_URL
    description: CHES service authentication url
    value: 'https://loginproxy.gov.bc.ca/auth/realms/comsvcauth/protocol/openid-connect/token'
  - name: CHES_API_URL
    description: CHES service api url
    value: 'https://ches.api.gov.bc.ca/api/v1'
  - name: CPU_REQUEST
    value: 75m
  - name: MEMORY_REQUEST
    value: 200Mi
  - name: BCREGISTRY_URI
    description: Bc Registry API address
    value: https://api.connect.gov.bc.ca
  - name: COGNITO_REGION
    description: Cognito region to be used
    value: 'ca-central-1'
  - name: FRONTEND_URL
    description: Frontend URL
    required: true
  - name: CONFIG_MAP
    description: Configuration map for application.yml
    required: true
  - name: RANDOM_EXPRESSION
    description: Random expression to make sure deployments update
    from: "[a-zA-Z0-9]{32}"
    generate: expression
  - name: CANADAPOST_CERT_SECRET
    description: "Optional secret that contains the Canada Post PEM file (key name: canadapost.pem)"
    required: false
    value: ""
  - name: CANADAPOST_CERT_MOUNT_PATH
    description: Path inside the container where the Canada Post PEM should be mounted
    required: false
    value: "/etc/ssl/certs/canadapost"
objects:
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      labels:
        app: ${NAME}-${ZONE}
      name: ${NAME}-${ZONE}-${COMPONENT}
    spec:
      replicas: 1
      selector:
        matchLabels:
          deployment: ${NAME}-${ZONE}-${COMPONENT}
      strategy:
        type: RollingUpdate
      template:
        metadata:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "8080"
            prometheus.io/path: "/metrics"
          labels:
            app: ${NAME}-${ZONE}
            deployment: ${NAME}-${ZONE}-${COMPONENT}
        spec:
          volumes:
            - name: ${COMPONENT}-config
              configMap:
                name: ${NAME}-${ZONE}-${COMPONENT}-config
            # Optional Canada Post cert secret volume
            - name: canadapost-cert
              secret:
                secretName: ${CANADAPOST_CERT_SECRET}
                optional: true
          containers:
            - image: ${REGISTRY}/${ORG}/${NAME}/${COMPONENT}:${TAG}
              imagePullPolicy: Always
              name: ${NAME}
              volumeMounts:
                - name: ${COMPONENT}-config
                  mountPath: /app/application.yml
                  subPath: application.yml
                # Optional mount for Canada Post PEM
                - name: canadapost-cert
                  mountPath: ${CANADAPOST_CERT_MOUNT_PATH}
                  readOnly: true
              env:
                - name: FRONTEND_URL
                  value: https://${FRONTEND_URL}
                - name: LEGACY_URL
                  value: http://${NAME}-${ZONE}-legacy
                - name: PROCESSOR_URL
                  value: http://${NAME}-${ZONE}-processor
                - name: SELF_URI
                  value: https://${NAME}-${ZONE}-${COMPONENT}.${DOMAIN}
                - name: CHES_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-${ZONE}
                      key: ches-client-id
                - name: CHES_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-${ZONE}
                      key: ches-client-secret
                - name: CHES_TOKEN_URL
                  value: ${CHES_TOKEN_URL}
                - name: CHES_API_URL
                  value: ${CHES_API_URL}
                - name: POSTGRESQL_HOST
                  value: ${NAME}-${ZONE}-database
                - name: CHES_COPY_EMAIL
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-${ZONE}
                      key: ches-mail-copy
                - name: POSTGRESQL_DATABASE
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-${ZONE}
                      key: database-name
                - name: POSTGRESQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-${ZONE}
                      key: database-password
                - name: POSTGRESQL_USER
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-${ZONE}
                      key: database-user
                - name: BCREGISTRY_URI
                  value: ${BCREGISTRY_URI}
                - name: BCREGISTRY_KEY
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-${ZONE}
                      key: bcregistry-key
                - name: BCREGISTRY_ACCOUNT
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-${ZONE}
                      key: bcregistry-account
                - name: ADDRESS_COMPLETE_KEY
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-${ZONE}
                      key: address-complete-key
                - name: COGNITO_USER_POOL
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-${ZONE}
                      key: cognito-user-pool
                - name: COGNITO_ENVIRONMENT
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-${ZONE}
                      key: cognito-environment
                - name: COGNITO_REGION
                  value: ${COGNITO_REGION}
                - name: PROCESSOR_SERVICE_ACCOUNT_NAME
                  valueFrom:
                      secretKeyRef:
                        name: ${NAME}-${ZONE}
                        key: processor-service-account-name
                - name: PROCESSOR_SERVICE_ACCOUNT_SECRET
                  valueFrom:
                      secretKeyRef:
                        name: ${NAME}-${ZONE}
                        key: processor-service-account-secret
                - name: TZ
                  value: America/Vancouver
                - name: APP_ZONE
                  value: ${ZONE}
                - name: APP_COMPONENT
                  value: ${COMPONENT}
                - name: FEATURES_BCREGISTRY_MULTIADDRESS
                  value: "false"
                - name: RANDOM_EXPRESSION
                  value: ${RANDOM_EXPRESSION}
                # Optional env var to point the application at the mounted PEM file
                - name: CA_BC_GOV_NRS_ADDRESSCOMPLETE_TRUSTCERTPATH
                  value: ${CANADAPOST_CERT_MOUNT_PATH}/canadapost.pem
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources:
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
              readinessProbe:
                successThreshold: 1
                failureThreshold: 15
                httpGet:
                  path: /health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 10
                periodSeconds: 30
                timeoutSeconds: 5
  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: ${NAME}-${ZONE}
      name: ${NAME}-${ZONE}-${COMPONENT}
    spec:
      ports:
        - name: 8080-tcp
          protocol: TCP
          port: 80
          targetPort: 8080
      selector:
        deployment: ${NAME}-${ZONE}-${COMPONENT}
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      labels:
        app: ${NAME}-${ZONE}
      name: ${NAME}-${ZONE}-${COMPONENT}
    spec:
      host: ${NAME}-${ZONE}-${COMPONENT}.${DOMAIN}
      port:
        targetPort: 8080-tcp
      to:
        kind: Service
        name: ${NAME}-${ZONE}-${COMPONENT}
        weight: 100
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      labels:
        app: ${NAME}-${ZONE}
      name: ${NAME}-${ZONE}-${COMPONENT}-config
    data:
      application.yml: |
        ${CONFIG_MAP}
