apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: ${NAME}-${ZONE}
  app.kubernetes.io/part-of: ${NAME}-${ZONE}
parameters:
  - name: NAME
    description: Module name
    value: nr-forest-client
  - name: COMPONENT
    description: Component name
    value: backend
  - name: ZONE
    description: Deployment zone, e.g. pr-### or prod
    required: true
  - name: IMAGE_TAG
    description: Image tag to use
    value: latest
  - name: DOMAIN
    value: apps.silver.devops.gov.bc.ca
  - name: REGISTRY
    description: Container registry to import from (internal is image-registry.openshift-image-registry.svc:5000)
    value: ghcr.io
  - name: PROMOTE
    description: Image (namespace/name:tag) to promote/import
    value: bcgov/nr-forest-client-backend:prod
  - name: CHES_TOKEN_URL
    description: CHES service authentication url
    required: true
  - name: CHES_API_URL
    description: CHES service api url
    required: true
  - name: CPU_REQUEST
    value: 75m
  - name: CPU_LIMIT
    value: 200m
  - name: MEMORY_REQUEST
    value: 200Mi
  - name: MEMORY_LIMIT
    value: 256Mi
  - name: BCREGISTRY_URI
    description: Bc Registry API address
    required: true
  - name: COGNITO_REGION
    description: Cognito region to be used
    required: true
  - name: FRONTEND_URL
    description: Frontend URL
    required: true
  - name: CONFIG_MAP_NAME
    description: ConfigMap name specific to each environment
    value: ${NAME}-${ZONE}-${COMPONENT}-config
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      labels:
        app: ${NAME}-${ZONE}
      name: ${NAME}-${ZONE}-${COMPONENT}
    spec:
      lookupPolicy:
        local: false
      tags:
        - name: ${IMAGE_TAG}
          from:
            kind: DockerImage
            name: ${REGISTRY}/${PROMOTE}
          referencePolicy:
            type: Local
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      labels:
        app: ${NAME}-${ZONE}
      name: ${NAME}-${ZONE}-${COMPONENT}
    spec:
      replicas: 1
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${NAME}
            from:
              kind: ImageStreamTag
              name: ${NAME}-${ZONE}-${COMPONENT}:${IMAGE_TAG}
      selector:
        deploymentconfig: ${NAME}-${ZONE}-${COMPONENT}
      strategy:
        type: Rolling
      template:
        metadata:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "8080"
            prometheus.io/path: "/metrics"
          labels:
            app: ${NAME}-${ZONE}
            deploymentconfig: ${NAME}-${ZONE}-${COMPONENT}
        spec:
          volumes:
            - name: ${COMPONENT}-config
              configMap:
                name: ${NAME}-${ZONE}-${COMPONENT}-config
          containers:
            - image: ${NAME}-${ZONE}-${COMPONENT}:${IMAGE_TAG}
              imagePullPolicy: Always
              name: ${NAME}
              volumeMounts:
                - name: ${COMPONENT}-config
                  mountPath: /app/application.yml
                  subPath: application.yml
              env:
                - name: FRONTEND_URL
                  value: https://${FRONTEND_URL}
                - name: LEGACY_URL
                  value: http://${NAME}-${ZONE}-legacy
                - name: SELF_URI
                  value: https://${NAME}-${ZONE}-${COMPONENT}.${DOMAIN}
                - name: CHES_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-${ZONE}
                      key: ches-client-id
                - name: CHES_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-${ZONE}
                      key: ches-client-secret
                - name: CHES_TOKEN_URL
                  value: ${CHES_TOKEN_URL}
                - name: CHES_API_URL
                  value: ${CHES_API_URL}
                - name: POSTGRESQL_HOST
                  value: ${NAME}-${ZONE}-database
                - name: CHES_COPY_EMAIL
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-${ZONE}
                      key: ches-mail-copy
                - name: POSTGRESQL_DATABASE
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-${ZONE}
                      key: database-name
                - name: POSTGRESQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-${ZONE}
                      key: database-password
                - name: POSTGRESQL_USER
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-${ZONE}
                      key: database-user
                - name: BCREGISTRY_URI
                  value: ${BCREGISTRY_URI}
                - name: BCREGISTRY_KEY
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-${ZONE}
                      key: bcregistry-key
                - name: BCREGISTRY_ACCOUNT
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-${ZONE}
                      key: bcregistry-account
                - name: ADDRESS_COMPLETE_KEY
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-${ZONE}
                      key: address-complete-key
                - name: COGNITO_USER_POOL
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-${ZONE}
                      key: cognito-user-pool
                - name: COGNITO_ENVIRONMENT
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}-${ZONE}
                      key: cognito-environment
                - name: COGNITO_REGION
                  value: ${COGNITO_REGION}
                - name: PROCESSOR_SERVICE_ACCOUNT_NAME
                  valueFrom:
                      secretKeyRef:
                        name: ${NAME}-${ZONE}
                        key: processor-service-account-name
                - name: PROCESSOR_SERVICE_ACCOUNT_SECRET
                  valueFrom:
                      secretKeyRef:
                        name: ${NAME}-${ZONE}
                        key: processor-service-account-secret
                - name: TZ
                  value: America/Vancouver
                - name: APP_ZONE
                  value: ${ZONE}
                - name: APP_COMPONENT
                  value: ${COMPONENT}
                - name: FEATURES_BCREGISTRY_MULTIADDRESS
                  value: "false"
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources:
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
              readinessProbe:
                successThreshold: 1
                failureThreshold: 15
                httpGet:
                  path: /health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 10
                periodSeconds: 30
                timeoutSeconds: 5
  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: ${NAME}-${ZONE}
      name: ${NAME}-${ZONE}-${COMPONENT}
    spec:
      ports:
        - name: 8080-tcp
          protocol: TCP
          port: 80
          targetPort: 8080
      selector:
        deploymentconfig: ${NAME}-${ZONE}-${COMPONENT}
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      labels:
        app: ${NAME}-${ZONE}
      name: ${NAME}-${ZONE}-${COMPONENT}
      annotations:
        haproxy.router.openshift.io/rate-limit-connections: "true"
        haproxy.router.openshift.io/rate-limit-connections.rate-http: "50"
        haproxy.router.openshift.io/rate-limit-connections.rate-tcp: "25"
    spec:
      host: ${NAME}-${ZONE}-${COMPONENT}.${DOMAIN}
      port:
        targetPort: 8080-tcp
      to:
        kind: Service
        name: ${NAME}-${ZONE}-${COMPONENT}
        weight: 100
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
