INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('NLDL', 'Newfoundland and Labrador Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('PEDL', 'Prince Edward Island Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('NSDL', 'Nova Scotia Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('NBDL', 'New Brunswick Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('QCDL', 'Quebec Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('ONDL', 'Ontario Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('MBDL', 'Manitoba Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('SKDL', 'Saskatchewan Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('ABDL', 'Alberta Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('YTDL', 'Yukon Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('NTDL', 'Northwest Territories Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('NUDL', 'Nunavut Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('ALDL', 'Alabama Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('AKDL', 'Alaska Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('AZDL', 'Arizona Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('ARDL', 'Arkansas Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('CADL', 'California Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('CODL', 'Colorado Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('CTDL', 'Connecticut Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('DEDL', 'Delaware Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('DCDL', 'District of Columbia Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('FLDL', 'Florida Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('GADL', 'Georgia Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('HIDL', 'Hawaii Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('IDDL', 'Idaho Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('ILDL', 'Illinois Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('INDL', 'Indiana Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('IADL', 'Iowa Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('KSDL', 'Kansas Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('KYDL', 'Kentucky Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('LADL', 'Louisiana Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('MEDL', 'Maine Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('MDDL', 'Maryland Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('MADL', 'Massachusetts Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('MIDL', 'Michigan Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('MNDL', 'Minnesota Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('MSDL', 'Mississippi Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('MODL', 'Missouri Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('MTDL', 'Montana Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('NEDL', 'Nebraska Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('NVDL', 'Nevada Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('NHDL', 'New Hampshire Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('NJDL', 'New Jersey Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('NMDL', 'New Mexico Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('NYDL', 'New York Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('NCDL', 'North Carolina Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('NDDL', 'North Dakota Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('OHDL', 'Ohio Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('OKDL', 'Oklahoma Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('ORDL', 'Oregon Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('PADL', 'Pennsylvania Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('RIDL', 'Rhode Island Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('SCDL', 'South Carolina Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('SDDL', 'South Dakota Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('TNDL', 'Tennessee Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('TXDL', 'Texas Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('UTDL', 'Utah Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('VTDL', 'Vermont Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('VADL', 'Virginia Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('WADL', 'Washington Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('WVDL', 'West Virginia Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('WIDL', 'Wisconsin Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));
INSERT INTO THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
VALUES ('WYDL', 'Wyoming Drivers Licence', CURRENT_TIMESTAMP(6), TIMESTAMP '9999-12-31 00:00:00.000000', CURRENT_TIMESTAMP(6));