CREATE TABLE THE.CLIENT_TYPE_CODE (
	CLIENT_TYPE_CODE VARCHAR2(1) NOT NULL,
	DESCRIPTION VARCHAR2(120) NOT NULL,
	EFFECTIVE_DATE DATE NOT NULL,
	EXPIRY_DATE DATE NOT NULL,
	UPDATE_TIMESTAMP DATE NOT NULL,
	CONSTRAINT CTCD_PK PRIMARY KEY (CLIENT_TYPE_CODE),
	CONSTRAINT SYS_C0012021 CHECK ("CLIENT_TYPE_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0012022 CHECK ("DESCRIPTION" IS NOT NULL),
	CONSTRAINT SYS_C0012023 CHECK ("EFFECTIVE_DATE" IS NOT NULL),
	CONSTRAINT SYS_C0012024 CHECK ("EXPIRY_DATE" IS NOT NULL),
	CONSTRAINT SYS_C0012025 CHECK ("UPDATE_TIMESTAMP" IS NOT NULL)
);
CREATE UNIQUE INDEX CTCD_IDX ON THE.CLIENT_TYPE_CODE (CLIENT_TYPE_CODE);

CREATE TABLE THE.RESTORED_BLOB_STORAGE (
	BSTO_SEQ_NBR NUMBER(15,0) NOT NULL,
	BSTO_TABLE_NAME VARCHAR2(30) NOT NULL,
	BSTO_TABLE_PRIMARY_KEY VARCHAR2(1000) NOT NULL,
	BSTO_FILE_NAME VARCHAR2(60) NULL,
	BSTO_FILE_DESCRIPTION VARCHAR2(300) NULL,
	CONSTRAINT SYS_C0011049 CHECK ("BSTO_SEQ_NBR" IS NOT NULL),
	CONSTRAINT SYS_C0011050 CHECK ("BSTO_TABLE_NAME" IS NOT NULL),
	CONSTRAINT SYS_C0011051 CHECK ("BSTO_TABLE_PRIMARY_KEY" IS NOT NULL)
);

CREATE TABLE THE.RESTORED_FOREST_COMMENT (
	COMM_SEQ_NBR NUMBER(15,0) NOT NULL,
	COMM_MODULE VARCHAR2(15) NULL,
	COMM_ITEM_TYPE VARCHAR2(30) NULL,
	COMM_ITEM_SEQ_NBR NUMBER(15,0) NULL,
	COMM_COMMENT_DATE DATE NOT NULL,
	COMM_COMMENT VARCHAR2(4000) NOT NULL,
	COMM_AGENCY VARCHAR2(15) NOT NULL,
	COMM_AGENT VARCHAR2(15) NOT NULL,
	COMM_RESPONSE_DATE DATE NULL,
	COMM_RESPONDANT VARCHAR2(15) NULL,
	COMM_RESPONSE VARCHAR2(4000) NULL,
	COMM_ACTION_REQUIRED VARCHAR2(1) NULL,
	COMM_ACTION_ITEM VARCHAR2(2000) NULL,
	COMM_COMMENT_TYPE VARCHAR2(30) NULL,
	COMM_FDP_ID VARCHAR2(50) NULL,
	COMM_PARENT_SEQ_NBR NUMBER(15,0) NULL,
	CONSTRAINT SYS_C0011056 CHECK ("COMM_SEQ_NBR" IS NOT NULL),
	CONSTRAINT SYS_C0011057 CHECK ("COMM_COMMENT_DATE" IS NOT NULL),
	CONSTRAINT SYS_C0011058 CHECK ("COMM_COMMENT" IS NOT NULL),
	CONSTRAINT SYS_C0011059 CHECK ("COMM_AGENCY" IS NOT NULL),
	CONSTRAINT SYS_C0011060 CHECK ("COMM_AGENT" IS NOT NULL)
);

CREATE TABLE THE.CLIENT_UPDATE_ACTION_CODE (
	CLIENT_UPDATE_ACTION_CODE VARCHAR2(4) NOT NULL,
	DESCRIPTION VARCHAR2(120) NOT NULL,
	EFFECTIVE_DATE DATE NOT NULL,
	EXPIRY_DATE DATE NOT NULL,
	UPDATE_TIMESTAMP DATE NOT NULL,
	CONSTRAINT CUAC_PK PRIMARY KEY (CLIENT_UPDATE_ACTION_CODE),
	CONSTRAINT SYS_C0012618 CHECK ("CLIENT_UPDATE_ACTION_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0012619 CHECK ("DESCRIPTION" IS NOT NULL),
	CONSTRAINT SYS_C0012620 CHECK ("EFFECTIVE_DATE" IS NOT NULL),
	CONSTRAINT SYS_C0012621 CHECK ("EXPIRY_DATE" IS NOT NULL),
	CONSTRAINT SYS_C0012622 CHECK ("UPDATE_TIMESTAMP" IS NOT NULL)
);
CREATE UNIQUE INDEX CUAC_IDX ON THE.CLIENT_UPDATE_ACTION_CODE (CLIENT_UPDATE_ACTION_CODE);

CREATE TABLE THE.MAX_CLIENT_NMBR (
	DUMMY_ACCESS_KEY VARCHAR2(1) NOT NULL,
	CLIENT_NUMBER VARCHAR2(8) NOT NULL,
	CONSTRAINT SYS_C0023534 CHECK ("DUMMY_ACCESS_KEY" IS NOT NULL),
	CONSTRAINT SYS_C0023535 CHECK ("CLIENT_NUMBER" IS NOT NULL)
);
CREATE UNIQUE INDEX "I1$_MAX_CLIENT_NMBR" ON THE.MAX_CLIENT_NMBR (DUMMY_ACCESS_KEY);

CREATE TABLE THE.CLIENT_UPDATE_REASON_CODE (
	CLIENT_UPDATE_REASON_CODE VARCHAR2(4) NOT NULL,
	DESCRIPTION VARCHAR2(120) NOT NULL,
	EFFECTIVE_DATE DATE NOT NULL,
	EXPIRY_DATE DATE NOT NULL,
	UPDATE_TIMESTAMP DATE NOT NULL,
	CONSTRAINT CURCD_PK PRIMARY KEY (CLIENT_UPDATE_REASON_CODE),
	CONSTRAINT SYS_C0012098 CHECK ("CLIENT_UPDATE_REASON_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0012099 CHECK ("DESCRIPTION" IS NOT NULL),
	CONSTRAINT SYS_C0012100 CHECK ("EFFECTIVE_DATE" IS NOT NULL),
	CONSTRAINT SYS_C0012101 CHECK ("EXPIRY_DATE" IS NOT NULL),
	CONSTRAINT SYS_C0012102 CHECK ("UPDATE_TIMESTAMP" IS NOT NULL)
);

CREATE TABLE THE.CODE_LIST_TABLE (
	COLUMN_NAME VARCHAR2(18) NOT NULL,
	CODE_ARGUMENT VARCHAR2(50) NOT NULL,
	EXPANDED_RESULT VARCHAR2(120) NOT NULL,
	EFFECTIVE_DATE DATE NOT NULL,
	EXPIRY_DATE DATE NOT NULL,
	CONSTRAINT SYS_C0029139 CHECK ("COLUMN_NAME" IS NOT NULL),
	CONSTRAINT SYS_C0029140 CHECK ("CODE_ARGUMENT" IS NOT NULL),
	CONSTRAINT SYS_C0029141 CHECK ("EXPANDED_RESULT" IS NOT NULL),
	CONSTRAINT SYS_C0029142 CHECK ("EFFECTIVE_DATE" IS NOT NULL),
	CONSTRAINT SYS_C0029143 CHECK ("EXPIRY_DATE" IS NOT NULL)
);
CREATE UNIQUE INDEX "I1$_CODE_LIST_TABLE" ON THE.CODE_LIST_TABLE (COLUMN_NAME,CODE_ARGUMENT);

CREATE TABLE THE.CODE_SUBSET_TBL (
	CODE_SUBSET_NAME VARCHAR2(18) NOT NULL,
	COLUMN_NAME VARCHAR2(18) NOT NULL,
	CODE_ARGUMENT VARCHAR2(50) NOT NULL,
	IN_EFFECT_DATE DATE NULL,
	EXPIRED_DATE DATE NULL,
	CONSTRAINT SYS_C0029088 CHECK ("CODE_SUBSET_NAME" IS NOT NULL),
	CONSTRAINT SYS_C0029089 CHECK ("COLUMN_NAME" IS NOT NULL),
	CONSTRAINT SYS_C0029090 CHECK ("CODE_ARGUMENT" IS NOT NULL)
);
CREATE UNIQUE INDEX "I1$_CODE_SUBSET_TBL" ON THE.CODE_SUBSET_TBL (CODE_SUBSET_NAME,COLUMN_NAME,CODE_ARGUMENT);

CREATE TABLE THE.CODE_TABLE (
	COLUMN_NAME VARCHAR2(18) NOT NULL,
	CODE_CUSTODIAN NUMBER(10,0) NOT NULL,
	UPDATE_AUTHORITY VARCHAR2(40) NOT NULL,
	CODE_DESCRIPTION VARCHAR2(254) NOT NULL,
	DISTRIBUTE_TYPE_CD VARCHAR2(3) NOT NULL,
	CONSTRAINT SYS_C0032456 CHECK ("COLUMN_NAME" IS NOT NULL),
	CONSTRAINT SYS_C0032458 CHECK ("CODE_CUSTODIAN" IS NOT NULL),
	CONSTRAINT SYS_C0032460 CHECK ("UPDATE_AUTHORITY" IS NOT NULL),
	CONSTRAINT SYS_C0032462 CHECK ("CODE_DESCRIPTION" IS NOT NULL),
	CONSTRAINT SYS_C0032464 CHECK ("DISTRIBUTE_TYPE_CD" IS NOT NULL)
);
CREATE UNIQUE INDEX "I1$_CODE_TABLE" ON THE.CODE_TABLE (COLUMN_NAME);

CREATE TABLE THE.CLIENT_ID_TYPE_CODE (
	CLIENT_ID_TYPE_CODE VARCHAR2(4) NOT NULL,
	DESCRIPTION VARCHAR2(120) NOT NULL,
	EFFECTIVE_DATE DATE NOT NULL,
	EXPIRY_DATE DATE NOT NULL,
	UPDATE_TIMESTAMP DATE NOT NULL,
	CONSTRAINT CITC_PK PRIMARY KEY (CLIENT_ID_TYPE_CODE),
	CONSTRAINT SYS_C0012128 CHECK ("CLIENT_ID_TYPE_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0012129 CHECK ("DESCRIPTION" IS NOT NULL),
	CONSTRAINT SYS_C0012130 CHECK ("EFFECTIVE_DATE" IS NOT NULL),
	CONSTRAINT SYS_C0012131 CHECK ("EXPIRY_DATE" IS NOT NULL),
	CONSTRAINT SYS_C0012132 CHECK ("UPDATE_TIMESTAMP" IS NOT NULL)
);

CREATE TABLE THE.EXTERNAL_CLIENT_REORG_SYSTEM (
	APPLICATION_ACRONYM VARCHAR2(10) NOT NULL,
	APPLICATION_UPDATE_IND VARCHAR2(1) NOT NULL,
	ENTRY_TIMESTAMP DATE NOT NULL,
	ENTRY_USERID VARCHAR2(30) NOT NULL,
	UPDATE_TIMESTAMP DATE NOT NULL,
	UPDATE_USERID VARCHAR2(30) NOT NULL,
	CONSTRAINT ECRS_PK PRIMARY KEY (APPLICATION_ACRONYM),
	CONSTRAINT SYS_C0022987 CHECK ("APPLICATION_ACRONYM" IS NOT NULL),
	CONSTRAINT SYS_C0022988 CHECK ("APPLICATION_UPDATE_IND" IS NOT NULL),
	CONSTRAINT SYS_C0022989 CHECK ("ENTRY_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0022990 CHECK ("ENTRY_USERID" IS NOT NULL),
	CONSTRAINT SYS_C0022991 CHECK ("UPDATE_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0022992 CHECK ("UPDATE_USERID" IS NOT NULL)
);

CREATE TABLE THE.CLIENT_RELATIONSHIP_CODE (
	CLIENT_RELATIONSHIP_CODE VARCHAR2(2) NOT NULL,
	DESCRIPTION VARCHAR2(120) NOT NULL,
	EFFECTIVE_DATE DATE NOT NULL,
	EXPIRY_DATE DATE NOT NULL,
	UPDATE_TIMESTAMP DATE NOT NULL,
	CONSTRAINT RELCD_PK PRIMARY KEY (CLIENT_RELATIONSHIP_CODE),
	CONSTRAINT SYS_C0012256 CHECK ("CLIENT_RELATIONSHIP_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0012257 CHECK ("DESCRIPTION" IS NOT NULL),
	CONSTRAINT SYS_C0012258 CHECK ("EFFECTIVE_DATE" IS NOT NULL),
	CONSTRAINT SYS_C0012259 CHECK ("EXPIRY_DATE" IS NOT NULL),
	CONSTRAINT SYS_C0012260 CHECK ("UPDATE_TIMESTAMP" IS NOT NULL)
);

CREATE TABLE THE.ORG_UNIT (
	ORG_UNIT_NO NUMBER(10,0) NOT NULL,
	ORG_UNIT_CODE VARCHAR2(6) NOT NULL,
	ORG_UNIT_NAME VARCHAR2(100) NOT NULL,
	LOCATION_CODE VARCHAR2(3) NOT NULL,
	AREA_CODE VARCHAR2(3) NOT NULL,
	TELEPHONE_NO VARCHAR2(7) NOT NULL,
	ORG_LEVEL_CODE VARCHAR2(1) NOT NULL,
	OFFICE_NAME_CODE VARCHAR2(2) NOT NULL,
	ROLLUP_REGION_NO NUMBER(10,0) NOT NULL,
	ROLLUP_REGION_CODE VARCHAR2(6) NOT NULL,
	ROLLUP_DIST_NO NUMBER(10,0) NOT NULL,
	ROLLUP_DIST_CODE VARCHAR2(6) NOT NULL,
	EFFECTIVE_DATE DATE NOT NULL,
	EXPIRY_DATE DATE NOT NULL,
	UPDATE_TIMESTAMP DATE NULL,
	CONSTRAINT ORG_UNIT_PK PRIMARY KEY (ORG_UNIT_NO),
	CONSTRAINT SYS_C008931 CHECK ("ORG_UNIT_NO" IS NOT NULL),
	CONSTRAINT SYS_C008932 CHECK ("ORG_UNIT_CODE" IS NOT NULL),
	CONSTRAINT SYS_C008933 CHECK ("ORG_UNIT_NAME" IS NOT NULL),
	CONSTRAINT SYS_C008934 CHECK ("LOCATION_CODE" IS NOT NULL),
	CONSTRAINT SYS_C008935 CHECK ("AREA_CODE" IS NOT NULL),
	CONSTRAINT SYS_C008936 CHECK ("TELEPHONE_NO" IS NOT NULL),
	CONSTRAINT SYS_C008938 CHECK ("ORG_LEVEL_CODE" IS NOT NULL),
	CONSTRAINT SYS_C008939 CHECK ("OFFICE_NAME_CODE" IS NOT NULL),
	CONSTRAINT SYS_C008941 CHECK ("ROLLUP_REGION_NO" IS NOT NULL),
	CONSTRAINT SYS_C008942 CHECK ("ROLLUP_REGION_CODE" IS NOT NULL),
	CONSTRAINT SYS_C008944 CHECK ("ROLLUP_DIST_NO" IS NOT NULL),
	CONSTRAINT SYS_C008946 CHECK ("ROLLUP_DIST_CODE" IS NOT NULL),
	CONSTRAINT SYS_C008947 CHECK ("EFFECTIVE_DATE" IS NOT NULL),
	CONSTRAINT SYS_C008949 CHECK ("EXPIRY_DATE" IS NOT NULL)
);
CREATE UNIQUE INDEX "I2$_ORG_UNIT" ON THE.ORG_UNIT (ORG_UNIT_CODE,ORG_UNIT_NO);
CREATE UNIQUE INDEX "I3$_ORG_UNIT" ON THE.ORG_UNIT (ORG_UNIT_CODE);
CREATE UNIQUE INDEX "I4$_ORG_UNIT" ON THE.ORG_UNIT (ORG_UNIT_NO,ORG_UNIT_CODE,ORG_UNIT_NAME,LOCATION_CODE,TELEPHONE_NO,ORG_LEVEL_CODE,OFFICE_NAME_CODE);
CREATE INDEX "I5$_ORG_UNIT" ON THE.ORG_UNIT (ROLLUP_DIST_CODE,ROLLUP_REGION_CODE);
CREATE INDEX "I6$_ORG_UNIT" ON THE.ORG_UNIT (ROLLUP_REGION_NO,ROLLUP_DIST_NO);
CREATE INDEX "I7$_ORG_UNIT" ON THE.ORG_UNIT (ROLLUP_REGION_CODE,ROLLUP_DIST_CODE);
CREATE UNIQUE INDEX "I8$_ORG_UNIT" ON THE.ORG_UNIT (ORG_UNIT_NO,ORG_UNIT_CODE);
CREATE UNIQUE INDEX "I9$_ORG_UNIT" ON THE.ORG_UNIT (ORG_UNIT_CODE,ORG_LEVEL_CODE,ORG_UNIT_NO,ORG_UNIT_NAME);

CREATE TABLE THE.CLIENT_AUDIT_CODE (
	CLIENT_AUDIT_CODE VARCHAR2(3) NOT NULL,
	DESCRIPTION VARCHAR2(120) NOT NULL,
	EFFECTIVE_DATE DATE NOT NULL,
	EXPIRY_DATE DATE NOT NULL,
	UPDATE_TIMESTAMP DATE NOT NULL,
	CONSTRAINT CAUDC_PK PRIMARY KEY (CLIENT_AUDIT_CODE),
	CONSTRAINT SYS_C0012678 CHECK ("CLIENT_AUDIT_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0012679 CHECK ("DESCRIPTION" IS NOT NULL),
	CONSTRAINT SYS_C0012680 CHECK ("EFFECTIVE_DATE" IS NOT NULL),
	CONSTRAINT SYS_C0012681 CHECK ("EXPIRY_DATE" IS NOT NULL),
	CONSTRAINT SYS_C0012682 CHECK ("UPDATE_TIMESTAMP" IS NOT NULL)
);

CREATE TABLE THE.CLIENT_REORG_STATUS_CODE (
	CLIENT_REORG_STATUS_CODE VARCHAR2(4) NOT NULL,
	DESCRIPTION VARCHAR2(120) NOT NULL,
	EFFECTIVE_DATE DATE NOT NULL,
	EXPIRY_DATE DATE NOT NULL,
	UPDATE_TIMESTAMP DATE NOT NULL,
	CONSTRAINT CRSCD_PK PRIMARY KEY (CLIENT_REORG_STATUS_CODE),
	CONSTRAINT SYS_C0024849 CHECK ("CLIENT_REORG_STATUS_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0024850 CHECK ("DESCRIPTION" IS NOT NULL),
	CONSTRAINT SYS_C0024851 CHECK ("EFFECTIVE_DATE" IS NOT NULL),
	CONSTRAINT SYS_C0024852 CHECK ("EXPIRY_DATE" IS NOT NULL),
	CONSTRAINT SYS_C0024853 CHECK ("UPDATE_TIMESTAMP" IS NOT NULL)
);

CREATE TABLE THE.CLIENT_REORG_TYPE_CODE (
	CLIENT_REORG_TYPE_CODE VARCHAR2(4) NOT NULL,
	DESCRIPTION VARCHAR2(120) NOT NULL,
	EFFECTIVE_DATE DATE NOT NULL,
	EXPIRY_DATE DATE NOT NULL,
	UPDATE_TIMESTAMP DATE NOT NULL,
	CONSTRAINT CRTCD_PK PRIMARY KEY (CLIENT_REORG_TYPE_CODE),
	CONSTRAINT SYS_C0024555 CHECK ("CLIENT_REORG_TYPE_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0024556 CHECK ("DESCRIPTION" IS NOT NULL),
	CONSTRAINT SYS_C0024557 CHECK ("EFFECTIVE_DATE" IS NOT NULL),
	CONSTRAINT SYS_C0024558 CHECK ("EXPIRY_DATE" IS NOT NULL),
	CONSTRAINT SYS_C0024559 CHECK ("UPDATE_TIMESTAMP" IS NOT NULL)
);

CREATE TABLE THE.CLIENT_REORG_AUDIT_CODE (
	CLIENT_REORG_AUDIT_CODE VARCHAR2(3) NOT NULL,
	DESCRIPTION VARCHAR2(120) NOT NULL,
	EFFECTIVE_DATE DATE NOT NULL,
	EXPIRY_DATE DATE NOT NULL,
	UPDATE_TIMESTAMP DATE NOT NULL,
	CONSTRAINT CRAC_PK PRIMARY KEY (CLIENT_REORG_AUDIT_CODE),
	CONSTRAINT SYS_C0024973 CHECK ("CLIENT_REORG_AUDIT_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0024974 CHECK ("DESCRIPTION" IS NOT NULL),
	CONSTRAINT SYS_C0024975 CHECK ("EFFECTIVE_DATE" IS NOT NULL),
	CONSTRAINT SYS_C0024976 CHECK ("EXPIRY_DATE" IS NOT NULL),
	CONSTRAINT SYS_C0024977 CHECK ("UPDATE_TIMESTAMP" IS NOT NULL)
);

CREATE TABLE THE.CLIENT_STATUS_CODE (
	CLIENT_STATUS_CODE VARCHAR2(3) NOT NULL,
	DESCRIPTION VARCHAR2(120) NOT NULL,
	EFFECTIVE_DATE DATE NOT NULL,
	EXPIRY_DATE DATE NOT NULL,
	UPDATE_TIMESTAMP DATE NOT NULL,
	CONSTRAINT CSTC_PK PRIMARY KEY (CLIENT_STATUS_CODE),
	CONSTRAINT SYS_C0012691 CHECK ("CLIENT_STATUS_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0012692 CHECK ("DESCRIPTION" IS NOT NULL),
	CONSTRAINT SYS_C0012693 CHECK ("EFFECTIVE_DATE" IS NOT NULL),
	CONSTRAINT SYS_C0012694 CHECK ("EXPIRY_DATE" IS NOT NULL),
	CONSTRAINT SYS_C0012695 CHECK ("UPDATE_TIMESTAMP" IS NOT NULL)
);

CREATE TABLE THE.REGISTRY_COMPANY_TYPE_CODE (
	REGISTRY_COMPANY_TYPE_CODE VARCHAR2(4) NOT NULL,
	DESCRIPTION VARCHAR2(120) NOT NULL,
	EFFECTIVE_DATE DATE NOT NULL,
	EXPIRY_DATE DATE NOT NULL,
	UPDATE_TIMESTAMP DATE NOT NULL,
	CONSTRAINT CRCTC_PK PRIMARY KEY (REGISTRY_COMPANY_TYPE_CODE),
	CONSTRAINT SYS_C0012219 CHECK ("REGISTRY_COMPANY_TYPE_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0012220 CHECK ("DESCRIPTION" IS NOT NULL),
	CONSTRAINT SYS_C0012221 CHECK ("EFFECTIVE_DATE" IS NOT NULL),
	CONSTRAINT SYS_C0012222 CHECK ("EXPIRY_DATE" IS NOT NULL),
	CONSTRAINT SYS_C0012223 CHECK ("UPDATE_TIMESTAMP" IS NOT NULL)
);

CREATE TABLE THE.LOCATION (
	LOCATION_CODE VARCHAR2(3) NOT NULL,
	STREET VARCHAR2(40) NOT NULL,
	CITY VARCHAR2(15) NOT NULL,
	PROVINCE VARCHAR2(4) NOT NULL,
	PCODE VARCHAR2(6) NOT NULL,
	CONSTRAINT SYS_C0021115 CHECK ("LOCATION_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0021116 CHECK ("STREET" IS NOT NULL),
	CONSTRAINT SYS_C0021117 CHECK ("CITY" IS NOT NULL),
	CONSTRAINT SYS_C0021118 CHECK ("PROVINCE" IS NOT NULL),
	CONSTRAINT SYS_C0021119 CHECK ("PCODE" IS NOT NULL)
);
CREATE UNIQUE INDEX "I1$_LOCATION" ON THE.LOCATION (LOCATION_CODE);
CREATE INDEX "I2$_LOCATION" ON THE.LOCATION (CITY);

CREATE TABLE THE.CLIENT_REORGANIZATION (
	CLIENT_REORGANIZATION_ID NUMBER(12,0) NOT NULL,
	EFFECTIVE_DATE DATE NULL,
	EXPIRY_DATE DATE NULL,
	COMMENTS VARCHAR2(4000) NULL,
	PARTIAL_REORG_IND VARCHAR2(1) NOT NULL,
	CLIENT_REORG_STATUS_CODE VARCHAR2(4) NOT NULL,
	CLIENT_REORG_TYPE_CODE VARCHAR2(4) NOT NULL,
	COMPLETED_TIMESTAMP DATE NULL,
	REVISION_COUNT NUMBER(5,0) NOT NULL,
	ENTRY_TIMESTAMP DATE NOT NULL,
	ENTRY_USERID VARCHAR2(30) NOT NULL,
	UPDATE_TIMESTAMP DATE NOT NULL,
	UPDATE_USERID VARCHAR2(30) NOT NULL,
	CONSTRAINT CREORG_PK PRIMARY KEY (CLIENT_REORGANIZATION_ID),
	CONSTRAINT SYS_C0025015 CHECK ("CLIENT_REORGANIZATION_ID" IS NOT NULL),
	CONSTRAINT SYS_C0025016 CHECK ("PARTIAL_REORG_IND" IS NOT NULL),
	CONSTRAINT SYS_C0025017 CHECK ("CLIENT_REORG_STATUS_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0025018 CHECK ("CLIENT_REORG_TYPE_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0025019 CHECK ("REVISION_COUNT" IS NOT NULL),
	CONSTRAINT SYS_C0025020 CHECK ("ENTRY_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0025021 CHECK ("ENTRY_USERID" IS NOT NULL),
	CONSTRAINT SYS_C0025022 CHECK ("UPDATE_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0025023 CHECK ("UPDATE_USERID" IS NOT NULL)
);
CREATE INDEX CREORG_CRSC_FK_I ON THE.CLIENT_REORGANIZATION (CLIENT_REORG_STATUS_CODE);
CREATE INDEX CREORG_CRTC_FK_I ON THE.CLIENT_REORGANIZATION (CLIENT_REORG_TYPE_CODE);

ALTER TABLE THE.CLIENT_REORGANIZATION ADD CONSTRAINT CREORG_CRSC_FK FOREIGN KEY (CLIENT_REORG_STATUS_CODE) REFERENCES THE.CLIENT_REORG_STATUS_CODE(CLIENT_REORG_STATUS_CODE);
ALTER TABLE THE.CLIENT_REORGANIZATION ADD CONSTRAINT CREORG_CRTC_FK FOREIGN KEY (CLIENT_REORG_TYPE_CODE) REFERENCES THE.CLIENT_REORG_TYPE_CODE(CLIENT_REORG_TYPE_CODE);

CREATE TABLE THE.EXTERNAL_CLIENT_REORG_RESULT (
	EXTERNAL_CLIENT_REORG_RSLT_ID NUMBER(12,0) NOT NULL,
	CLIENT_REORGANIZATION_ID NUMBER(12,0) NOT NULL,
	ORIGINAL_CLIENT_NUMBER VARCHAR2(8) NOT NULL,
	ORIGINAL_CLIENT_LOCN_CODE VARCHAR2(2) NOT NULL,
	RESULTING_CLIENT_NUMBER VARCHAR2(8) NOT NULL,
	RESULTING_CLIENT_LOCN_CODE VARCHAR2(2) NOT NULL,
	APPLICATION_ACRONYM VARCHAR2(10) NOT NULL,
	EXECUTED_PROCEDURE VARCHAR2(50) NOT NULL,
	EXECUTED_TIMESTAMP DATE NOT NULL,
	EXECUTED_BY_USERID VARCHAR2(30) NOT NULL,
	UPDATED_TABLE VARCHAR2(50) NULL,
	UPDATE_ROW_COUNT NUMBER(9,0) NULL,
	ERROR_MESSAGE VARCHAR2(2000) NULL,
	CONSTRAINT ECRR_PK PRIMARY KEY (EXTERNAL_CLIENT_REORG_RSLT_ID),
	CONSTRAINT SYS_C0023039 CHECK ("EXTERNAL_CLIENT_REORG_RSLT_ID" IS NOT NULL),
	CONSTRAINT SYS_C0023040 CHECK ("CLIENT_REORGANIZATION_ID" IS NOT NULL),
	CONSTRAINT SYS_C0023041 CHECK ("ORIGINAL_CLIENT_NUMBER" IS NOT NULL),
	CONSTRAINT SYS_C0023042 CHECK ("ORIGINAL_CLIENT_LOCN_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0023043 CHECK ("RESULTING_CLIENT_NUMBER" IS NOT NULL),
	CONSTRAINT SYS_C0023044 CHECK ("RESULTING_CLIENT_LOCN_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0023045 CHECK ("APPLICATION_ACRONYM" IS NOT NULL),
	CONSTRAINT SYS_C0023046 CHECK ("EXECUTED_PROCEDURE" IS NOT NULL),
	CONSTRAINT SYS_C0023047 CHECK ("EXECUTED_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0023048 CHECK ("EXECUTED_BY_USERID" IS NOT NULL)
);
CREATE INDEX ECRR_CRD_FK_I ON THE.EXTERNAL_CLIENT_REORG_RESULT (CLIENT_REORGANIZATION_ID,ORIGINAL_CLIENT_NUMBER,ORIGINAL_CLIENT_LOCN_CODE,RESULTING_CLIENT_NUMBER,RESULTING_CLIENT_LOCN_CODE);
CREATE INDEX ECRR_ECRS_FK_I ON THE.EXTERNAL_CLIENT_REORG_RESULT (APPLICATION_ACRONYM);

ALTER TABLE THE.EXTERNAL_CLIENT_REORG_RESULT ADD CONSTRAINT ECRR_CRD_FK FOREIGN KEY (CLIENT_REORGANIZATION_ID,ORIGINAL_CLIENT_NUMBER,ORIGINAL_CLIENT_LOCN_CODE,RESULTING_CLIENT_NUMBER,RESULTING_CLIENT_LOCN_CODE) REFERENCES THE.CLIENT_REORG_DETAIL(CLIENT_REORGANIZATION_ID,ORIGINAL_CLIENT_NUMBER,ORIGINAL_CLIENT_LOCN_CODE,RESULTING_CLIENT_NUMBER,RESULTING_CLIENT_LOCN_CODE);
ALTER TABLE THE.EXTERNAL_CLIENT_REORG_RESULT ADD CONSTRAINT ECRR_ECRS_FK FOREIGN KEY (APPLICATION_ACRONYM) REFERENCES THE.EXTERNAL_CLIENT_REORG_SYSTEM(APPLICATION_ACRONYM);

CREATE TABLE THE.CLIENT_RELATIONSHIP_TYPE_XREF (
	CLIENT_RELATIONSHIP_CODE VARCHAR2(2) NOT NULL,
	PRIMARY_CLIENT_TYPE_CODE VARCHAR2(1) NOT NULL,
	SECONDARY_CLIENT_TYPE_CODE VARCHAR2(1) NOT NULL,
	REVISION_COUNT NUMBER(5,0) NOT NULL,
	ENTRY_USERID VARCHAR2(30) NOT NULL,
	ENTRY_TIMESTAMP DATE NOT NULL,
	UPDATE_USERID VARCHAR2(30) NOT NULL,
	UPDATE_TIMESTAMP DATE NOT NULL,
	CONSTRAINT CRX_PK PRIMARY KEY (CLIENT_RELATIONSHIP_CODE,SECONDARY_CLIENT_TYPE_CODE,PRIMARY_CLIENT_TYPE_CODE),
	CONSTRAINT SYS_C0019306 CHECK ("CLIENT_RELATIONSHIP_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0019307 CHECK ("PRIMARY_CLIENT_TYPE_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0019308 CHECK ("SECONDARY_CLIENT_TYPE_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0019309 CHECK ("REVISION_COUNT" IS NOT NULL),
	CONSTRAINT SYS_C0019310 CHECK ("ENTRY_USERID" IS NOT NULL),
	CONSTRAINT SYS_C0019311 CHECK ("ENTRY_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0019312 CHECK ("UPDATE_USERID" IS NOT NULL),
	CONSTRAINT SYS_C0019313 CHECK ("UPDATE_TIMESTAMP" IS NOT NULL)
);
CREATE INDEX CRX_PCTC_FK_I ON THE.CLIENT_RELATIONSHIP_TYPE_XREF (PRIMARY_CLIENT_TYPE_CODE);
CREATE INDEX CRX_RELCD_FK_I ON THE.CLIENT_RELATIONSHIP_TYPE_XREF (CLIENT_RELATIONSHIP_CODE);
CREATE INDEX CRX_SCTC_FK_I ON THE.CLIENT_RELATIONSHIP_TYPE_XREF (SECONDARY_CLIENT_TYPE_CODE);


ALTER TABLE THE.CLIENT_RELATIONSHIP_TYPE_XREF ADD CONSTRAINT CRX_PCTC_FK FOREIGN KEY (PRIMARY_CLIENT_TYPE_CODE) REFERENCES THE.CLIENT_TYPE_CODE(CLIENT_TYPE_CODE);
ALTER TABLE THE.CLIENT_RELATIONSHIP_TYPE_XREF ADD CONSTRAINT CRX_RELCD_FK FOREIGN KEY (CLIENT_RELATIONSHIP_CODE) REFERENCES THE.CLIENT_RELATIONSHIP_CODE(CLIENT_RELATIONSHIP_CODE);
ALTER TABLE THE.CLIENT_RELATIONSHIP_TYPE_XREF ADD CONSTRAINT CRX_SCTC_FK FOREIGN KEY (SECONDARY_CLIENT_TYPE_CODE) REFERENCES THE.CLIENT_TYPE_CODE(CLIENT_TYPE_CODE);

CREATE TABLE THE.BUSINESS_CONTACT_CODE (
	BUSINESS_CONTACT_CODE VARCHAR2(3) NOT NULL,
	DESCRIPTION VARCHAR2(120) NOT NULL,
	EFFECTIVE_DATE DATE NOT NULL,
	EXPIRY_DATE DATE NOT NULL,
	UPDATE_TIMESTAMP DATE NOT NULL,
	CONSTRAINT BCC_PK PRIMARY KEY (BUSINESS_CONTACT_CODE),
	CONSTRAINT SYS_C0012316 CHECK ("BUSINESS_CONTACT_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0012317 CHECK ("DESCRIPTION" IS NOT NULL),
	CONSTRAINT SYS_C0012318 CHECK ("EFFECTIVE_DATE" IS NOT NULL),
	CONSTRAINT SYS_C0012319 CHECK ("EXPIRY_DATE" IS NOT NULL),
	CONSTRAINT SYS_C0012320 CHECK ("UPDATE_TIMESTAMP" IS NOT NULL)
);

CREATE TABLE THE.MAILING_COUNTRY (
	COUNTRY_NAME VARCHAR2(50) NOT NULL,
	COUNTRY_CODE VARCHAR2(3) NULL,
	CONSTRAINT CTRY_PK PRIMARY KEY (COUNTRY_NAME),
	CONSTRAINT SYS_C0012419 CHECK ("COUNTRY_NAME" IS NOT NULL)
);

CREATE TABLE THE.MAILING_PROVINCE_STATE (
	COUNTRY_NAME VARCHAR2(50) NOT NULL,
	PROVINCE_STATE_NAME VARCHAR2(50) NOT NULL,
	PROVINCE_STATE_CODE VARCHAR2(2) NULL,
	CONSTRAINT PROV_PK PRIMARY KEY (PROVINCE_STATE_NAME,COUNTRY_NAME),
	CONSTRAINT SYS_C0012368 CHECK ("COUNTRY_NAME" IS NOT NULL),
	CONSTRAINT SYS_C0012369 CHECK ("PROVINCE_STATE_NAME" IS NOT NULL)
);
CREATE INDEX PROV_CTRY_FK_I ON THE.MAILING_PROVINCE_STATE (COUNTRY_NAME);
ALTER TABLE THE.MAILING_PROVINCE_STATE ADD CONSTRAINT PROV_CTRY_FK FOREIGN KEY (COUNTRY_NAME) REFERENCES THE.MAILING_COUNTRY(COUNTRY_NAME);

CREATE TABLE THE.MAILING_CITY (
	COUNTRY_NAME VARCHAR2(50) NOT NULL,
	PROVINCE_STATE_NAME VARCHAR2(50) NOT NULL,
	CITY_NAME VARCHAR2(30) NOT NULL,
	CONSTRAINT CTY_PK PRIMARY KEY (CITY_NAME,PROVINCE_STATE_NAME,COUNTRY_NAME),
	CONSTRAINT SYS_C0010890 CHECK ("COUNTRY_NAME" IS NOT NULL),
	CONSTRAINT SYS_C0010893 CHECK ("PROVINCE_STATE_NAME" IS NOT NULL),
	CONSTRAINT SYS_C0010896 CHECK ("CITY_NAME" IS NOT NULL)
);
CREATE INDEX CTY_PROV_FK_I ON THE.MAILING_CITY (PROVINCE_STATE_NAME,COUNTRY_NAME);
ALTER TABLE THE.MAILING_CITY ADD CONSTRAINT CTY_PROV_FK FOREIGN KEY (PROVINCE_STATE_NAME,COUNTRY_NAME) REFERENCES THE.MAILING_PROVINCE_STATE(PROVINCE_STATE_NAME,COUNTRY_NAME);

CREATE TABLE THE.CLIENT_REORG_AUDIT (
	CLIENT_REORG_AUDIT_ID NUMBER(12,0) NOT NULL,
	CLIENT_REORG_AUDIT_CODE VARCHAR2(3) NOT NULL,
	CLIENT_REORGANIZATION_ID NUMBER(12,0) NOT NULL,
	EFFECTIVE_DATE DATE NULL,
	EXPIRY_DATE DATE NULL,
	COMMENTS VARCHAR2(4000) NULL,
	PARTIAL_REORG_IND VARCHAR2(1) NOT NULL,
	CLIENT_REORG_STATUS_CODE VARCHAR2(4) NOT NULL,
	CLIENT_REORG_TYPE_CODE VARCHAR2(4) NOT NULL,
	COMPLETED_TIMESTAMP DATE NULL,
	ENTRY_TIMESTAMP DATE NOT NULL,
	ENTRY_USERID VARCHAR2(30) NOT NULL,
	UPDATE_TIMESTAMP DATE NOT NULL,
	UPDATE_USERID VARCHAR2(30) NOT NULL,
	CONSTRAINT CREA_PK PRIMARY KEY (CLIENT_REORG_AUDIT_ID),
	CONSTRAINT SYS_C0024919 CHECK ("CLIENT_REORG_AUDIT_ID" IS NOT NULL),
	CONSTRAINT SYS_C0024920 CHECK ("CLIENT_REORG_AUDIT_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0024921 CHECK ("CLIENT_REORGANIZATION_ID" IS NOT NULL),
	CONSTRAINT SYS_C0024922 CHECK ("PARTIAL_REORG_IND" IS NOT NULL),
	CONSTRAINT SYS_C0024923 CHECK ("CLIENT_REORG_STATUS_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0024924 CHECK ("CLIENT_REORG_TYPE_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0024925 CHECK ("ENTRY_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0024926 CHECK ("ENTRY_USERID" IS NOT NULL),
	CONSTRAINT SYS_C0024927 CHECK ("UPDATE_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0024928 CHECK ("UPDATE_USERID" IS NOT NULL)
);
CREATE INDEX CREA_AAC_FK_I ON THE.CLIENT_REORG_AUDIT (CLIENT_REORG_AUDIT_CODE);
ALTER TABLE THE.CLIENT_REORG_AUDIT ADD CONSTRAINT CREA_CRAC_FK FOREIGN KEY (CLIENT_REORG_AUDIT_CODE) REFERENCES THE.CLIENT_REORG_AUDIT_CODE(CLIENT_REORG_AUDIT_CODE);


CREATE TABLE THE.CLIENT_TYPE_COMPANY_XREF (
	CLIENT_TYPE_CODE VARCHAR2(1) NOT NULL,
	REGISTRY_COMPANY_TYPE_CODE VARCHAR2(4) NOT NULL,
	ADD_USERID VARCHAR2(30) NOT NULL,
	ADD_TIMESTAMP DATE NOT NULL,
	UPDATE_USERID VARCHAR2(30) NOT NULL,
	UPDATE_TIMESTAMP DATE NOT NULL,
	CONSTRAINT CTCX_PK PRIMARY KEY (CLIENT_TYPE_CODE,REGISTRY_COMPANY_TYPE_CODE),
	CONSTRAINT SYS_C0011915 CHECK ("CLIENT_TYPE_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0011916 CHECK ("REGISTRY_COMPANY_TYPE_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0011917 CHECK ("ADD_USERID" IS NOT NULL),
	CONSTRAINT SYS_C0011918 CHECK ("ADD_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0011919 CHECK ("UPDATE_USERID" IS NOT NULL),
	CONSTRAINT SYS_C0011920 CHECK ("UPDATE_TIMESTAMP" IS NOT NULL)
);
CREATE INDEX CTCX_CRCTC_FK_I ON THE.CLIENT_TYPE_COMPANY_XREF (REGISTRY_COMPANY_TYPE_CODE);
CREATE INDEX CTCX_CTC_FK_I ON THE.CLIENT_TYPE_COMPANY_XREF (CLIENT_TYPE_CODE);
ALTER TABLE THE.CLIENT_TYPE_COMPANY_XREF ADD CONSTRAINT CTCX_CRCTC_FK FOREIGN KEY (REGISTRY_COMPANY_TYPE_CODE) REFERENCES THE.REGISTRY_COMPANY_TYPE_CODE(REGISTRY_COMPANY_TYPE_CODE);
ALTER TABLE THE.CLIENT_TYPE_COMPANY_XREF ADD CONSTRAINT CTCX_CTC_FK FOREIGN KEY (CLIENT_TYPE_CODE) REFERENCES THE.CLIENT_TYPE_CODE(CLIENT_TYPE_CODE);


CREATE TABLE THE.FOREST_CLIENT (
	CLIENT_NUMBER VARCHAR2(8) NOT NULL,
	CLIENT_NAME VARCHAR2(60) NOT NULL,
	LEGAL_FIRST_NAME VARCHAR2(30) NULL,
	LEGAL_MIDDLE_NAME VARCHAR2(30) NULL,
	CLIENT_STATUS_CODE VARCHAR2(3) NOT NULL,
	CLIENT_TYPE_CODE VARCHAR2(1) NOT NULL,
	BIRTHDATE DATE NULL,
	CLIENT_ID_TYPE_CODE VARCHAR2(4) NULL,
	CLIENT_IDENTIFICATION VARCHAR2(40) NULL,
	REGISTRY_COMPANY_TYPE_CODE VARCHAR2(4) NULL,
	CORP_REGN_NMBR VARCHAR2(9) NULL,
	CLIENT_ACRONYM VARCHAR2(8) NULL,
	WCB_FIRM_NUMBER VARCHAR2(6) NULL,
	OCG_SUPPLIER_NMBR VARCHAR2(10) NULL,
	CLIENT_COMMENT VARCHAR2(4000) NULL,
	ADD_TIMESTAMP DATE NOT NULL,
	ADD_USERID VARCHAR2(30) NOT NULL,
	ADD_ORG_UNIT NUMBER(10,0) NOT NULL,
	UPDATE_TIMESTAMP DATE NOT NULL,
	UPDATE_USERID VARCHAR2(30) NOT NULL,
	UPDATE_ORG_UNIT NUMBER(10,0) NOT NULL,
	REVISION_COUNT NUMBER(5,0) NOT NULL,
	CONSTRAINT FOREST_CLIENT_PK PRIMARY KEY (CLIENT_NUMBER),
	CONSTRAINT SYS_C0029588 CHECK ("CLIENT_NUMBER" IS NOT NULL),
	CONSTRAINT SYS_C0029589 CHECK ("CLIENT_NAME" IS NOT NULL),
	CONSTRAINT SYS_C0029590 CHECK ("CLIENT_STATUS_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0029591 CHECK ("CLIENT_TYPE_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0029592 CHECK ("ADD_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0029593 CHECK ("ADD_USERID" IS NOT NULL),
	CONSTRAINT SYS_C0029594 CHECK ("ADD_ORG_UNIT" IS NOT NULL),
	CONSTRAINT SYS_C0029595 CHECK ("UPDATE_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0029596 CHECK ("UPDATE_USERID" IS NOT NULL),
	CONSTRAINT SYS_C0029597 CHECK ("UPDATE_ORG_UNIT" IS NOT NULL),
	CONSTRAINT SYS_C0029598 CHECK ("REVISION_COUNT" IS NOT NULL)
);
CREATE UNIQUE INDEX FC_ACRONYM_I ON THE.FOREST_CLIENT (CLIENT_ACRONYM);
CREATE INDEX FC_CITC_FK_I ON THE.FOREST_CLIENT (CLIENT_ID_TYPE_CODE);
CREATE INDEX FC_CSC_FK_I ON THE.FOREST_CLIENT (CLIENT_STATUS_CODE);
CREATE INDEX FC_CTCX_FK_I ON THE.FOREST_CLIENT (CLIENT_TYPE_CODE,REGISTRY_COMPANY_TYPE_CODE);
CREATE INDEX FC_OU_FK_I ON THE.FOREST_CLIENT (ADD_ORG_UNIT);
CREATE INDEX FC_OU_IS_UPDATED_BY_FK_I ON THE.FOREST_CLIENT (UPDATE_ORG_UNIT);
CREATE UNIQUE INDEX "I2$_FOREST_CLIENT" ON THE.FOREST_CLIENT (CLIENT_NAME,LEGAL_FIRST_NAME,LEGAL_MIDDLE_NAME,CLIENT_NUMBER);
CREATE INDEX "I4$_FOREST_CLIENT" ON THE.FOREST_CLIENT (OCG_SUPPLIER_NMBR);
CREATE INDEX "I5$_FOREST_CLIENT" ON THE.FOREST_CLIENT (CORP_REGN_NMBR);
ALTER TABLE THE.FOREST_CLIENT ADD CONSTRAINT FC_CITC_FK FOREIGN KEY (CLIENT_ID_TYPE_CODE) REFERENCES THE.CLIENT_ID_TYPE_CODE(CLIENT_ID_TYPE_CODE);
ALTER TABLE THE.FOREST_CLIENT ADD CONSTRAINT FC_CSC_FK FOREIGN KEY (CLIENT_STATUS_CODE) REFERENCES THE.CLIENT_STATUS_CODE(CLIENT_STATUS_CODE);
ALTER TABLE THE.FOREST_CLIENT ADD CONSTRAINT FC_CTCX_FK FOREIGN KEY (CLIENT_TYPE_CODE,REGISTRY_COMPANY_TYPE_CODE) REFERENCES THE.CLIENT_TYPE_COMPANY_XREF(CLIENT_TYPE_CODE,REGISTRY_COMPANY_TYPE_CODE);
ALTER TABLE THE.FOREST_CLIENT ADD CONSTRAINT FC_OU_FK FOREIGN KEY (ADD_ORG_UNIT) REFERENCES THE.ORG_UNIT(ORG_UNIT_NO);
ALTER TABLE THE.FOREST_CLIENT ADD CONSTRAINT FC_OU_IS_UPDATED_BY_FK FOREIGN KEY (UPDATE_ORG_UNIT) REFERENCES THE.ORG_UNIT(ORG_UNIT_NO);


CREATE TABLE THE.CLIENT_REORG_LINK (
	CLIENT_REORGANIZATION_ID NUMBER(12,0) NOT NULL,
	ORIGINAL_CLIENT_NUMBER VARCHAR2(8) NOT NULL,
	RESULTING_CLIENT_NUMBER VARCHAR2(8) NOT NULL,
	REVISION_COUNT NUMBER(5,0) NOT NULL,
	ENTRY_TIMESTAMP DATE NOT NULL,
	ENTRY_USERID VARCHAR2(30) NOT NULL,
	UPDATE_TIMESTAMP DATE NOT NULL,
	UPDATE_USERID VARCHAR2(30) NOT NULL,
	CONSTRAINT CRL_PK PRIMARY KEY (CLIENT_REORGANIZATION_ID,ORIGINAL_CLIENT_NUMBER,RESULTING_CLIENT_NUMBER),
	CONSTRAINT SYS_C0023174 CHECK ("CLIENT_REORGANIZATION_ID" IS NOT NULL),
	CONSTRAINT SYS_C0023175 CHECK ("ORIGINAL_CLIENT_NUMBER" IS NOT NULL),
	CONSTRAINT SYS_C0023176 CHECK ("RESULTING_CLIENT_NUMBER" IS NOT NULL),
	CONSTRAINT SYS_C0023177 CHECK ("REVISION_COUNT" IS NOT NULL),
	CONSTRAINT SYS_C0023178 CHECK ("ENTRY_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0023179 CHECK ("ENTRY_USERID" IS NOT NULL),
	CONSTRAINT SYS_C0023180 CHECK ("UPDATE_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0023181 CHECK ("UPDATE_USERID" IS NOT NULL)
);
CREATE INDEX CRL_CR_FK_I ON THE.CLIENT_REORG_LINK (CLIENT_REORGANIZATION_ID);
CREATE INDEX CRL_FC_FK_I ON THE.CLIENT_REORG_LINK (ORIGINAL_CLIENT_NUMBER);
CREATE INDEX CRL_FC_INCLUDES_RESULTING_FK_I ON THE.CLIENT_REORG_LINK (RESULTING_CLIENT_NUMBER);

ALTER TABLE THE.CLIENT_REORG_LINK ADD CONSTRAINT CRL_CR_FK FOREIGN KEY (CLIENT_REORGANIZATION_ID) REFERENCES THE.CLIENT_REORGANIZATION(CLIENT_REORGANIZATION_ID);
ALTER TABLE THE.CLIENT_REORG_LINK ADD CONSTRAINT CRL_FC_FK FOREIGN KEY (ORIGINAL_CLIENT_NUMBER) REFERENCES THE.FOREST_CLIENT(CLIENT_NUMBER);
ALTER TABLE THE.CLIENT_REORG_LINK ADD CONSTRAINT CRL_FC_INCLUDES_RESULTING_FK FOREIGN KEY (RESULTING_CLIENT_NUMBER) REFERENCES THE.FOREST_CLIENT(CLIENT_NUMBER);

CREATE TABLE THE.CLIENT_LOCATION (
	CLIENT_NUMBER VARCHAR2(8) NOT NULL,
	CLIENT_LOCN_CODE VARCHAR2(2) NOT NULL,
	CLIENT_LOCN_NAME VARCHAR2(40) NULL,
	HDBS_COMPANY_CODE VARCHAR2(5) NULL,
	ADDRESS_1 VARCHAR2(40) NOT NULL,
	ADDRESS_2 VARCHAR2(40) NULL,
	ADDRESS_3 VARCHAR2(40) NULL,
	CITY VARCHAR2(30) NOT NULL,
	PROVINCE VARCHAR2(50) NULL,
	POSTAL_CODE VARCHAR2(10) NULL,
	COUNTRY VARCHAR2(50) NOT NULL,
	BUSINESS_PHONE VARCHAR2(10) NULL,
	HOME_PHONE VARCHAR2(10) NULL,
	CELL_PHONE VARCHAR2(10) NULL,
	FAX_NUMBER VARCHAR2(10) NULL,
	EMAIL_ADDRESS VARCHAR2(128) NULL,
	LOCN_EXPIRED_IND VARCHAR2(1) NOT NULL,
	RETURNED_MAIL_DATE DATE NULL,
	TRUST_LOCATION_IND VARCHAR2(1) NOT NULL,
	CLI_LOCN_COMMENT VARCHAR2(4000) NULL,
	UPDATE_TIMESTAMP DATE NOT NULL,
	UPDATE_USERID VARCHAR2(30) NOT NULL,
	UPDATE_ORG_UNIT NUMBER(10,0) NOT NULL,
	ADD_TIMESTAMP DATE NOT NULL,
	ADD_USERID VARCHAR2(30) NOT NULL,
	ADD_ORG_UNIT NUMBER(10,0) NOT NULL,
	REVISION_COUNT NUMBER(5,0) NOT NULL,
	CONSTRAINT "BIN$A8NnKNSZAszgVAAQ4CNh2g==$0" CHECK ("UPDATE_USERID" IS NOT NULL),
	CONSTRAINT "BIN$A8NnKNSaAszgVAAQ4CNh2g==$0" CHECK ("UPDATE_ORG_UNIT" IS NOT NULL),
	CONSTRAINT "BIN$A8NnKNSbAszgVAAQ4CNh2g==$0" CHECK ("ADD_TIMESTAMP" IS NOT NULL),
	CONSTRAINT "BIN$A8NnKNScAszgVAAQ4CNh2g==$0" CHECK ("ADD_USERID" IS NOT NULL),
	CONSTRAINT "BIN$A8NnKNSdAszgVAAQ4CNh2g==$0" CHECK ("ADD_ORG_UNIT" IS NOT NULL),
	CONSTRAINT "BIN$A8NnKNSeAszgVAAQ4CNh2g==$0" CHECK ("REVISION_COUNT" IS NOT NULL),
	CONSTRAINT CLIENT_LOCATION_PK PRIMARY KEY (CLIENT_NUMBER,CLIENT_LOCN_CODE),
	CONSTRAINT SYS_C0030524 CHECK ("CLIENT_NUMBER" IS NOT NULL),
	CONSTRAINT SYS_C0030525 CHECK ("CLIENT_LOCN_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0030526 CHECK ("ADDRESS_1" IS NOT NULL),
	CONSTRAINT SYS_C0030527 CHECK ("CITY" IS NOT NULL),
	CONSTRAINT SYS_C0030528 CHECK ("COUNTRY" IS NOT NULL),
	CONSTRAINT SYS_C0030529 CHECK ("LOCN_EXPIRED_IND" IS NOT NULL),
	CONSTRAINT SYS_C0030530 CHECK ("TRUST_LOCATION_IND" IS NOT NULL),
	CONSTRAINT SYS_C0030531 CHECK ("UPDATE_TIMESTAMP" IS NOT NULL)
);
CREATE INDEX CL_FC_FK_I ON THE.CLIENT_LOCATION (CLIENT_NUMBER);
CREATE INDEX CL_OU_FK_I ON THE.CLIENT_LOCATION (UPDATE_ORG_UNIT);
CREATE INDEX CL_OU_IS_CREATED_BY_FK_I ON THE.CLIENT_LOCATION (ADD_ORG_UNIT);
CREATE INDEX "I2$_CLIENT_LOCATION" ON THE.CLIENT_LOCATION (HDBS_COMPANY_CODE);
ALTER TABLE THE.CLIENT_LOCATION ADD CONSTRAINT CL_FC_FK FOREIGN KEY (CLIENT_NUMBER) REFERENCES THE.FOREST_CLIENT(CLIENT_NUMBER);
ALTER TABLE THE.CLIENT_LOCATION ADD CONSTRAINT CL_OU_FK FOREIGN KEY (UPDATE_ORG_UNIT) REFERENCES THE.ORG_UNIT(ORG_UNIT_NO);
ALTER TABLE THE.CLIENT_LOCATION ADD CONSTRAINT CL_OU_IS_CREATED_BY_FK FOREIGN KEY (ADD_ORG_UNIT) REFERENCES THE.ORG_UNIT(ORG_UNIT_NO);

CREATE TABLE THE.CLIENT_CONTACT (
	CLIENT_CONTACT_ID NUMBER(12,0) NOT NULL,
	CLIENT_NUMBER VARCHAR2(8) NOT NULL,
	CLIENT_LOCN_CODE VARCHAR2(2) NOT NULL,
	BUS_CONTACT_CODE VARCHAR2(3) NOT NULL,
	CONTACT_NAME VARCHAR2(120) NOT NULL,
	BUSINESS_PHONE VARCHAR2(10) NULL,
	CELL_PHONE VARCHAR2(10) NULL,
	FAX_NUMBER VARCHAR2(10) NULL,
	EMAIL_ADDRESS VARCHAR2(128) NULL,
	UPDATE_TIMESTAMP DATE NOT NULL,
	UPDATE_USERID VARCHAR2(30) NOT NULL,
	UPDATE_ORG_UNIT NUMBER(10,0) NOT NULL,
	ADD_TIMESTAMP DATE NOT NULL,
	ADD_USERID VARCHAR2(30) NOT NULL,
	ADD_ORG_UNIT NUMBER(10,0) NOT NULL,
	REVISION_COUNT NUMBER(5,0) NOT NULL,
	CONSTRAINT CLC_PK PRIMARY KEY (CLIENT_CONTACT_ID),
	CONSTRAINT SYS_C0030038 CHECK ("CLIENT_CONTACT_ID" IS NOT NULL),
	CONSTRAINT SYS_C0030040 CHECK ("CLIENT_NUMBER" IS NOT NULL),
	CONSTRAINT SYS_C0030042 CHECK ("CLIENT_LOCN_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0030044 CHECK ("BUS_CONTACT_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0030046 CHECK ("CONTACT_NAME" IS NOT NULL),
	CONSTRAINT SYS_C0030048 CHECK ("UPDATE_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0030050 CHECK ("UPDATE_USERID" IS NOT NULL),
	CONSTRAINT SYS_C0030051 CHECK ("UPDATE_ORG_UNIT" IS NOT NULL),
	CONSTRAINT SYS_C0030052 CHECK ("ADD_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0030053 CHECK ("ADD_USERID" IS NOT NULL),
	CONSTRAINT SYS_C0030054 CHECK ("ADD_ORG_UNIT" IS NOT NULL),
	CONSTRAINT SYS_C0030055 CHECK ("REVISION_COUNT" IS NOT NULL)
);
CREATE INDEX CC_BCC_FK_I ON THE.CLIENT_CONTACT (BUS_CONTACT_CODE);
CREATE INDEX CC_CL_FK_I ON THE.CLIENT_CONTACT (CLIENT_NUMBER,CLIENT_LOCN_CODE);
CREATE INDEX CC_OU_FK_I ON THE.CLIENT_CONTACT (ADD_ORG_UNIT);
CREATE INDEX CC_OU_IS_UPDATED_BY_FK_I ON THE.CLIENT_CONTACT (UPDATE_ORG_UNIT);
ALTER TABLE THE.CLIENT_CONTACT ADD CONSTRAINT CC_BCC_FK FOREIGN KEY (BUS_CONTACT_CODE) REFERENCES THE.BUSINESS_CONTACT_CODE(BUSINESS_CONTACT_CODE);
ALTER TABLE THE.CLIENT_CONTACT ADD CONSTRAINT CC_CL_FK FOREIGN KEY (CLIENT_NUMBER,CLIENT_LOCN_CODE) REFERENCES THE.CLIENT_LOCATION(CLIENT_NUMBER,CLIENT_LOCN_CODE);
ALTER TABLE THE.CLIENT_CONTACT ADD CONSTRAINT CC_OU_FK FOREIGN KEY (ADD_ORG_UNIT) REFERENCES THE.ORG_UNIT(ORG_UNIT_NO);
ALTER TABLE THE.CLIENT_CONTACT ADD CONSTRAINT CC_OU_IS_UPDATED_BY_FK FOREIGN KEY (UPDATE_ORG_UNIT) REFERENCES THE.ORG_UNIT(ORG_UNIT_NO);

CREATE TABLE THE.CLIENT_REORG_DETAIL (
	CLIENT_REORGANIZATION_ID NUMBER(12,0) NOT NULL,
	ORIGINAL_CLIENT_NUMBER VARCHAR2(8) NOT NULL,
	ORIGINAL_CLIENT_LOCN_CODE VARCHAR2(2) NOT NULL,
	RESULTING_CLIENT_NUMBER VARCHAR2(8) NOT NULL,
	RESULTING_CLIENT_LOCN_CODE VARCHAR2(2) NOT NULL,
	REVISION_COUNT NUMBER(5,0) NOT NULL,
	ENTRY_TIMESTAMP DATE NOT NULL,
	ENTRY_USERID VARCHAR2(30) NOT NULL,
	UPDATE_TIMESTAMP DATE NOT NULL,
	UPDATE_USERID VARCHAR2(30) NOT NULL,
	CONSTRAINT CRD_PK PRIMARY KEY (CLIENT_REORGANIZATION_ID,ORIGINAL_CLIENT_NUMBER,ORIGINAL_CLIENT_LOCN_CODE,RESULTING_CLIENT_NUMBER,RESULTING_CLIENT_LOCN_CODE),
	CONSTRAINT SYS_C0023091 CHECK ("CLIENT_REORGANIZATION_ID" IS NOT NULL),
	CONSTRAINT SYS_C0023093 CHECK ("ORIGINAL_CLIENT_NUMBER" IS NOT NULL),
	CONSTRAINT SYS_C0023095 CHECK ("ORIGINAL_CLIENT_LOCN_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0023097 CHECK ("RESULTING_CLIENT_NUMBER" IS NOT NULL),
	CONSTRAINT SYS_C0023099 CHECK ("RESULTING_CLIENT_LOCN_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0023101 CHECK ("REVISION_COUNT" IS NOT NULL),
	CONSTRAINT SYS_C0023103 CHECK ("ENTRY_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0023105 CHECK ("ENTRY_USERID" IS NOT NULL),
	CONSTRAINT SYS_C0023107 CHECK ("UPDATE_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0023109 CHECK ("UPDATE_USERID" IS NOT NULL)
);
CREATE INDEX CRD_CL_FK_I ON THE.CLIENT_REORG_DETAIL (ORIGINAL_CLIENT_NUMBER,ORIGINAL_CLIENT_LOCN_CODE);
CREATE INDEX CRD_CL_INCLUDES_RESULTING_FK_I ON THE.CLIENT_REORG_DETAIL (RESULTING_CLIENT_NUMBER,RESULTING_CLIENT_LOCN_CODE);
CREATE INDEX CRD_CR_FK_I ON THE.CLIENT_REORG_DETAIL (CLIENT_REORGANIZATION_ID);
ALTER TABLE THE.CLIENT_REORG_DETAIL ADD CONSTRAINT CRD_CL_FK FOREIGN KEY (ORIGINAL_CLIENT_NUMBER,ORIGINAL_CLIENT_LOCN_CODE) REFERENCES THE.CLIENT_LOCATION(CLIENT_NUMBER,CLIENT_LOCN_CODE);
ALTER TABLE THE.CLIENT_REORG_DETAIL ADD CONSTRAINT CRD_CL_INCLUDES_RESULTING_FK FOREIGN KEY (RESULTING_CLIENT_NUMBER,RESULTING_CLIENT_LOCN_CODE) REFERENCES THE.CLIENT_LOCATION(CLIENT_NUMBER,CLIENT_LOCN_CODE);
ALTER TABLE THE.CLIENT_REORG_DETAIL ADD CONSTRAINT CRD_CR_FK FOREIGN KEY (CLIENT_REORGANIZATION_ID) REFERENCES THE.CLIENT_REORGANIZATION(CLIENT_REORGANIZATION_ID);

CREATE TABLE THE.CLIENT_DOING_BUSINESS_AS (
	CLIENT_DBA_ID NUMBER(12,0) NOT NULL,
	CLIENT_NUMBER VARCHAR2(8) NOT NULL,
	DOING_BUSINESS_AS_NAME VARCHAR2(120) NOT NULL,
	UPDATE_TIMESTAMP DATE NOT NULL,
	UPDATE_USERID VARCHAR2(30) NOT NULL,
	UPDATE_ORG_UNIT NUMBER(10,0) NOT NULL,
	ADD_TIMESTAMP DATE NOT NULL,
	ADD_USERID VARCHAR2(30) NOT NULL,
	ADD_ORG_UNIT NUMBER(10,0) NOT NULL,
	REVISION_COUNT NUMBER(5,0) NOT NULL,
	CONSTRAINT CDBA_PK PRIMARY KEY (CLIENT_DBA_ID),
	CONSTRAINT SYS_C0011796 CHECK ("CLIENT_DBA_ID" IS NOT NULL),
	CONSTRAINT SYS_C0011797 CHECK ("CLIENT_NUMBER" IS NOT NULL),
	CONSTRAINT SYS_C0011798 CHECK ("DOING_BUSINESS_AS_NAME" IS NOT NULL),
	CONSTRAINT SYS_C0011799 CHECK ("UPDATE_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0011800 CHECK ("UPDATE_USERID" IS NOT NULL),
	CONSTRAINT SYS_C0011801 CHECK ("UPDATE_ORG_UNIT" IS NOT NULL),
	CONSTRAINT SYS_C0011802 CHECK ("ADD_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0011803 CHECK ("ADD_USERID" IS NOT NULL),
	CONSTRAINT SYS_C0011804 CHECK ("ADD_ORG_UNIT" IS NOT NULL),
	CONSTRAINT SYS_C0011805 CHECK ("REVISION_COUNT" IS NOT NULL)
);
CREATE INDEX CDBA_FC_FK_I ON THE.CLIENT_DOING_BUSINESS_AS (CLIENT_NUMBER);
CREATE INDEX CDBA_OU_FK_I ON THE.CLIENT_DOING_BUSINESS_AS (ADD_ORG_UNIT);
CREATE INDEX CDBA_OU_IS_UPDATED_BY_FK_I ON THE.CLIENT_DOING_BUSINESS_AS (UPDATE_ORG_UNIT);
ALTER TABLE THE.CLIENT_DOING_BUSINESS_AS ADD CONSTRAINT CDBA_FC_FK FOREIGN KEY (CLIENT_NUMBER) REFERENCES THE.FOREST_CLIENT(CLIENT_NUMBER);
ALTER TABLE THE.CLIENT_DOING_BUSINESS_AS ADD CONSTRAINT CDBA_OU_FK FOREIGN KEY (ADD_ORG_UNIT) REFERENCES THE.ORG_UNIT(ORG_UNIT_NO);
ALTER TABLE THE.CLIENT_DOING_BUSINESS_AS ADD CONSTRAINT CDBA_OU_IS_UPDATED_BY_FK FOREIGN KEY (UPDATE_ORG_UNIT) REFERENCES THE.ORG_UNIT(ORG_UNIT_NO);

CREATE TABLE THE.CLIENT_REORG_LINK_AUDIT (
	CLIENT_REORG_LINK_AUDIT_ID NUMBER(12,0) NOT NULL,
	CLIENT_REORG_AUDIT_CODE VARCHAR2(3) NOT NULL,
	CLIENT_REORGANIZATION_ID NUMBER(12,0) NOT NULL,
	ORIGINAL_CLIENT_NUMBER VARCHAR2(8) NOT NULL,
	RESULTING_CLIENT_NUMBER VARCHAR2(8) NOT NULL,
	ENTRY_TIMESTAMP DATE NOT NULL,
	ENTRY_USERID VARCHAR2(30) NOT NULL,
	UPDATE_TIMESTAMP DATE NOT NULL,
	UPDATE_USERID VARCHAR2(30) NOT NULL,
	CONSTRAINT CRLA_PK PRIMARY KEY (CLIENT_REORG_LINK_AUDIT_ID),
	CONSTRAINT SYS_C0022934 CHECK ("CLIENT_REORG_LINK_AUDIT_ID" IS NOT NULL),
	CONSTRAINT SYS_C0022935 CHECK ("CLIENT_REORG_AUDIT_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0022936 CHECK ("CLIENT_REORGANIZATION_ID" IS NOT NULL),
	CONSTRAINT SYS_C0022937 CHECK ("ORIGINAL_CLIENT_NUMBER" IS NOT NULL),
	CONSTRAINT SYS_C0022938 CHECK ("RESULTING_CLIENT_NUMBER" IS NOT NULL),
	CONSTRAINT SYS_C0022939 CHECK ("ENTRY_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0022940 CHECK ("ENTRY_USERID" IS NOT NULL),
	CONSTRAINT SYS_C0022941 CHECK ("UPDATE_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0022942 CHECK ("UPDATE_USERID" IS NOT NULL)
);
CREATE INDEX CRLA_AAC_FK_I ON THE.CLIENT_REORG_LINK_AUDIT (CLIENT_REORG_AUDIT_CODE);
ALTER TABLE THE.CLIENT_REORG_LINK_AUDIT ADD CONSTRAINT CRLA_CRAC_FK FOREIGN KEY (CLIENT_REORG_AUDIT_CODE) REFERENCES THE.CLIENT_REORG_AUDIT_CODE(CLIENT_REORG_AUDIT_CODE);

CREATE TABLE THE.CLIENT_REORG_DETAIL_AUDIT (
	CLIENT_REORG_DETAIL_AUDIT_ID NUMBER(12,0) NOT NULL,
	CLIENT_REORG_AUDIT_CODE VARCHAR2(3) NOT NULL,
	CLIENT_REORGANIZATION_ID NUMBER(12,0) NOT NULL,
	ORIGINAL_CLIENT_NUMBER VARCHAR2(8) NOT NULL,
	ORIGINAL_CLIENT_LOCN_CODE VARCHAR2(2) NOT NULL,
	RESULTING_CLIENT_NUMBER VARCHAR2(8) NOT NULL,
	RESULTING_CLIENT_LOCN_CODE VARCHAR2(2) NOT NULL,
	ENTRY_TIMESTAMP DATE NOT NULL,
	ENTRY_USERID VARCHAR2(30) NOT NULL,
	UPDATE_TIMESTAMP DATE NOT NULL,
	UPDATE_USERID VARCHAR2(30) NOT NULL,
	CONSTRAINT CRDA_PK PRIMARY KEY (CLIENT_REORG_DETAIL_AUDIT_ID),
	CONSTRAINT SYS_C0024617 CHECK ("CLIENT_REORG_DETAIL_AUDIT_ID" IS NOT NULL),
	CONSTRAINT SYS_C0024618 CHECK ("CLIENT_REORG_AUDIT_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0024619 CHECK ("CLIENT_REORGANIZATION_ID" IS NOT NULL),
	CONSTRAINT SYS_C0024620 CHECK ("ORIGINAL_CLIENT_NUMBER" IS NOT NULL),
	CONSTRAINT SYS_C0024621 CHECK ("ORIGINAL_CLIENT_LOCN_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0024622 CHECK ("RESULTING_CLIENT_NUMBER" IS NOT NULL),
	CONSTRAINT SYS_C0024623 CHECK ("RESULTING_CLIENT_LOCN_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0024624 CHECK ("ENTRY_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0024625 CHECK ("ENTRY_USERID" IS NOT NULL),
	CONSTRAINT SYS_C0024626 CHECK ("UPDATE_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0024627 CHECK ("UPDATE_USERID" IS NOT NULL)
);
CREATE INDEX CRDA_AAC_FK_I ON THE.CLIENT_REORG_DETAIL_AUDIT (CLIENT_REORG_AUDIT_CODE);
ALTER TABLE THE.CLIENT_REORG_DETAIL_AUDIT ADD CONSTRAINT CRDA_CRAC_FK FOREIGN KEY (CLIENT_REORG_AUDIT_CODE) REFERENCES THE.CLIENT_REORG_AUDIT_CODE(CLIENT_REORG_AUDIT_CODE);

CREATE TABLE THE.FOR_CLI_AUDIT (
	FOREST_CLIENT_AUDIT_ID NUMBER(12,0) NOT NULL,
	CLIENT_AUDIT_CODE VARCHAR2(3) NOT NULL,
	CLIENT_NUMBER VARCHAR2(8) NOT NULL,
	CLIENT_NAME VARCHAR2(60) NOT NULL,
	LEGAL_FIRST_NAME VARCHAR2(30) NULL,
	LEGAL_MIDDLE_NAME VARCHAR2(30) NULL,
	CLIENT_STATUS_CODE VARCHAR2(3) NOT NULL,
	CLIENT_TYPE_CODE VARCHAR2(1) NOT NULL,
	BIRTHDATE DATE NULL,
	CLIENT_ID_TYPE_CODE VARCHAR2(4) NULL,
	CLIENT_IDENTIFICATION VARCHAR2(40) NULL,
	REGISTRY_COMPANY_TYPE_CODE VARCHAR2(4) NULL,
	CORP_REGN_NMBR VARCHAR2(9) NULL,
	CLIENT_ACRONYM VARCHAR2(8) NULL,
	WCB_FIRM_NUMBER VARCHAR2(6) NULL,
	OCG_SUPPLIER_NMBR VARCHAR2(10) NULL,
	CLIENT_COMMENT VARCHAR2(4000) NULL,
	ADD_TIMESTAMP DATE NOT NULL,
	ADD_USERID VARCHAR2(30) NOT NULL,
	ADD_ORG_UNIT NUMBER(10,0) NOT NULL,
	UPDATE_TIMESTAMP DATE NOT NULL,
	UPDATE_USERID VARCHAR2(30) NOT NULL,
	UPDATE_ORG_UNIT NUMBER(10,0) NOT NULL,
	CONSTRAINT FCAUD_PK PRIMARY KEY (FOREST_CLIENT_AUDIT_ID),
	CONSTRAINT SYS_C0029950 CHECK ("FOREST_CLIENT_AUDIT_ID" IS NOT NULL),
	CONSTRAINT SYS_C0029951 CHECK ("CLIENT_AUDIT_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0029952 CHECK ("CLIENT_NUMBER" IS NOT NULL),
	CONSTRAINT SYS_C0029953 CHECK ("CLIENT_NAME" IS NOT NULL),
	CONSTRAINT SYS_C0029954 CHECK ("CLIENT_STATUS_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0029955 CHECK ("CLIENT_TYPE_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0029956 CHECK ("ADD_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0029957 CHECK ("ADD_USERID" IS NOT NULL),
	CONSTRAINT SYS_C0029958 CHECK ("ADD_ORG_UNIT" IS NOT NULL),
	CONSTRAINT SYS_C0029959 CHECK ("UPDATE_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0029960 CHECK ("UPDATE_USERID" IS NOT NULL),
	CONSTRAINT SYS_C0029961 CHECK ("UPDATE_ORG_UNIT" IS NOT NULL)
);
CREATE INDEX FCA_CAUDC_FK_I ON THE.FOR_CLI_AUDIT (CLIENT_AUDIT_CODE);
CREATE INDEX FCA_FC_FK_I ON THE.FOR_CLI_AUDIT (CLIENT_NUMBER);
CREATE INDEX FCA_OU_FK_I ON THE.FOR_CLI_AUDIT (ADD_ORG_UNIT);
CREATE INDEX FCA_OU_IS_UPDATED_BY_FK_I ON THE.FOR_CLI_AUDIT (UPDATE_ORG_UNIT);
ALTER TABLE THE.FOR_CLI_AUDIT ADD CONSTRAINT FCA_CAUDC_FK FOREIGN KEY (CLIENT_AUDIT_CODE) REFERENCES THE.CLIENT_AUDIT_CODE(CLIENT_AUDIT_CODE);
ALTER TABLE THE.FOR_CLI_AUDIT ADD CONSTRAINT FCA_FC_FK FOREIGN KEY (CLIENT_NUMBER) REFERENCES THE.FOREST_CLIENT(CLIENT_NUMBER);
ALTER TABLE THE.FOR_CLI_AUDIT ADD CONSTRAINT FCA_OU_FK FOREIGN KEY (ADD_ORG_UNIT) REFERENCES THE.ORG_UNIT(ORG_UNIT_NO);
ALTER TABLE THE.FOR_CLI_AUDIT ADD CONSTRAINT FCA_OU_IS_UPDATED_BY_FK FOREIGN KEY (UPDATE_ORG_UNIT) REFERENCES THE.ORG_UNIT(ORG_UNIT_NO);

CREATE TABLE THE.CLIENT_DOING_BUSINESS_AS_AUDIT (
	CLIENT_DBA_AUDIT_ID NUMBER(12,0) NOT NULL,
	CLIENT_AUDIT_CODE VARCHAR2(3) NOT NULL,
	CLIENT_DBA_ID NUMBER(12,0) NOT NULL,
	CLIENT_NUMBER VARCHAR2(8) NOT NULL,
	DOING_BUSINESS_AS_NAME VARCHAR2(120) NOT NULL,
	UPDATE_TIMESTAMP DATE NOT NULL,
	UPDATE_USERID VARCHAR2(30) NOT NULL,
	UPDATE_ORG_UNIT NUMBER(10,0) NOT NULL,
	ADD_TIMESTAMP DATE NOT NULL,
	ADD_USERID VARCHAR2(30) NOT NULL,
	ADD_ORG_UNIT NUMBER(10,0) NOT NULL,
	CONSTRAINT CDBAA_PK PRIMARY KEY (CLIENT_DBA_AUDIT_ID),
	CONSTRAINT SYS_C0011716 CHECK ("CLIENT_DBA_AUDIT_ID" IS NOT NULL),
	CONSTRAINT SYS_C0011717 CHECK ("CLIENT_AUDIT_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0011718 CHECK ("CLIENT_DBA_ID" IS NOT NULL),
	CONSTRAINT SYS_C0011719 CHECK ("CLIENT_NUMBER" IS NOT NULL),
	CONSTRAINT SYS_C0011720 CHECK ("DOING_BUSINESS_AS_NAME" IS NOT NULL),
	CONSTRAINT SYS_C0011721 CHECK ("UPDATE_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0011722 CHECK ("UPDATE_USERID" IS NOT NULL),
	CONSTRAINT SYS_C0011723 CHECK ("UPDATE_ORG_UNIT" IS NOT NULL),
	CONSTRAINT SYS_C0011724 CHECK ("ADD_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0011725 CHECK ("ADD_USERID" IS NOT NULL),
	CONSTRAINT SYS_C0011726 CHECK ("ADD_ORG_UNIT" IS NOT NULL)
);
CREATE INDEX CDBAA_CAUDC_FK_I ON THE.CLIENT_DOING_BUSINESS_AS_AUDIT (CLIENT_AUDIT_CODE);
CREATE INDEX CDBAA_OU_FK_I ON THE.CLIENT_DOING_BUSINESS_AS_AUDIT (ADD_ORG_UNIT);
CREATE INDEX CDBAA_OU_IS_UPDATED_BY_FK_I ON THE.CLIENT_DOING_BUSINESS_AS_AUDIT (UPDATE_ORG_UNIT);
ALTER TABLE THE.CLIENT_DOING_BUSINESS_AS_AUDIT ADD CONSTRAINT CDBAA_CAUDC_FK FOREIGN KEY (CLIENT_AUDIT_CODE) REFERENCES THE.CLIENT_AUDIT_CODE(CLIENT_AUDIT_CODE);
ALTER TABLE THE.CLIENT_DOING_BUSINESS_AS_AUDIT ADD CONSTRAINT CDBAA_OU_FK FOREIGN KEY (ADD_ORG_UNIT) REFERENCES THE.ORG_UNIT(ORG_UNIT_NO);
ALTER TABLE THE.CLIENT_DOING_BUSINESS_AS_AUDIT ADD CONSTRAINT CDBAA_OU_IS_UPDATED_BY_FK FOREIGN KEY (UPDATE_ORG_UNIT) REFERENCES THE.ORG_UNIT(ORG_UNIT_NO);

CREATE TABLE THE.CLIENT_ACTION_REASON_XREF (
	CLIENT_UPDATE_ACTION_CODE VARCHAR2(4) NOT NULL,
	CLIENT_UPDATE_REASON_CODE VARCHAR2(4) NOT NULL,
	CLIENT_TYPE_CODE VARCHAR2(1) NOT NULL,
	UPDATE_TIMESTAMP DATE NOT NULL,
	UPDATE_USERID VARCHAR2(30) NOT NULL,
	ADD_TIMESTAMP DATE NOT NULL,
	ADD_USERID VARCHAR2(30) NOT NULL,
	CONSTRAINT CARX_PK PRIMARY KEY (CLIENT_UPDATE_ACTION_CODE,CLIENT_UPDATE_REASON_CODE,CLIENT_TYPE_CODE),
	CONSTRAINT SYS_C0038307 CHECK ("CLIENT_UPDATE_ACTION_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0038309 CHECK ("CLIENT_UPDATE_REASON_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0038311 CHECK ("CLIENT_TYPE_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0038313 CHECK ("UPDATE_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0038315 CHECK ("UPDATE_USERID" IS NOT NULL),
	CONSTRAINT SYS_C0038317 CHECK ("ADD_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0038319 CHECK ("ADD_USERID" IS NOT NULL)
);
CREATE INDEX CARX_CTC_FK_I ON THE.CLIENT_ACTION_REASON_XREF (CLIENT_TYPE_CODE);
CREATE INDEX CARX_CUAC_FK_I ON THE.CLIENT_ACTION_REASON_XREF (CLIENT_UPDATE_ACTION_CODE);
CREATE INDEX CARX_CURC_FK_I ON THE.CLIENT_ACTION_REASON_XREF (CLIENT_UPDATE_REASON_CODE);
ALTER TABLE THE.CLIENT_ACTION_REASON_XREF ADD CONSTRAINT CARX_CTC_FK FOREIGN KEY (CLIENT_TYPE_CODE) REFERENCES THE.CLIENT_TYPE_CODE(CLIENT_TYPE_CODE);
ALTER TABLE THE.CLIENT_ACTION_REASON_XREF ADD CONSTRAINT CARX_CUAC_FK FOREIGN KEY (CLIENT_UPDATE_ACTION_CODE) REFERENCES THE.CLIENT_UPDATE_ACTION_CODE(CLIENT_UPDATE_ACTION_CODE);
ALTER TABLE THE.CLIENT_ACTION_REASON_XREF ADD CONSTRAINT CARX_CURC_FK FOREIGN KEY (CLIENT_UPDATE_REASON_CODE) REFERENCES THE.CLIENT_UPDATE_REASON_CODE(CLIENT_UPDATE_REASON_CODE);

CREATE TABLE THE.CLIENT_UPDATE_REASON (
	CLIENT_UPDATE_REASON_ID NUMBER(12,0) NOT NULL,
	CLIENT_UPDATE_ACTION_CODE VARCHAR2(4) NOT NULL,
	CLIENT_UPDATE_REASON_CODE VARCHAR2(4) NOT NULL,
	CLIENT_TYPE_CODE VARCHAR2(1) NOT NULL,
	FOREST_CLIENT_AUDIT_ID NUMBER(12,0) NOT NULL,
	UPDATE_TIMESTAMP DATE NOT NULL,
	UPDATE_USERID VARCHAR2(30) NOT NULL,
	ADD_TIMESTAMP DATE NOT NULL,
	ADD_USERID VARCHAR2(30) NOT NULL,
	CONSTRAINT CU_PK PRIMARY KEY (CLIENT_UPDATE_REASON_ID),
	CONSTRAINT SYS_C0038356 CHECK ("CLIENT_UPDATE_REASON_ID" IS NOT NULL),
	CONSTRAINT SYS_C0038357 CHECK ("CLIENT_UPDATE_ACTION_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0038358 CHECK ("CLIENT_UPDATE_REASON_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0038359 CHECK ("CLIENT_TYPE_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0038360 CHECK ("FOREST_CLIENT_AUDIT_ID" IS NOT NULL),
	CONSTRAINT SYS_C0038361 CHECK ("UPDATE_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0038362 CHECK ("UPDATE_USERID" IS NOT NULL),
	CONSTRAINT SYS_C0038363 CHECK ("ADD_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0038364 CHECK ("ADD_USERID" IS NOT NULL)
);
CREATE INDEX CU_CARX_FK_I ON THE.CLIENT_UPDATE_REASON (CLIENT_UPDATE_ACTION_CODE,CLIENT_UPDATE_REASON_CODE,CLIENT_TYPE_CODE);
CREATE INDEX CU_FCA_FK_I ON THE.CLIENT_UPDATE_REASON (FOREST_CLIENT_AUDIT_ID);
ALTER TABLE THE.CLIENT_UPDATE_REASON ADD CONSTRAINT CU_CARX_FK FOREIGN KEY (CLIENT_UPDATE_ACTION_CODE,CLIENT_UPDATE_REASON_CODE,CLIENT_TYPE_CODE) REFERENCES THE.CLIENT_ACTION_REASON_XREF(CLIENT_UPDATE_ACTION_CODE,CLIENT_UPDATE_REASON_CODE,CLIENT_TYPE_CODE);
ALTER TABLE THE.CLIENT_UPDATE_REASON ADD CONSTRAINT CU_FCA_FK FOREIGN KEY (FOREST_CLIENT_AUDIT_ID) REFERENCES THE.FOR_CLI_AUDIT(FOREST_CLIENT_AUDIT_ID);

CREATE TABLE THE.CLI_CON_AUDIT (
	CLIENT_CONTACT_AUDIT_ID NUMBER(12,0) NOT NULL,
	CLIENT_AUDIT_CODE VARCHAR2(3) NOT NULL,
	CLIENT_CONTACT_ID NUMBER(12,0) NULL,
	CLIENT_NUMBER VARCHAR2(8) NOT NULL,
	CLIENT_LOCN_CODE VARCHAR2(2) NOT NULL,
	BUS_CONTACT_CODE VARCHAR2(3) NOT NULL,
	CONTACT_NAME VARCHAR2(120) NOT NULL,
	BUSINESS_PHONE VARCHAR2(10) NULL,
	CELL_PHONE VARCHAR2(10) NULL,
	FAX_NUMBER VARCHAR2(10) NULL,
	EMAIL_ADDRESS VARCHAR2(128) NULL,
	UPDATE_TIMESTAMP DATE NOT NULL,
	UPDATE_USERID VARCHAR2(30) NOT NULL,
	UPDATE_ORG_UNIT_NO NUMBER(10,0) NOT NULL,
	ADD_TIMESTAMP DATE NOT NULL,
	ADD_USERID VARCHAR2(30) NOT NULL,
	ADD_ORG_UNIT NUMBER(10,0) NOT NULL,
	CONSTRAINT CCA_PK PRIMARY KEY (CLIENT_CONTACT_AUDIT_ID),
	CONSTRAINT SYS_C0029803 CHECK ("CLIENT_CONTACT_AUDIT_ID" IS NOT NULL),
	CONSTRAINT SYS_C0029804 CHECK ("CLIENT_AUDIT_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0029805 CHECK ("CLIENT_NUMBER" IS NOT NULL),
	CONSTRAINT SYS_C0029806 CHECK ("CLIENT_LOCN_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0029807 CHECK ("BUS_CONTACT_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0029808 CHECK ("CONTACT_NAME" IS NOT NULL),
	CONSTRAINT SYS_C0029809 CHECK ("UPDATE_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0029810 CHECK ("UPDATE_USERID" IS NOT NULL),
	CONSTRAINT SYS_C0029811 CHECK ("UPDATE_ORG_UNIT_NO" IS NOT NULL),
	CONSTRAINT SYS_C0029812 CHECK ("ADD_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0029813 CHECK ("ADD_USERID" IS NOT NULL),
	CONSTRAINT SYS_C0029814 CHECK ("ADD_ORG_UNIT" IS NOT NULL)
);
CREATE INDEX CCA_OU_FK_I ON THE.CLI_CON_AUDIT (ADD_ORG_UNIT);
CREATE INDEX CCA_OU_IS_UPDATED_BY_FK_I ON THE.CLI_CON_AUDIT (UPDATE_ORG_UNIT_NO);
CREATE UNIQUE INDEX "I1$_CLI_CON_AUDIT" ON THE.CLI_CON_AUDIT (CLIENT_NUMBER,CLIENT_LOCN_CODE,BUS_CONTACT_CODE,UPDATE_TIMESTAMP);
ALTER TABLE THE.CLI_CON_AUDIT ADD CONSTRAINT CCA_CAUDC_FK FOREIGN KEY (CLIENT_AUDIT_CODE) REFERENCES THE.CLIENT_AUDIT_CODE(CLIENT_AUDIT_CODE);
ALTER TABLE THE.CLI_CON_AUDIT ADD CONSTRAINT CCA_OU_FK FOREIGN KEY (ADD_ORG_UNIT) REFERENCES THE.ORG_UNIT(ORG_UNIT_NO);
ALTER TABLE THE.CLI_CON_AUDIT ADD CONSTRAINT CCA_OU_IS_UPDATED_BY_FK FOREIGN KEY (UPDATE_ORG_UNIT_NO) REFERENCES THE.ORG_UNIT(ORG_UNIT_NO);

CREATE TABLE THE.CLI_LOCN_AUDIT (
	CLIENT_LOCATION_AUDIT_ID NUMBER(12,0) NOT NULL,
	CLIENT_AUDIT_CODE VARCHAR2(3) NOT NULL,
	CLIENT_NUMBER VARCHAR2(8) NOT NULL,
	CLIENT_LOCN_CODE VARCHAR2(2) NOT NULL,
	CLIENT_LOCN_NAME VARCHAR2(40) NULL,
	HDBS_COMPANY_CODE VARCHAR2(5) NULL,
	ADDRESS_1 VARCHAR2(40) NOT NULL,
	ADDRESS_2 VARCHAR2(40) NULL,
	ADDRESS_3 VARCHAR2(40) NULL,
	CITY VARCHAR2(30) NOT NULL,
	PROVINCE VARCHAR2(50) NULL,
	POSTAL_CODE VARCHAR2(10) NULL,
	COUNTRY VARCHAR2(50) NOT NULL,
	BUSINESS_PHONE VARCHAR2(10) NULL,
	HOME_PHONE VARCHAR2(10) NULL,
	CELL_PHONE VARCHAR2(10) NULL,
	FAX_NUMBER VARCHAR2(10) NULL,
	EMAIL_ADDRESS VARCHAR2(128) NULL,
	LOCN_EXPIRED_IND VARCHAR2(1) NOT NULL,
	RETURNED_MAIL_DATE DATE NULL,
	TRUST_LOCATION_IND VARCHAR2(1) NULL,
	CLI_LOCN_COMMENT VARCHAR2(4000) NULL,
	CLIENT_UPDATE_ACTION_CODE VARCHAR2(4) NULL,
	CLIENT_UPDATE_REASON_CODE VARCHAR2(4) NULL,
	CLIENT_TYPE_CODE VARCHAR2(1) NULL,
	UPDATE_TIMESTAMP DATE NOT NULL,
	UPDATE_USERID VARCHAR2(30) NOT NULL,
	UPDATE_ORG_UNIT NUMBER(10,0) NOT NULL,
	ADD_TIMESTAMP DATE NOT NULL,
	ADD_USERID VARCHAR2(30) NOT NULL,
	ADD_ORG_UNIT NUMBER(10,0) NOT NULL,
	CONSTRAINT CLA_PK PRIMARY KEY (CLIENT_LOCATION_AUDIT_ID),
	CONSTRAINT SYS_C0029886 CHECK ("CLIENT_LOCATION_AUDIT_ID" IS NOT NULL),
	CONSTRAINT SYS_C0029887 CHECK ("CLIENT_AUDIT_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0029888 CHECK ("CLIENT_NUMBER" IS NOT NULL),
	CONSTRAINT SYS_C0029889 CHECK ("CLIENT_LOCN_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0029890 CHECK ("ADDRESS_1" IS NOT NULL),
	CONSTRAINT SYS_C0029891 CHECK ("CITY" IS NOT NULL),
	CONSTRAINT SYS_C0029892 CHECK ("COUNTRY" IS NOT NULL),
	CONSTRAINT SYS_C0029893 CHECK ("LOCN_EXPIRED_IND" IS NOT NULL),
	CONSTRAINT SYS_C0029894 CHECK ("UPDATE_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0029895 CHECK ("UPDATE_USERID" IS NOT NULL),
	CONSTRAINT SYS_C0029896 CHECK ("UPDATE_ORG_UNIT" IS NOT NULL),
	CONSTRAINT SYS_C0029897 CHECK ("ADD_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0029898 CHECK ("ADD_USERID" IS NOT NULL),
	CONSTRAINT SYS_C0029899 CHECK ("ADD_ORG_UNIT" IS NOT NULL)
);
CREATE INDEX CLA_CARX_FK_I ON THE.CLI_LOCN_AUDIT (CLIENT_UPDATE_ACTION_CODE,CLIENT_UPDATE_REASON_CODE,CLIENT_TYPE_CODE);
CREATE INDEX CLA_CAUDC_FK_I ON THE.CLI_LOCN_AUDIT (CLIENT_AUDIT_CODE);
CREATE INDEX CLA_CL_FK_I ON THE.CLI_LOCN_AUDIT (CLIENT_NUMBER,CLIENT_LOCN_CODE);
CREATE INDEX CLA_OU_FK_I ON THE.CLI_LOCN_AUDIT (UPDATE_ORG_UNIT);
CREATE INDEX CLA_OU_IS_CREATED_BY_FK_I ON THE.CLI_LOCN_AUDIT (ADD_ORG_UNIT);
ALTER TABLE THE.CLI_LOCN_AUDIT ADD CONSTRAINT CLA_CARX_FK FOREIGN KEY (CLIENT_UPDATE_ACTION_CODE,CLIENT_UPDATE_REASON_CODE,CLIENT_TYPE_CODE) REFERENCES THE.CLIENT_ACTION_REASON_XREF(CLIENT_UPDATE_ACTION_CODE,CLIENT_UPDATE_REASON_CODE,CLIENT_TYPE_CODE);
ALTER TABLE THE.CLI_LOCN_AUDIT ADD CONSTRAINT CLA_CAUDC_FK FOREIGN KEY (CLIENT_AUDIT_CODE) REFERENCES THE.CLIENT_AUDIT_CODE(CLIENT_AUDIT_CODE);
ALTER TABLE THE.CLI_LOCN_AUDIT ADD CONSTRAINT CLA_CL_FK FOREIGN KEY (CLIENT_NUMBER,CLIENT_LOCN_CODE) REFERENCES THE.CLIENT_LOCATION(CLIENT_NUMBER,CLIENT_LOCN_CODE);
ALTER TABLE THE.CLI_LOCN_AUDIT ADD CONSTRAINT CLA_OU_FK FOREIGN KEY (UPDATE_ORG_UNIT) REFERENCES THE.ORG_UNIT(ORG_UNIT_NO);
ALTER TABLE THE.CLI_LOCN_AUDIT ADD CONSTRAINT CLA_OU_IS_CREATED_BY_FK FOREIGN KEY (ADD_ORG_UNIT) REFERENCES THE.ORG_UNIT(ORG_UNIT_NO);

CREATE TABLE THE.RELATED_CLIENT (
	CLIENT_NUMBER VARCHAR2(8) NOT NULL,
	CLIENT_LOCN_CODE VARCHAR2(2) NOT NULL,
	RELATED_CLNT_NMBR VARCHAR2(8) NOT NULL,
	RELATED_CLNT_LOCN VARCHAR2(2) NOT NULL,
	RELATIONSHIP_CODE VARCHAR2(2) NOT NULL,
	SIGNING_AUTH_IND VARCHAR2(1) NULL,
	PERCENT_OWNERSHIP NUMBER(4,1) NULL,
	UPDATE_TIMESTAMP DATE NOT NULL,
	UPDATE_USERID VARCHAR2(30) NOT NULL,
	UPDATE_ORG_UNIT NUMBER(10,0) NOT NULL,
	ADD_TIMESTAMP DATE NOT NULL,
	ADD_USERID VARCHAR2(30) NOT NULL,
	ADD_ORG_UNIT NUMBER(10,0) NOT NULL,
	REVISION_COUNT NUMBER(5,0) NOT NULL,
	CONSTRAINT RCLI_PK PRIMARY KEY (CLIENT_NUMBER,CLIENT_LOCN_CODE,RELATED_CLNT_NMBR,RELATED_CLNT_LOCN),
	CONSTRAINT SYS_C0011626 CHECK ("CLIENT_NUMBER" IS NOT NULL),
	CONSTRAINT SYS_C0011627 CHECK ("CLIENT_LOCN_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0011628 CHECK ("RELATED_CLNT_NMBR" IS NOT NULL),
	CONSTRAINT SYS_C0011629 CHECK ("RELATED_CLNT_LOCN" IS NOT NULL),
	CONSTRAINT SYS_C0011630 CHECK ("RELATIONSHIP_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0011631 CHECK ("UPDATE_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0011632 CHECK ("UPDATE_USERID" IS NOT NULL),
	CONSTRAINT SYS_C0011633 CHECK ("UPDATE_ORG_UNIT" IS NOT NULL),
	CONSTRAINT SYS_C0011634 CHECK ("ADD_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0011635 CHECK ("ADD_USERID" IS NOT NULL),
	CONSTRAINT SYS_C0011636 CHECK ("ADD_ORG_UNIT" IS NOT NULL),
	CONSTRAINT SYS_C0011637 CHECK ("REVISION_COUNT" IS NOT NULL)
);
CREATE INDEX RC_CL_FK_I ON THE.RELATED_CLIENT (CLIENT_NUMBER,CLIENT_LOCN_CODE);
CREATE INDEX RC_CL_HAS_RELATIONSHIP_FOR_F_I ON THE.RELATED_CLIENT (RELATED_CLNT_NMBR,RELATED_CLNT_LOCN);
CREATE INDEX RC_OU_FK_I ON THE.RELATED_CLIENT (ADD_ORG_UNIT);
CREATE INDEX RC_OU_IS_UPDATED_BY_FK_I ON THE.RELATED_CLIENT (UPDATE_ORG_UNIT);
CREATE INDEX RC_RELCD_FK_I ON THE.RELATED_CLIENT (RELATIONSHIP_CODE);
ALTER TABLE THE.RELATED_CLIENT ADD CONSTRAINT RC_CL_FK FOREIGN KEY (CLIENT_NUMBER,CLIENT_LOCN_CODE) REFERENCES THE.CLIENT_LOCATION(CLIENT_NUMBER,CLIENT_LOCN_CODE);
ALTER TABLE THE.RELATED_CLIENT ADD CONSTRAINT RC_CL_HAS_RELATIONSHIP_FOR_FK FOREIGN KEY (RELATED_CLNT_NMBR,RELATED_CLNT_LOCN) REFERENCES THE.CLIENT_LOCATION(CLIENT_NUMBER,CLIENT_LOCN_CODE);
ALTER TABLE THE.RELATED_CLIENT ADD CONSTRAINT RC_OU_FK FOREIGN KEY (ADD_ORG_UNIT) REFERENCES THE.ORG_UNIT(ORG_UNIT_NO);
ALTER TABLE THE.RELATED_CLIENT ADD CONSTRAINT RC_OU_IS_UPDATED_BY_FK FOREIGN KEY (UPDATE_ORG_UNIT) REFERENCES THE.ORG_UNIT(ORG_UNIT_NO);
ALTER TABLE THE.RELATED_CLIENT ADD CONSTRAINT RC_RELCD_FK FOREIGN KEY (RELATIONSHIP_CODE) REFERENCES THE.CLIENT_RELATIONSHIP_CODE(CLIENT_RELATIONSHIP_CODE);

CREATE TABLE THE.REL_CLI_AUDIT (
	RELATED_CLIENT_AUDIT_ID NUMBER(12,0) NOT NULL,
	CLIENT_AUDIT_CODE VARCHAR2(3) NOT NULL,
	CLIENT_NUMBER VARCHAR2(8) NOT NULL,
	CLIENT_LOCN_CODE VARCHAR2(2) NOT NULL,
	RELATED_CLNT_NMBR VARCHAR2(8) NOT NULL,
	RELATED_CLNT_LOCN VARCHAR2(2) NULL,
	RELATIONSHIP_CODE VARCHAR2(2) NULL,
	SIGNING_AUTH_IND VARCHAR2(1) NULL,
	PERCENT_OWNERSHIP NUMBER(4,1) NULL,
	UPDATE_TIMESTAMP DATE NOT NULL,
	UPDATE_USERID VARCHAR2(30) NOT NULL,
	UPDATE_ORG_UNIT NUMBER(10,0) NOT NULL,
	ADD_TIMESTAMP DATE NOT NULL,
	ADD_USERID VARCHAR2(30) NOT NULL,
	ADD_ORG_UNIT NUMBER(10,0) NOT NULL,
	CONSTRAINT RCA_PK PRIMARY KEY (RELATED_CLIENT_AUDIT_ID),
	CONSTRAINT SYS_C0011541 CHECK ("RELATED_CLIENT_AUDIT_ID" IS NOT NULL),
	CONSTRAINT SYS_C0011542 CHECK ("CLIENT_AUDIT_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0011543 CHECK ("CLIENT_NUMBER" IS NOT NULL),
	CONSTRAINT SYS_C0011544 CHECK ("CLIENT_LOCN_CODE" IS NOT NULL),
	CONSTRAINT SYS_C0011545 CHECK ("RELATED_CLNT_NMBR" IS NOT NULL),
	CONSTRAINT SYS_C0011546 CHECK ("UPDATE_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0011547 CHECK ("UPDATE_USERID" IS NOT NULL),
	CONSTRAINT SYS_C0011548 CHECK ("UPDATE_ORG_UNIT" IS NOT NULL),
	CONSTRAINT SYS_C0011549 CHECK ("ADD_TIMESTAMP" IS NOT NULL),
	CONSTRAINT SYS_C0011550 CHECK ("ADD_USERID" IS NOT NULL),
	CONSTRAINT SYS_C0011551 CHECK ("ADD_ORG_UNIT" IS NOT NULL)
);
CREATE UNIQUE INDEX "I1$_REL_CLI_AUDIT" ON THE.REL_CLI_AUDIT (CLIENT_NUMBER,CLIENT_LOCN_CODE,RELATED_CLNT_NMBR,UPDATE_TIMESTAMP);
CREATE INDEX RCA_CAUDC_FK_I ON THE.REL_CLI_AUDIT (CLIENT_AUDIT_CODE);
CREATE INDEX RCA_CLI_LOCN_I ON THE.REL_CLI_AUDIT (CLIENT_NUMBER,CLIENT_LOCN_CODE);
CREATE INDEX RCA_OU_FK_I ON THE.REL_CLI_AUDIT (ADD_ORG_UNIT);
CREATE INDEX RCA_OU_IS_UPDATED_BY_FK_I ON THE.REL_CLI_AUDIT (UPDATE_ORG_UNIT);
CREATE INDEX RCA_REL_CLI_LOCN_I ON THE.REL_CLI_AUDIT (RELATED_CLNT_NMBR,RELATED_CLNT_LOCN);
ALTER TABLE THE.REL_CLI_AUDIT ADD CONSTRAINT RCA_CAUDC_FK FOREIGN KEY (CLIENT_AUDIT_CODE) REFERENCES THE.CLIENT_AUDIT_CODE(CLIENT_AUDIT_CODE);
ALTER TABLE THE.REL_CLI_AUDIT ADD CONSTRAINT RCA_OU_FK FOREIGN KEY (ADD_ORG_UNIT) REFERENCES THE.ORG_UNIT(ORG_UNIT_NO);
ALTER TABLE THE.REL_CLI_AUDIT ADD CONSTRAINT RCA_OU_IS_UPDATED_BY_FK FOREIGN KEY (UPDATE_ORG_UNIT) REFERENCES THE.ORG_UNIT(ORG_UNIT_NO);