CREATE OR REPLACE TYPE THE."SIL_ERROR_PARAMS" AS VARRAY(50) OF VARCHAR2(500);

CREATE OR REPLACE TYPE THE."SIL_ERROR_MESSAGE" AS OBJECT 
(
  DATABASE_FIELD                 VARCHAR2(50),
  MESSAGE                        VARCHAR2(250),
  PARAMS                         SIL_ERROR_PARAMS,
  WARNING_FLAG                   VARCHAR2(1)
);

CREATE OR REPLACE TYPE THE."SIL_ERROR_MESSAGES" AS VARRAY(100) OF SIL_ERROR_MESSAGE;

CREATE OR REPLACE PACKAGE THE.client_constants AS

  TYPE REF_CUR_T IS REF CURSOR;

  C_AUDIT_INSERT                       CONSTANT VARCHAR2(3) := 'INS';
  C_AUDIT_UPDATE                       CONSTANT VARCHAR2(3) := 'UPD';
  C_AUDIT_DELETE                       CONSTANT VARCHAR2(3) := 'DEL';

END client_constants;

CREATE OR REPLACE TYPE THE."CLIENT_GENERIC_STRING_VARRAY" AS VARRAY(4000) OF VARCHAR2(255);
CREATE OR REPLACE TYPE THE."CLIENT_REORG_RESULTS" AS VARRAY(1000) OF client_reorg_result;

CREATE OR REPLACE TYPE THE."CLIENT_REORG_RESULT" AS OBJECT
(
  TABLE_NAME                     VARCHAR2(30)
, ROWS_UPDATED                   NUMBER(20)
);

CREATE SEQUENCE client_dba_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;


CREATE SEQUENCE client_contact_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;