CREATE SEQUENCE client_dba_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE client_contact_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE forest_client_audit_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE client_update_reason_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;