-- Create a new entry in the CLIENT_ID_TYPE_CODE table for the BCeID in an idempotent way
MERGE INTO THE.CLIENT_ID_TYPE_CODE tgt
USING (
    SELECT 'BCEI' AS CLIENT_ID_TYPE_CODE,
           'BCeID' AS DESCRIPTION,
           TIMESTAMP '2023-11-29 00:00:00.0' AS EFFECTIVE_DATE,
           TIMESTAMP '9999-12-31 00:00:00.0' AS EXPIRY_DATE,
           TIMESTAMP '2023-11-29 13:00:40.0' AS UPDATE_TIMESTAMP
    FROM DUAL
) src
ON (tgt.CLIENT_ID_TYPE_CODE = src.CLIENT_ID_TYPE_CODE)
WHEN MATCHED THEN
    UPDATE SET
        tgt.DESCRIPTION = src.DESCRIPTION,
        tgt.EFFECTIVE_DATE = src.EFFECTIVE_DATE,
        tgt.EXPIRY_DATE = src.EXPIRY_DATE,
        tgt.UPDATE_TIMESTAMP = src.UPDATE_TIMESTAMP
WHEN NOT MATCHED THEN
    INSERT (CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
    VALUES (src.CLIENT_ID_TYPE_CODE, src.DESCRIPTION, src.EFFECTIVE_DATE, src.EXPIRY_DATE, src.UPDATE_TIMESTAMP);

-- Create a new entry in the CLIENT_ID_TYPE_CODE table for the BCSC in an idempotent way
MERGE INTO THE.CLIENT_ID_TYPE_CODE tgt
USING (
    SELECT  'BCSC' AS CLIENT_ID_TYPE_CODE,
            'BC Services Card' AS DESCRIPTION,
            TIMESTAMP'2023-11-29 00:00:00.0' AS EFFECTIVE_DATE,
            TIMESTAMP'9999-12-31 00:00:00.0' AS EXPIRY_DATE,
            TIMESTAMP'2023-11-29 13:00:40.0' AS UPDATE_TIMESTAMP
    FROM dual
) src
ON (tgt.CLIENT_ID_TYPE_CODE = src.CLIENT_ID_TYPE_CODE)
WHEN MATCHED THEN
    UPDATE SET
        tgt.DESCRIPTION = src.DESCRIPTION,
        tgt.EFFECTIVE_DATE = src.EFFECTIVE_DATE,
        tgt.EXPIRY_DATE = src.EXPIRY_DATE,
        tgt.UPDATE_TIMESTAMP = src.UPDATE_TIMESTAMP
WHEN NOT MATCHED THEN
    INSERT (CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
    VALUES (src.CLIENT_ID_TYPE_CODE, src.DESCRIPTION, src.EFFECTIVE_DATE, src.EXPIRY_DATE, src.UPDATE_TIMESTAMP);

-- Create a new entry in the CLIENT_ID_TYPE_CODE table for the BC Registry in an idempotent way
MERGE INTO THE.CLIENT_ID_TYPE_CODE tgt
USING (
    SELECT  'BCRE' AS CLIENT_ID_TYPE_CODE,
            'BC Registry' AS DESCRIPTION,
            TIMESTAMP'2023-11-29 00:00:00.0' AS EFFECTIVE_DATE,
            TIMESTAMP'9999-12-31 00:00:00.0' AS EXPIRY_DATE,
            TIMESTAMP'2023-11-29 13:00:40.0' AS UPDATE_TIMESTAMP
    FROM dual
) src
ON (tgt.CLIENT_ID_TYPE_CODE = src.CLIENT_ID_TYPE_CODE)
WHEN MATCHED THEN
    UPDATE SET
        tgt.DESCRIPTION = src.DESCRIPTION,
        tgt.EFFECTIVE_DATE = src.EFFECTIVE_DATE,
        tgt.EXPIRY_DATE = src.EXPIRY_DATE,
        tgt.UPDATE_TIMESTAMP = src.UPDATE_TIMESTAMP
WHEN NOT MATCHED THEN
    INSERT (CLIENT_ID_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
    VALUES (src.CLIENT_ID_TYPE_CODE, src.DESCRIPTION, src.EFFECTIVE_DATE, src.EXPIRY_DATE, src.UPDATE_TIMESTAMP);
