UPDATE THE.CLIENT_CONTACT c
SET CONTACT_NAME = (
    SELECT CASE 
             WHEN rn = 1 THEN CONTACT_NAME
             ELSE CONTACT_NAME || ' ' || (rn-1)
           END
    FROM (
        SELECT CLIENT_CONTACT_ID,
               ROW_NUMBER() OVER (
                   PARTITION BY CLIENT_NUMBER, CONTACT_NAME
                   ORDER BY CLIENT_CONTACT_ID
               ) rn
        FROM THE.CLIENT_CONTACT
        ORDER BY CLIENT_CONTACT_ID
    ) sub
    WHERE sub.CLIENT_CONTACT_ID = c.CLIENT_CONTACT_ID
),
REVISION_COUNT = REVISION_COUNT + 1,
UPDATE_TIMESTAMP = SYSTIMESTAMP + (ROWNUM/1000000) -- tiny offset
WHERE EXISTS (
    SELECT 1
    FROM THE.CLIENT_CONTACT cc
    JOIN THE.FOREST_CLIENT fc 
      ON fc.CLIENT_NUMBER = cc.CLIENT_NUMBER
    WHERE cc.CLIENT_NUMBER = c.CLIENT_NUMBER
      AND cc.CONTACT_NAME  = c.CONTACT_NAME
      AND fc.CLIENT_STATUS_CODE = 'ACT'
    GROUP BY cc.CLIENT_NUMBER, cc.CONTACT_NAME
    HAVING COUNT(DISTINCT NVL(BUS_CONTACT_CODE, '~')) > 1
        OR COUNT(DISTINCT NVL(BUSINESS_PHONE, '~'))   > 1
        OR COUNT(DISTINCT NVL(CELL_PHONE, '~'))       > 1
        OR COUNT(DISTINCT NVL(FAX_NUMBER, '~'))       > 1
