-- Test data to support ScaleSiteContact "contact in use" checks.
-- Client 00000160 has three contacts:
--   * "IN USE CONTACT" is referenced by THE.SCALE_SITE_CONTACT and therefore cannot be deleted.
--   * "FREE CONTACT" has no reference in THE.SCALE_SITE_CONTACT (used for the in-use check).
--   * "DELETABLE CONTACT" has no reference in THE.SCALE_SITE_CONTACT (used for the delete flow).

INSERT INTO THE.FOREST_CLIENT (CLIENT_NUMBER, CLIENT_TYPE_CODE, CLIENT_NAME, LEGAL_FIRST_NAME, LEGAL_MIDDLE_NAME, CLIENT_STATUS_CODE, BIRTHDATE, REGISTRY_COMPANY_TYPE_CODE, CORP_REGN_NMBR, CLIENT_ACRONYM, CLIENT_ID_TYPE_CODE, CLIENT_IDENTIFICATION, WCB_FIRM_NUMBER, OCG_SUPPLIER_NMBR, CLIENT_COMMENT, ADD_TIMESTAMP, ADD_USERID, ADD_ORG_UNIT, UPDATE_TIMESTAMP, UPDATE_USERID, UPDATE_ORG_UNIT, REVISION_COUNT)
VALUES ('00000160', 'C', 'SCALE SITE CONTACT TEST CO', null, null, 'ACT', null, 'BC', '9999999', null, null, null, null, null, null, CURRENT_TIMESTAMP(6), 'IDIR\\TESTUSER', 70, CURRENT_TIMESTAMP(6), 'IDIR\\TESTUSER', 70, 1);

INSERT INTO THE.CLIENT_LOCATION (CLIENT_NUMBER, CLIENT_LOCN_CODE, CLIENT_LOCN_NAME, HDBS_COMPANY_CODE, ADDRESS_1, ADDRESS_2, ADDRESS_3, CITY, PROVINCE, POSTAL_CODE, COUNTRY, BUSINESS_PHONE, HOME_PHONE, CELL_PHONE, FAX_NUMBER, EMAIL_ADDRESS, LOCN_EXPIRED_IND, RETURNED_MAIL_DATE, TRUST_LOCATION_IND, UPDATE_TIMESTAMP, UPDATE_USERID, UPDATE_ORG_UNIT, ADD_TIMESTAMP, ADD_USERID, ADD_ORG_UNIT, REVISION_COUNT)
VALUES ('00000160', '00', 'MAIN OFFICE', null, '123 TEST STREET', null, null, 'VICTORIA', 'BC', 'V8T5J9', 'CANADA', '2505551234', null, null, null, 'test@scalesite.ca', 'N', null, 'N', CURRENT_TIMESTAMP(6), 'IDIR\\TESTUSER', 70, CURRENT_TIMESTAMP(6), 'IDIR\\TESTUSER', 70, 1);

INSERT INTO THE.CLIENT_CONTACT (CLIENT_CONTACT_ID, CLIENT_NUMBER, CLIENT_LOCN_CODE, BUS_CONTACT_CODE, CONTACT_NAME, BUSINESS_PHONE, CELL_PHONE, FAX_NUMBER, EMAIL_ADDRESS, UPDATE_TIMESTAMP, UPDATE_USERID, UPDATE_ORG_UNIT, ADD_TIMESTAMP, ADD_USERID, ADD_ORG_UNIT, REVISION_COUNT)
VALUES (THE.client_contact_seq.NEXTVAL, '00000160', '00', 'BL', 'IN USE CONTACT', '2505551234', null, null, 'inuse@scalesite.ca', CURRENT_TIMESTAMP(6), 'IDIR\\TESTUSER', 70, CURRENT_TIMESTAMP(6), 'IDIR\\TESTUSER', 70, 1);

INSERT INTO THE.CLIENT_CONTACT (CLIENT_CONTACT_ID, CLIENT_NUMBER, CLIENT_LOCN_CODE, BUS_CONTACT_CODE, CONTACT_NAME, BUSINESS_PHONE, CELL_PHONE, FAX_NUMBER, EMAIL_ADDRESS, UPDATE_TIMESTAMP, UPDATE_USERID, UPDATE_ORG_UNIT, ADD_TIMESTAMP, ADD_USERID, ADD_ORG_UNIT, REVISION_COUNT)
VALUES (THE.client_contact_seq.NEXTVAL, '00000160', '00', 'AP', 'FREE CONTACT', '2505555678', null, null, 'free@scalesite.ca', CURRENT_TIMESTAMP(6), 'IDIR\\TESTUSER', 70, CURRENT_TIMESTAMP(6), 'IDIR\\TESTUSER', 70, 1);

INSERT INTO THE.CLIENT_CONTACT (CLIENT_CONTACT_ID, CLIENT_NUMBER, CLIENT_LOCN_CODE, BUS_CONTACT_CODE, CONTACT_NAME, BUSINESS_PHONE, CELL_PHONE, FAX_NUMBER, EMAIL_ADDRESS, UPDATE_TIMESTAMP, UPDATE_USERID, UPDATE_ORG_UNIT, ADD_TIMESTAMP, ADD_USERID, ADD_ORG_UNIT, REVISION_COUNT)
VALUES (THE.client_contact_seq.NEXTVAL, '00000160', '00', 'LB', 'DELETABLE CONTACT', '2505559999', null, null, 'deletable@scalesite.ca', CURRENT_TIMESTAMP(6), 'IDIR\\TESTUSER', 70, CURRENT_TIMESTAMP(6), 'IDIR\\TESTUSER', 70, 1);

INSERT INTO THE.SCALE_SITE_CONTACT (SCALE_SITE_ID_NMBR, CLIENT_CONTACT_ID, CONTACT_ROLE_DESCRIPTION, PRIMARY_CONTACT_IND, SITE_INFORMATION_ACCESS_IND, EFFECTIVE_DATE, ENTRY_TIMESTAMP, ENTRY_USERID, UPDATE_TIMESTAMP, UPDATE_USERID, REVISION_COUNT)
SELECT '1111', CC.CLIENT_CONTACT_ID, 'Site Contact', 'Y', 'N', SYSDATE, CURRENT_TIMESTAMP(6), 'IDIR\\TESTUSER', CURRENT_TIMESTAMP(6), 'IDIR\\TESTUSER', 1
FROM THE.CLIENT_CONTACT CC
WHERE CC.CLIENT_NUMBER = '00000160'
  AND CC.CONTACT_NAME = 'IN USE CONTACT';
