-- Create a new entry in the REGISTRY_COMPANY_TYPE_CODE table for the BCeID FM type in an idempotent way
MERGE INTO THE.REGISTRY_COMPANY_TYPE_CODE tgt
USING (
    SELECT 'LP' AS REGISTRY_COMPANY_TYPE_CODE,
           'Limited Partnership' AS DESCRIPTION,
           TIMESTAMP '2024-10-07 00:00:00.0' AS EFFECTIVE_DATE,
           TIMESTAMP '9999-12-31 00:00:00.0' AS EXPIRY_DATE,
           TIMESTAMP '2024-10-07 00:00:00.0' AS UPDATE_TIMESTAMP
    FROM DUAL
) src
ON (tgt.REGISTRY_COMPANY_TYPE_CODE = src.REGISTRY_COMPANY_TYPE_CODE)
WHEN MATCHED THEN
    UPDATE SET
        tgt.DESCRIPTION = src.DESCRIPTION,
        tgt.EFFECTIVE_DATE = src.EFFECTIVE_DATE,
        tgt.EXPIRY_DATE = src.EXPIRY_DATE,
        tgt.UPDATE_TIMESTAMP = src.UPDATE_TIMESTAMP
WHEN NOT MATCHED THEN
    INSERT (REGISTRY_COMPANY_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
    VALUES (src.REGISTRY_COMPANY_TYPE_CODE, src.DESCRIPTION, src.EFFECTIVE_DATE, src.EXPIRY_DATE, src.UPDATE_TIMESTAMP);

-- Create a new entry in the CLIENT_TYPE_COMPANY_XREF table for the BCeID FM code linking with I in an idempotent way
MERGE INTO THE.CLIENT_TYPE_COMPANY_XREF tgt
USING (
    SELECT 'L' AS CLIENT_TYPE_CODE,
           'LP' AS REGISTRY_COMPANY_TYPE_CODE,
           'CLIADMIN' AS ADD_USERID,
           TIMESTAMP '2024-10-07 00:00:00.0' AS ADD_TIMESTAMP,
           'CLIADMIN' AS UPDATE_USERID,
           TIMESTAMP '2024-10-07 00:00:00.0' AS UPDATE_TIMESTAMP
    FROM DUAL
) src
ON (tgt.CLIENT_TYPE_CODE = src.CLIENT_TYPE_CODE AND tgt.REGISTRY_COMPANY_TYPE_CODE = src.REGISTRY_COMPANY_TYPE_CODE)
WHEN MATCHED THEN
    UPDATE SET
        tgt.ADD_USERID = src.ADD_USERID,
        tgt.ADD_TIMESTAMP = src.ADD_TIMESTAMP,
        tgt.UPDATE_USERID = src.UPDATE_USERID,
        tgt.UPDATE_TIMESTAMP = src.UPDATE_TIMESTAMP
WHEN NOT MATCHED THEN
    INSERT (CLIENT_TYPE_CODE, REGISTRY_COMPANY_TYPE_CODE, ADD_USERID, ADD_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
    VALUES (src.CLIENT_TYPE_CODE, src.REGISTRY_COMPANY_TYPE_CODE, src.ADD_USERID, src.ADD_TIMESTAMP, src.UPDATE_USERID, src.UPDATE_TIMESTAMP);

-- Create a new entry in the REGISTRY_COMPANY_TYPE_CODE table for the BCeID FM type in an idempotent way
MERGE INTO THE.REGISTRY_COMPANY_TYPE_CODE tgt
USING (
    SELECT 'LL' AS REGISTRY_COMPANY_TYPE_CODE,
           'Limited Liability Partnership' AS DESCRIPTION,
           TIMESTAMP '2024-10-07 00:00:00.0' AS EFFECTIVE_DATE,
           TIMESTAMP '9999-12-31 00:00:00.0' AS EXPIRY_DATE,
           TIMESTAMP '2024-10-07 00:00:00.0' AS UPDATE_TIMESTAMP
    FROM DUAL
) src
ON (tgt.REGISTRY_COMPANY_TYPE_CODE = src.REGISTRY_COMPANY_TYPE_CODE)
WHEN MATCHED THEN
    UPDATE SET
        tgt.DESCRIPTION = src.DESCRIPTION,
        tgt.EFFECTIVE_DATE = src.EFFECTIVE_DATE,
        tgt.EXPIRY_DATE = src.EXPIRY_DATE,
        tgt.UPDATE_TIMESTAMP = src.UPDATE_TIMESTAMP
WHEN NOT MATCHED THEN
    INSERT (REGISTRY_COMPANY_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
    VALUES (src.REGISTRY_COMPANY_TYPE_CODE, src.DESCRIPTION, src.EFFECTIVE_DATE, src.EXPIRY_DATE, src.UPDATE_TIMESTAMP);

-- Create a new entry in the CLIENT_TYPE_COMPANY_XREF table for the BCeID FM code linking with I in an idempotent way
MERGE INTO THE.CLIENT_TYPE_COMPANY_XREF tgt
USING (
    SELECT 'L' AS CLIENT_TYPE_CODE,
           'LL' AS REGISTRY_COMPANY_TYPE_CODE,
           'CLIADMIN' AS ADD_USERID,
           TIMESTAMP '2024-10-07 00:00:00.0' AS ADD_TIMESTAMP,
           'CLIADMIN' AS UPDATE_USERID,
           TIMESTAMP '2024-10-07 00:00:00.0' AS UPDATE_TIMESTAMP
    FROM DUAL
) src
ON (tgt.CLIENT_TYPE_CODE = src.CLIENT_TYPE_CODE AND tgt.REGISTRY_COMPANY_TYPE_CODE = src.REGISTRY_COMPANY_TYPE_CODE)
WHEN MATCHED THEN
    UPDATE SET
        tgt.ADD_USERID = src.ADD_USERID,
        tgt.ADD_TIMESTAMP = src.ADD_TIMESTAMP,
        tgt.UPDATE_USERID = src.UPDATE_USERID,
        tgt.UPDATE_TIMESTAMP = src.UPDATE_TIMESTAMP
WHEN NOT MATCHED THEN
    INSERT (CLIENT_TYPE_CODE, REGISTRY_COMPANY_TYPE_CODE, ADD_USERID, ADD_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
    VALUES (src.CLIENT_TYPE_CODE, src.REGISTRY_COMPANY_TYPE_CODE, src.ADD_USERID, src.ADD_TIMESTAMP, src.UPDATE_USERID, src.UPDATE_TIMESTAMP);

-- Create a new entry in the REGISTRY_COMPANY_TYPE_CODE table for the BCeID FM type in an idempotent way
MERGE INTO THE.REGISTRY_COMPANY_TYPE_CODE tgt
USING (
    SELECT 'XP' AS REGISTRY_COMPANY_TYPE_CODE,
           'Extraprovincial Limited Partnership' AS DESCRIPTION,
           TIMESTAMP '2024-10-07 00:00:00.0' AS EFFECTIVE_DATE,
           TIMESTAMP '9999-12-31 00:00:00.0' AS EXPIRY_DATE,
           TIMESTAMP '2024-10-07 00:00:00.0' AS UPDATE_TIMESTAMP
    FROM DUAL
) src
ON (tgt.REGISTRY_COMPANY_TYPE_CODE = src.REGISTRY_COMPANY_TYPE_CODE)
WHEN MATCHED THEN
    UPDATE SET
        tgt.DESCRIPTION = src.DESCRIPTION,
        tgt.EFFECTIVE_DATE = src.EFFECTIVE_DATE,
        tgt.EXPIRY_DATE = src.EXPIRY_DATE,
        tgt.UPDATE_TIMESTAMP = src.UPDATE_TIMESTAMP
WHEN NOT MATCHED THEN
    INSERT (REGISTRY_COMPANY_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
    VALUES (src.REGISTRY_COMPANY_TYPE_CODE, src.DESCRIPTION, src.EFFECTIVE_DATE, src.EXPIRY_DATE, src.UPDATE_TIMESTAMP);

-- Create a new entry in the CLIENT_TYPE_COMPANY_XREF table for the BCeID FM code linking with I in an idempotent way
MERGE INTO THE.CLIENT_TYPE_COMPANY_XREF tgt
USING (
    SELECT 'L' AS CLIENT_TYPE_CODE,
           'XP' AS REGISTRY_COMPANY_TYPE_CODE,
           'CLIADMIN' AS ADD_USERID,
           TIMESTAMP '2024-10-07 00:00:00.0' AS ADD_TIMESTAMP,
           'CLIADMIN' AS UPDATE_USERID,
           TIMESTAMP '2024-10-07 00:00:00.0' AS UPDATE_TIMESTAMP
    FROM DUAL
) src
ON (tgt.CLIENT_TYPE_CODE = src.CLIENT_TYPE_CODE AND tgt.REGISTRY_COMPANY_TYPE_CODE = src.REGISTRY_COMPANY_TYPE_CODE)
WHEN MATCHED THEN
    UPDATE SET
        tgt.ADD_USERID = src.ADD_USERID,
        tgt.ADD_TIMESTAMP = src.ADD_TIMESTAMP,
        tgt.UPDATE_USERID = src.UPDATE_USERID,
        tgt.UPDATE_TIMESTAMP = src.UPDATE_TIMESTAMP
WHEN NOT MATCHED THEN
    INSERT (CLIENT_TYPE_CODE, REGISTRY_COMPANY_TYPE_CODE, ADD_USERID, ADD_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
    VALUES (src.CLIENT_TYPE_CODE, src.REGISTRY_COMPANY_TYPE_CODE, src.ADD_USERID, src.ADD_TIMESTAMP, src.UPDATE_USERID, src.UPDATE_TIMESTAMP);

-- Create a new entry in the REGISTRY_COMPANY_TYPE_CODE table for the BCeID FM type in an idempotent way
MERGE INTO THE.REGISTRY_COMPANY_TYPE_CODE tgt
USING (
    SELECT 'XL' AS REGISTRY_COMPANY_TYPE_CODE,
           'Extraprovincial Limited Liability Partnership' AS DESCRIPTION,
           TIMESTAMP '2024-10-07 00:00:00.0' AS EFFECTIVE_DATE,
           TIMESTAMP '9999-12-31 00:00:00.0' AS EXPIRY_DATE,
           TIMESTAMP '2024-10-07 00:00:00.0' AS UPDATE_TIMESTAMP
    FROM DUAL
) src
ON (tgt.REGISTRY_COMPANY_TYPE_CODE = src.REGISTRY_COMPANY_TYPE_CODE)
WHEN MATCHED THEN
    UPDATE SET
        tgt.DESCRIPTION = src.DESCRIPTION,
        tgt.EFFECTIVE_DATE = src.EFFECTIVE_DATE,
        tgt.EXPIRY_DATE = src.EXPIRY_DATE,
        tgt.UPDATE_TIMESTAMP = src.UPDATE_TIMESTAMP
WHEN NOT MATCHED THEN
    INSERT (REGISTRY_COMPANY_TYPE_CODE, DESCRIPTION, EFFECTIVE_DATE, EXPIRY_DATE, UPDATE_TIMESTAMP)
    VALUES (src.REGISTRY_COMPANY_TYPE_CODE, src.DESCRIPTION, src.EFFECTIVE_DATE, src.EXPIRY_DATE, src.UPDATE_TIMESTAMP);

-- Create a new entry in the CLIENT_TYPE_COMPANY_XREF table for the BCeID FM code linking with I in an idempotent way
MERGE INTO THE.CLIENT_TYPE_COMPANY_XREF tgt
USING (
    SELECT 'L' AS CLIENT_TYPE_CODE,
           'XL' AS REGISTRY_COMPANY_TYPE_CODE,
           'CLIADMIN' AS ADD_USERID,
           TIMESTAMP '2024-10-07 00:00:00.0' AS ADD_TIMESTAMP,
           'CLIADMIN' AS UPDATE_USERID,
           TIMESTAMP '2024-10-07 00:00:00.0' AS UPDATE_TIMESTAMP
    FROM DUAL
) src
ON (tgt.CLIENT_TYPE_CODE = src.CLIENT_TYPE_CODE AND tgt.REGISTRY_COMPANY_TYPE_CODE = src.REGISTRY_COMPANY_TYPE_CODE)
WHEN MATCHED THEN
    UPDATE SET
        tgt.ADD_USERID = src.ADD_USERID,
        tgt.ADD_TIMESTAMP = src.ADD_TIMESTAMP,
        tgt.UPDATE_USERID = src.UPDATE_USERID,
        tgt.UPDATE_TIMESTAMP = src.UPDATE_TIMESTAMP
WHEN NOT MATCHED THEN
    INSERT (CLIENT_TYPE_CODE, REGISTRY_COMPANY_TYPE_CODE, ADD_USERID, ADD_TIMESTAMP, UPDATE_USERID, UPDATE_TIMESTAMP)
    VALUES (src.CLIENT_TYPE_CODE, src.REGISTRY_COMPANY_TYPE_CODE, src.ADD_USERID, src.ADD_TIMESTAMP, src.UPDATE_USERID, src.UPDATE_TIMESTAMP);

