services:
  - name: nrfc
    host: nrfc-test-backend.d2723f-test.svc
    tags: [ns.d2723f.test]
    port: 80
    protocol: http
    retries: 0
    routes:
      - name: nrfc-route
        tags: [ns.d2723f.test]
        hosts:
          - nrfc.api.gov.bc.ca
        paths:
          - /
        methods:
          - GET
        strip_path: false
        https_redirect_status_code: 426
        path_handling: v0
    plugins:
      - name: key-auth
        tags: [ns.d2723f.test]
        protocols: [http, https]
        config:
          key_names: ["X-API-KEY"]
          run_on_preflight: true
          hide_credentials: true
          key_in_body: false
      - name: acl
        tags: [ns.d2723f.test]
        config:
          hide_groups_header: true
          allow: [E990939D]
