services:
  - name: nrfc-swagger
    host: nrfc-prod-backend.d2723f-prod.svc
    tags: [ns.nr-d2723f.doc]
    port: 80
    protocol: http
    retries: 0
    routes:
      - name: nrfc-swagger-route
        tags: [ns.nr-d2723f.doc]
        hosts:
          - nrfc-swagger.api.gov.bc.ca
        paths:
          - /api
        methods:
          - GET
        strip_path: false
        https_redirect_status_code: 426
        path_handling: v0
