spring:
  flyway:
    enabled: true
    locations: classpath:dbmigrations
  r2dbc:
    url: r2dbc:oracle://${ca.bc.gov.nrs.oracle.host}:${ca.bc.gov.nrs.oracle.port}/${ca.bc.gov.nrs.oracle.service}
ca:
  bc:
    gov:
      nrs:
        oracle:
          port: 1521