server:
  port: 3100

spring:
  application:
    name: nr-forest-client-${APP_COMPONENT:processor}
  main:
    lazy-initialization: false
    banner-mode: "off"
    allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:postgresql://${ca.bc.gov.nrs.postgres.host}/${ca.bc.gov.nrs.postgres.database}
    username: ${ca.bc.gov.nrs.postgres.username}
    password: ${ca.bc.gov.nrs.postgres.password}
    pool:
      enabled: true
      initialSize: 1
      minIdle: 1
      maxSize: 1
      maxLifeTime: 60000
      maxIdleTime: 45000
      maxCreateConnectionTime: 90000
      poolName: FsaProcessorClientConPool
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  sleuth:
    propagation-keys:
      - X-TRACE-ID
    baggage-keys:
      - X-TRACE-ID
    log:
      slf4j:
        whitelisted-mdc-keys:
          - X-TRACE-ID

management:
  enable-native-support: true
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      path-mapping:
        prometheus: metrics
      base-path: /
      exposure:
        include: health,info,metrics,otlp,tracing
  httpexchanges:
    recording:
      include: principal,request-headers,response-headers,cookie-headers,time-taken,authorization-header,remote-address,session-id
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    enabled: false
    baggage:
      remote-fields:
        - X-TRACE-ID
      correlation:
        fields:
          - X-TRACE-ID
    sampling:
      probability: 0.75
  zipkin:
    metrics:
      export:
        enabled: true

info:
  app:
    name: ${spring.application.name}
    zone: ${APP_ZONE:local}

ca:
  bc:
    gov:
      nrs:
        processor:
          poolTime: ${TIMING:5M}
        backend:
          uri: ${CLIENT_URI:http://localhost:8080/api}
        legacy:
          uri: ${LEGACY_URI:http://localhost:9999/api}
        postgres:
          database: ${POSTGRESQL_DATABASE:fsa-forest}
          host: ${POSTGRESQL_HOST:localhost}:5432
          username: ${POSTGRESQL_USER:user}
          password: ${POSTGRESQL_PASSWORD:passwd}
          url: r2dbc:postgresql://${ca.bc.gov.nrs.postgres.host}/${ca.bc.gov.nrs.postgres.database}
        bcregistry:
          uri: ${BCREGISTRY_URI:https://bcregistry-sandbox.apigee.net}
          apiKey: ${BCREGISTRY_KEY:123456}
          accountId: ${BCREGISTRY_ACCOUNT:123456}
        security:
          service-account-name: ${PROCESSOR_SERVICE_ACCOUNT_NAME}
          service-account-secret: ${PROCESSOR_SERVICE_ACCOUNT_SECRET}


logging:
  pattern:
    correlation: "[${spring.application.name:},%X{${X-TRACE-ID:traceId}:-},%X{spanId:-}] "

# Profile Specific Properties
---
spring:
  config:
    activate:
      on-profile: container
  sleuth:
    propagation-keys:
      - X-TRACE-ID
    baggage-keys:
      - X-TRACE-ID
    log:
      slf4j:
        whitelisted-mdc-keys:
          - X-TRACE-ID

logging:
  pattern:
    console: "{\"time\": \"%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}\", \"level\": \"${LOG_LEVEL:%5p}\", \"app\":\"${spring.application.name:-}\", \"traceId\":\"%X{${X-TRACE-ID:traceId}:-}\", \"spanId\":\"%X{spanId:-}\", \"pid\": \"${PID: }\", \"thread\": \"%t\", \"source\": \"%logger{63}:%L\", \"message\": \"%m${LOG_EXCEPTION_CONVERSION_WORD:%wEx}\"}%n"