server:
  port: 3100

spring:
  application:
    name: FSA Forest Client Processor
  main:
    lazy-initialization: false
    banner-mode: "off"
    allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:postgresql://${ca.bc.gov.nrs.postgres.host}/${ca.bc.gov.nrs.postgres.database}
    username: ${ca.bc.gov.nrs.postgres.username}
    password: ${ca.bc.gov.nrs.postgres.password}
    pool:
      enabled: true
      initialSize: 1
      minIdle: 1
      maxSize: 1
      maxLifeTime: 60000
      maxIdleTime: 45000
      maxCreateConnectionTime: 90000
      poolName: FsaProcessorClientConPool

management:
  enable-native-support: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,metrics

ca:
  bc:
    gov:
      nrs:
        processor:
          poolTime: ${TIMING:5M}
        backend:
          uri: ${CLIENT_URI:http://localhost:8080/api}
        legacy:
          uri: ${LEGACY_URI:http://localhost:9999/api}
        postgres:
          database: ${POSTGRESQL_DATABASE:fsa-forest}
          host: ${POSTGRESQL_HOST:localhost}:5432
          username: ${POSTGRESQL_USER:user}
          password: ${POSTGRESQL_PASSWORD:passwd}
          url: r2dbc:postgresql://${ca.bc.gov.nrs.postgres.host}/${ca.bc.gov.nrs.postgres.database}
        bcregistry:
          uri: ${BCREGISTRY_URI:https://bcregistry-sandbox.apigee.net}
          apiKey: ${BCREGISTRY_KEY:123456}
          accountId: ${BCREGISTRY_ACCOUNT:123456}
