apiVersion: template.openshift.io/v1
kind: Template
parameters:
  - name: NAME
    description: Product name
    value: nr-forest-client
  - name: ZONE
    description: Deployment zone, e.g. pr-### or prod
    required: true
  - name: DB_PASSWORD
    description: Password for the PostgreSQL connection user.
    required: true
  - name: ORACLEDB_USER
    description: Oracle database user name
    required: true
  - name: ORACLEDB_PASSWORD
    description: Oracle database password
    required: true    
  - name: ORACLEDB_DATABASE
    description: Oracle database database name
    required: true
  - name: ORACLEDB_HOST
    description: Oracle database host
    required: true
  - name: ORACLEDB_SERVICENAME
    description: Oracle database service name
    required: true
  - name: ORACLEDB_SECRET
    description: Oracle database keystore secret/password
    required: true
  - name: BCREGISTRY_KEY
    description: BC Registry key
    required: true
  - name: BCREGISTRY_ACCOUNT
    description: BC Registry account Id
    required: true
  - name: CHES_CLIENT_ID
    description: CHES service client id
    required: true
  - name: CHES_CLIENT_SECRET
    description: CHES service client secret
    required: true
  - name: ADDRESS_COMPLETE_KEY
    description: Canada Post API key
    required: true
  - name: VITE_KEYCLOAK_CLIENT_ID
    value: ""
  - name: IDX_PVC_SIZE
    description: Volume space available for data, e.g. 512Mi, 2Gi.
    displayName: Database Volume Capacity
    required: true
    value: 256Mi
  - name: IDX_BKP_PVC_SIZE
    description: Volume space available for data, e.g. 512Mi, 2Gi.
    displayName: Database Backup Volume Capacity
    required: true
    value: 256Mi
  - name: COGNITO_CLIENT_ID
    required: true
  - name: COGNITO_DOMAIN
    value: 'lza-prod-fam-user-pool-domain'
  - name: COGNITO_ENVIRONMENT
    required: true
  - name: COGNITO_USER_POOL
    description: Cognito user pool id
    required: true
  - name: COGNITO_REGION
    description: Cognito region information
    value: 'ca-central-1'
  - name: CHES_MAIL_COPY
    description: Email address to copy all CHES emails to
    required: true
  - name: PROCESSOR_SERVICE_ACCOUNT_SECRET
    description: Password for the Processor service
    from: "[a-zA-Z0-9]{16}"
    generate: expression
  - name: GREEN_DOMAIN
    description: Green domain
    required: true
  - name: LANDING_URL
    required: true
  - name: URL_FRONTEND
    description: Frontend URL
    required: true
  - name: DOMAIN
    value: apps.silver.devops.gov.bc.ca
  - name: SPRING_PROFILES_ACTIVE
    description: Spring profile
    required: true
  - name: VITE_NODE_ENV
    required: true
  - name: PEM_VALUE
    required: true
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}-${ZONE}
      labels:
        app: ${NAME}-${ZONE}
    stringData:
      database-name: ${NAME}
      database-password: ${DB_PASSWORD}
      database-user: ${NAME}  
      oracle-user: ${ORACLEDB_USER}
      oracle-password: ${ORACLEDB_PASSWORD}
      oracle-database: ${ORACLEDB_DATABASE}
      oracle-host: ${ORACLEDB_HOST}
      oracle-service: ${ORACLEDB_SERVICENAME}
      oracle-secret: ${ORACLEDB_SECRET}  
      ches-client-id: ${CHES_CLIENT_ID}
      ches-client-secret: ${CHES_CLIENT_SECRET}
      bcregistry-key: ${BCREGISTRY_KEY}
      bcregistry-account: ${BCREGISTRY_ACCOUNT}
      address-complete-key: ${ADDRESS_COMPLETE_KEY}      
      cognito-user-pool: ${COGNITO_USER_POOL}
      cognito-environment: ${COGNITO_ENVIRONMENT}      
      ches-mail-copy: ${CHES_MAIL_COPY}
      processor-service-account-secret: ${PROCESSOR_SERVICE_ACCOUNT_SECRET}
      processor-service-account-name: processor-service-account
      spring-profiles-active: "container,${SPRING_PROFILES_ACTIVE}"
      pem-value: ${PEM_VALUE}
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-from-openshift-ingress
      labels:
        template: openshift-test
    spec:
      podSelector: {}
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  network.openshift.io/policy-group: ingress
      policyTypes:
        - Ingress
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-same-namespace
      labels:
        template: quickstart-network-security-policy
    spec:
      podSelector: {}
      ingress:
        - from:
            - podSelector: {}
      policyTypes:
        - Ingress
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      labels:
        app: ${NAME}-${ZONE}
      name: ${NAME}-${ZONE}-frontend
    data:
      config.js: |
        window.localStorage.setItem('VITE_BACKEND_URL', 'https://${NAME}-${ZONE}-backend.${DOMAIN}');
        window.localStorage.setItem('VITE_FRONTEND_URL', 'https://${URL_FRONTEND}');
        window.localStorage.setItem('VITE_NODE_ENV', '${VITE_NODE_ENV}');
        window.localStorage.setItem('VITE_GREEN_DOMAIN', '${GREEN_DOMAIN}');
        window.localStorage.setItem('VITE_AWS_COGNITO_CLIENT_ID','${COGNITO_CLIENT_ID}');
        window.localStorage.setItem('VITE_AWS_COGNITO_DOMAIN','${COGNITO_DOMAIN}');
        window.localStorage.setItem('VITE_AWS_COGNITO_ENVIRONMENT','${COGNITO_ENVIRONMENT}');
        window.localStorage.setItem('VITE_AWS_COGNITO_POOL_ID','${COGNITO_USER_POOL}');
        window.localStorage.setItem('VITE_AWS_COGNITO_REGION','${COGNITO_REGION}');
        window.localStorage.setItem('VITE_LOGOUT_BCSC_URL','${LANDING_URL}');
        window.localStorage.setItem('VITE_LOGOUT_BCEIDBUSINESS_URL','${LANDING_URL}');
        window.localStorage.setItem('VITE_LOGOUT_IDIR_URL','https://${URL_FRONTEND}');
