spring:
  application:
    name: nr-forest-client-${APP_COMPONENT:backend}
  main:
    lazy-initialization: false
    banner-mode: "off"
    allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:postgresql://${ca.bc.gov.nrs.postgres.host}/${ca.bc.gov.nrs.postgres.database}
    username: ${ca.bc.gov.nrs.postgres.username}
    password: ${ca.bc.gov.nrs.postgres.password}
    pool:
      enabled: true
      initialSize: 1
      minIdle: 1
      maxSize: 3
      maxLifeTime: 60000
      maxIdleTime: 45000
      maxCreateConnectionTime: 90000
      poolName: FsaClientConPool
  flyway:
    locations: classpath:db/migration
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true
    user: ${ca.bc.gov.nrs.postgres.username}
    password: ${ca.bc.gov.nrs.postgres.password}
    url: jdbc:postgresql://${ca.bc.gov.nrs.postgres.host}/${ca.bc.gov.nrs.postgres.database}
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  sleuth:
    propagation-keys:
      - X-TRACE-ID
    baggage-keys:
      - X-TRACE-ID
    log:
      slf4j:
        whitelisted-mdc-keys:
          - X-TRACE-ID

management:
  enable-native-support: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      path-mapping:
        prometheus: metrics
      base-path: /
      exposure:
        include: health,info,metrics,otlp,tracing
  httpexchanges:
    recording:
      include: principal,request-headers,response-headers,cookie-headers,time-taken,authorization-header,remote-address,session-id
  tracing:
    enabled: false
    baggage:
      remote-fields:
        - X-TRACE-ID
      correlation:
        fields:
          - X-TRACE-ID
    sampling:
      probability: 0.75
  zipkin:
    metrics:
      export:
        enabled: true

info:
  app:
    name: ${spring.application.name}
    zone: ${APP_ZONE:local}

ca:
  bc:
    gov:
      nrs:
        submissionLimit: ${SUBMISSION_LIMIT:7D}
        ches:
          uri: ${CHES_API_URL:http://127.0.0.1:10010/chess/uri}
          tokenUrl: ${CHES_TOKEN_URL:http://127.0.0.1:10010/token/uri}
          clientId: ${CHES_CLIENT_ID:clientId}
          clientSecret: ${CHES_CLIENT_SECRET:secret}
          scope: scope
          copyEmail: ${CHES_COPY_EMAIL:email@email.ca}
        bcregistry:
          uri: ${BCREGISTRY_URI:https://bcregistry-sandbox.apigee.net}
          apiKey: ${BCREGISTRY_KEY:123456}
          accountId: ${BCREGISTRY_ACCOUNT:123456}
        postgres:
          database: ${POSTGRESQL_DATABASE:fsa-forest}
          host: ${POSTGRESQL_HOST:localhost}:5432
          username: ${POSTGRESQL_USER:user}
          password: ${POSTGRESQL_PASSWORD:passwd}
        legacy:
          url: ${LEGACY_URL:http://127.0.0.1:9019/api}
        addressComplete:
          url: ${ADDRESS_COMPLETE_URL:https://ws1.postescanada-canadapost.ca/addresscomplete/interactive}
          apiKey: ${ADDRESS_COMPLETE_KEY:apiKey}
        cognito:
          region: ${COGNITO_REGION}
          client-id: ${COGNITO_CLIENT_ID}
          user-pool: ${COGNITO_USER_POOL}
          domain: ${COGNITO_DOMAIN}
          environment: ${COGNITO_ENVIRONMENT}
          redirect-uri: ${COGNITO_REDIRECT_URI}
          logout-uri: ${COGNITO_LOGOUT_URI}
          cookie-domain: ${COGNITO_COOKIE_DOMAIN}
        frontend:
          url: ${FRONTEND_URL:*}
          cors:
            headers:
              - x-requested-with
              - X-REQUESTED-WITH
              - authorization
              - Authorization
              - Content-Type
              - content-type
              - credential
              - CREDENTIAL
              - X-XSRF-TOKEN
              - access-control-allow-origin
              - Access-Control-Allow-Origin
              - DNT
              - Keep-Alive,
              - User-Agent,
              - X-Requested-With,
              - If-Modified-Since,
              - Cache-Control,
              - Content-Range,
              - Range
              - Location
              - location
              - x-sub-id
              - X-Sub-Id
              - x-user-id
              - X-User-Id
              - x-user-email
              - X-User-Email
              - x-user-name
              - X-User-Name
              - x-user-businessid
              - X-User-Businessid
              - x-total-count
              - X-Total-Count
            methods:
              - OPTIONS
              - GET
              - POST
              - PUT
              - DELETE
            age: 5m

logging:
  pattern:
    correlation: "[${spring.application.name:},%X{${X-TRACE-ID:traceId}:-},%X{spanId:-}] "

# Profile Specific Properties
---
spring:
  config:
    activate:
      on-profile: container
  sleuth:
    propagation-keys:
      - X-TRACE-ID
    baggage-keys:
      - X-TRACE-ID
    log:
      slf4j:
        whitelisted-mdc-keys:
          - X-TRACE-ID

logging:
  pattern:
    console: "{\"time\": \"%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}\", \"level\": \"${LOG_LEVEL:%5p}\", \"app\":\"${spring.application.name:-}\", \"traceId\":\"%X{${X-TRACE-ID:traceId}:-}\", \"spanId\":\"%X{spanId:-}\", \"pid\": \"${PID: }\", \"thread\": \"%t\", \"source\": \"%logger{63}:%L\", \"message\": \"%m${LOG_EXCEPTION_CONVERSION_WORD:%wEx}\"}%n"