server:
  port: 3000

spring:
  application:
    name: FSA Forest Client
  main:
    lazy-initialization: false
    banner-mode: "off"
    allow-bean-definition-overriding: true
  jpa:
    show-sql: false
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
  datasource:
    url: jdbc:postgresql://${ca.bc.gov.postgres.host}/${ca.bc.gov.postgres.database}
    username: ${ca.bc.gov.postgres.username}
    password: ${ca.bc.gov.postgres.password}
    hikari:
      connectionTimeout: 90000
      idleTimeout: 45000
      maxLifetime: 60000
      keepaliveTime: 30000
      poolName: FsaClientConPool
      minimumIdle: 1
      maximumPoolSize: 3

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
  httpexchanges:
    recording:
      include: principal,request-headers,response-headers,cookie-headers,time-taken,authorization-header,remote-address,session-id

springdoc:
  webjars:
    prefix: /v3
  api-docs:
    groups:
      enabled: true
  show-actuator: false

frontend:
  url: ${FRONTEND_URL:*}


ca:
  bc:
    gov:
      ches:
        uri: http://127.0.0.1:10010/chess/uri
        tokenUrl: http://127.0.0.1:10010/token/uri
        clientId: clientId
        clientSecret: secret
        scope: scope
      postgres:
        database: ${POSTGRESQL_DATABASE:fsa-forest}
        host: ${POSTGRESQL_HOST:localhost}:5432
        username: ${POSTGRESQL_USER:user}
        password: ${POSTGRESQL_PASSWORD:passwd}