name: Reusable Unit Tests and Analysis

on:
  workflow_call:

jobs:
  vars:
    name: Set Variables
    outputs:
      user: ${{ steps.data.outputs.user }}
      pass: ${{ steps.data.outputs.pass }}
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    steps:
      - name: Generate random username and password
        id: data
        run: |          
          USERNAME="user$(shuf -i 1000-9999 -n 1)"
          PASSWORD=$(openssl rand -base64 12)

          echo "user=$USERNAME" >> $GITHUB_OUTPUT
          echo "pass=$PASSWORD" >> $GITHUB_OUTPUT

  schemaspy:
    name: Generate Documentation
    runs-on: ubuntu-22.04
    needs: [vars]
    services:
      postgres:
        image: postgis/postgis:16-3.4
        env:
          POSTGRES_DB: default
          POSTGRES_USER: ${{ needs.vars.outputs.user }}
          POSTGRES_PASSWORD: ${{ needs.vars.outputs.pass }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Flyway
        uses: docker://flyway/flyway:10
        env:
          FLYWAY_URL: jdbc:postgresql://postgres:5432/default
          FLYWAY_USER: ${{ needs.vars.outputs.user }}
          FLYWAY_PASSWORD: ${{ needs.vars.outputs.pass }}
          FLYWAY_LOCATIONS: filesystem:./backend/src/main/resources/db/migration
          FLYWAY_DEFAULT_SCHEMA: "nrfc"
        with:
          args: info migrate info

      - name: Create Output Folder
        run: |
          mkdir -p output/schema
          chmod a+rwx -R output

      - name: Run Schemaspy
        run: docker run --network host -v "$PWD/output/schema:/output" schemaspy/schemaspy:6.2.4 -t pgsql11 -db default -host 127.0.0.1 -port 5432 -u ${{ needs.vars.outputs.user }} -p ${{ needs.vars.outputs.pass }} -schemas nrfc

      - name: Convert README.md to index.html
        continue-on-error: true
        run: |
          sudo apt-get install -y pandoc
          sed -i 's/README.md/index.html/g' README.md
          pandoc README.md -o index.html
          mv index.html output/
 
      - name: Set up JDK 17 and Caching maven dependencies
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"
          server-id: "github"

      - name: Generate docs for Backend
        continue-on-error: true
        working-directory: backend
        run: ./mvnw clean javadoc:javadoc

      - name: Copy Backend docs to output
        run: mv backend/target/site/apidocs/ output/backend/

      - name: Generate docs for Legacy
        continue-on-error: true
        working-directory: legacy
        run: ./mvnw clean javadoc:javadoc

      - name: Copy Legacy docs to output
        run: mv legacy/target/site/apidocs/ output/legacy/

      - name: Generate docs for Processor
        continue-on-error: true
        working-directory: processor
        run: ./mvnw clean javadoc:javadoc

      - name: Copy Legacy docs to output
        run: mv processor/target/site/apidocs/ output/processor/

      - name: Deploy to Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: output