name: Reusable Unit Tests and Analysis

on:
  workflow_call:

jobs:
  trivy:
    name: Repository Report
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.18.0
        with:
          format: "sarif"
          output: "trivy-results.sarif"
          ignore-unfixed: true
          scan-type: "fs"
          scanners: "vuln,secret,config"
          severity: "CRITICAL,HIGH"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"

      - name: Upload Trivy scan results to S3
        uses: actions/upload-artifact@v2
        with:
          name: trivy-results
          path: trivy-results.sarif

  codeql:
    name: Semantic Code Analysis
    runs-on: ubuntu-22.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with:
          languages: javascript,java

      # Autobuild failed for Java, so building manually
      - name: Set up JDK 17 and Caching maven dependencies
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"

      # Java builds
      - name: Build Backend
        working-directory: backend
        run: ./mvnw clean package

      - name: Build Legacy
        working-directory: legacy
        run: ./mvnw clean package

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  owasp-be:
    name: Owasp Code Analysis for Backend
    runs-on: ubuntu-22.04
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      matrix:
        package: [backend, legacy, processor]
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17 and Caching maven dependencies
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"

      # Java builds
      - name: Owasp ${{ matrix.package }}
        working-directory: ${{ matrix.package }}
        run: mvn clean validate --owasp.skip=false

      - name: Owasp ${{ matrix.package }} file cleanup
        run: |
          if [ -f "${{ matrix.package }}/target/dependency-check-report.sarif" ]; then
            sed -i 's/\[,/[/' ${{ matrix.package }}/target/dependency-check-report.sarif
          fi

      - name: Upload Owasp ${{ matrix.package }} scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "${{ matrix.package }}/target/dependency-check-report.sarif"

  owasp-fe:
    name: Owasp Code Analysis for Frontend
    runs-on: ubuntu-22.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Owasp frontend
        working-directory: frontend
        run: |
          npm install
          npm run test:owasp

      - name: Upload Owasp frontend scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "frontend/reports/owasp/dependency-check-report.sarif"
