name: Unit Tests and Analysis

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests-java:
    name: ${{ matrix.package }} Integrated Tests
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        package: [ backend, legacy, processor ]
        include:
          - package: backend
            triggers: ('backend/')
            token: ('${{ secrets.SONAR_TOKEN_BACKEND }}')
            key: forest-client-backend
          - package: legacy
            triggers: ('legacy/')
            token: ("${{ secrets.SONAR_TOKEN_LEGACY }}")
            key: forest-client-backend
          - package: processor
            triggers: ('processor/')
            token: (${{ secrets.SONAR_TOKEN_PROCESSOR }})
            key: forest-client-processor
    steps:
      - uses: bcgov-nr/action-test-and-analyse-java@v0.1.0
        name: Coverage
        with:
          commands: |
            mvn -B verify -P all-tests checkstyle:checkstyle -Dcheckstyle.skip=false --file pom.xml
          dir: backend
          java-cache: maven
          java-distribution: temurin
          java-version: "17"
          sonar_args: >
            -Dsonar.organization=bcgov-sonarcloud
            -Dsonar.projectKey=${{ matrix.key }}
          sonar_project_token: ${{ matrix.token }}

      - name: Archive CycloneDX
        continue-on-error: true
        uses: actions/upload-artifact@v3
        with:
          name: cyclone-${{ matrix.package }}
          path: target/bom.json
          retention-days: 5

      - name: Use Checkstyle report
        continue-on-error: true
        uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: ${{ matrix.package }}/**/checkstyle-result.xml

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        continue-on-error: true
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: ${{ matrix.package }}/target/**/TEST-*.xml
          commit: ${{ github.event.pull_request.head.sha }}
          summary: Pull Request Tests ${{ matrix.package }}
          detailed_summary: true
          job_name: ${{ matrix.package }} Tests

      - name: Add coverage to PR
        id: jacoco
        continue-on-error: true
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: ${{ matrix.package }}/target/coverage-reports/merged-test-report/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 75
          min-coverage-changed-files: 75

  tests-frontend:
    name: Frontend Unit Tests
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    runs-on: ubuntu-22.04
    steps:
      - uses: bcgov-nr/action-test-and-analyse@v0.0.1
        with:
          commands: |
            npm ci
            npm run test
          dir: frontend
          sonar_args: >
            -Dsonar.exclusions=**/coverage/**,**/examples/**,**/pages/**
            -Dsonar.organization=bcgov-sonarcloud
            -Dsonar.projectKey=forest-client-frontend
            -Dsonar.tests=src/tests
          sonar_project_token: ${{ secrets.SONAR_TOKEN_FRONTEND }}
  
  trivy:
    name: Repository Report
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.9.1
        with:
          scan-type: "fs"
          format: "sarif"
          output: "trivy-results.sarif"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
          security-checks: "vuln,secret,config"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results.sarif"
