name: Unit Tests and Analysis

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review, converted_to_draft]
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests-java:
    uses: ./.github/workflows/reusable-tests-be.yml

  tests-frontend:
    uses: ./.github/workflows/reusable-tests-fe.yml

  trivy:
    uses: ./.github/workflows/reusable-tests-repo.yml
