name: Unit Tests and Analysis

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review, converted_to_draft]
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests-java:
    name: Backend Tests
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    uses: ./.github/workflows/reusable-tests-be.yml
    with:
      uid: ${{ github.event.number || 'main' }}

  tests-frontend:
    name: Frontend Unit Tests
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    uses: ./.github/workflows/reusable-tests-fe.yml

  trivy:
    name: Repository Report
    uses: ./.github/workflows/reusable-tests-repo.yml
