package ca.bc.gov.app.repository;

import lombok.AccessLevel;
import lombok.NoArgsConstructor;

@NoArgsConstructor(access = AccessLevel.PRIVATE)
public final class ForestClientQueries {

  public static final String CLIENT_INFORMATION_HISTORY = """
      WITH AUDIT_DATA AS (
        SELECT
            'ClientInformation' AS TABLE_NAME,
            AL.FOREST_CLIENT_AUDIT_ID AS IDX,
            'clientName' AS COLUMN_NAME,
            CLIENT_NAME AS NEW_VALUE,
            LAG(CLIENT_NAME) OVER (
                PARTITION BY AL.CLIENT_NUMBER
                ORDER BY AL.FOREST_CLIENT_AUDIT_ID
            ) AS OLD_VALUE,
            AL.UPDATE_TIMESTAMP,
            AL.UPDATE_USERID,
            AL.CLIENT_AUDIT_CODE AS CHANGE_TYPE,
            UR.CLIENT_UPDATE_ACTION_CODE AS ACTION_CODE,
            RC.DESCRIPTION AS REASON,
            1 AS FIELD_ORDER
        FROM THE.FOR_CLI_AUDIT AL
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON UR
            ON AL.FOREST_CLIENT_AUDIT_ID = UR.FOREST_CLIENT_AUDIT_ID
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON_CODE RC
            ON UR.CLIENT_UPDATE_REASON_CODE = RC.CLIENT_UPDATE_REASON_CODE
        WHERE AL.CLIENT_NUMBER = :clientNumber
  
        UNION ALL
  
        SELECT
            'ClientInformation',
            AL.FOREST_CLIENT_AUDIT_ID,
            'clientAcronym',
            CLIENT_ACRONYM,
            LAG(CLIENT_ACRONYM) OVER (
                PARTITION BY AL.CLIENT_NUMBER
                ORDER BY AL.FOREST_CLIENT_AUDIT_ID
            ),
            AL.UPDATE_TIMESTAMP,
            AL.UPDATE_USERID,
            AL.CLIENT_AUDIT_CODE,
            UR.CLIENT_UPDATE_ACTION_CODE,
            RC.DESCRIPTION,
            2 AS FIELD_ORDER
        FROM THE.FOR_CLI_AUDIT AL
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON UR
            ON AL.FOREST_CLIENT_AUDIT_ID = UR.FOREST_CLIENT_AUDIT_ID
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON_CODE RC
            ON UR.CLIENT_UPDATE_REASON_CODE = RC.CLIENT_UPDATE_REASON_CODE
        WHERE AL.CLIENT_NUMBER = :clientNumber
  
        UNION ALL
  
        SELECT
            'ClientInformation',
            AL.FOREST_CLIENT_AUDIT_ID,
            'legalFirstName',
            LEGAL_FIRST_NAME,
            LAG(LEGAL_FIRST_NAME) OVER (
                PARTITION BY AL.CLIENT_NUMBER
                ORDER BY AL.FOREST_CLIENT_AUDIT_ID
            ),
            AL.UPDATE_TIMESTAMP,
            AL.UPDATE_USERID,
            AL.CLIENT_AUDIT_CODE,
            UR.CLIENT_UPDATE_ACTION_CODE,
            RC.DESCRIPTION,
            3 AS FIELD_ORDER
        FROM THE.FOR_CLI_AUDIT AL
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON UR
            ON AL.FOREST_CLIENT_AUDIT_ID = UR.FOREST_CLIENT_AUDIT_ID
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON_CODE RC
            ON UR.CLIENT_UPDATE_REASON_CODE = RC.CLIENT_UPDATE_REASON_CODE
        WHERE AL.CLIENT_NUMBER = :clientNumber
  
        UNION ALL
  
        SELECT
            'ClientInformation',
            AL.FOREST_CLIENT_AUDIT_ID,
            'legalMiddleName',
            LEGAL_MIDDLE_NAME,
            LAG(LEGAL_MIDDLE_NAME) OVER (
                PARTITION BY AL.CLIENT_NUMBER
                ORDER BY AL.FOREST_CLIENT_AUDIT_ID
            ),
            AL.UPDATE_TIMESTAMP,
            AL.UPDATE_USERID,
            AL.CLIENT_AUDIT_CODE,
            UR.CLIENT_UPDATE_ACTION_CODE,
            RC.DESCRIPTION,
            4 AS FIELD_ORDER
        FROM THE.FOR_CLI_AUDIT AL
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON UR
            ON AL.FOREST_CLIENT_AUDIT_ID = UR.FOREST_CLIENT_AUDIT_ID
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON_CODE RC
            ON UR.CLIENT_UPDATE_REASON_CODE = RC.CLIENT_UPDATE_REASON_CODE
        WHERE AL.CLIENT_NUMBER = :clientNumber
  
        UNION ALL
  
        SELECT
            'ClientInformation',
            AL.FOREST_CLIENT_AUDIT_ID,
            'clientTypeDesc',
            TC.DESCRIPTION,
            LAG(TC.DESCRIPTION) OVER (
                PARTITION BY AL.CLIENT_NUMBER
                ORDER BY AL.FOREST_CLIENT_AUDIT_ID
            ),
            AL.UPDATE_TIMESTAMP,
            AL.UPDATE_USERID,
            AL.CLIENT_AUDIT_CODE,
            UR.CLIENT_UPDATE_ACTION_CODE,
            RC.DESCRIPTION,
            5 AS FIELD_ORDER
        FROM THE.FOR_CLI_AUDIT AL
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON UR
            ON AL.FOREST_CLIENT_AUDIT_ID = UR.FOREST_CLIENT_AUDIT_ID
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON_CODE RC
            ON UR.CLIENT_UPDATE_REASON_CODE = RC.CLIENT_UPDATE_REASON_CODE
        LEFT OUTER JOIN THE.CLIENT_TYPE_CODE TC
            ON AL.CLIENT_TYPE_CODE = TC.CLIENT_TYPE_CODE
        WHERE AL.CLIENT_NUMBER = :clientNumber
  
        UNION ALL
  
        SELECT
            'ClientInformation',
            AL.FOREST_CLIENT_AUDIT_ID,
            'birthdate',
            TO_CHAR(BIRTHDATE, 'YYYY-MM-DD'),
            LAG(TO_CHAR(BIRTHDATE, 'YYYY-MM-DD')) OVER (
                PARTITION BY AL.CLIENT_NUMBER
                ORDER BY AL.FOREST_CLIENT_AUDIT_ID
            ),
            AL.UPDATE_TIMESTAMP,
            AL.UPDATE_USERID,
            AL.CLIENT_AUDIT_CODE,
            UR.CLIENT_UPDATE_ACTION_CODE,
            RC.DESCRIPTION,
            6 AS FIELD_ORDER
        FROM THE.FOR_CLI_AUDIT AL
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON UR
            ON AL.FOREST_CLIENT_AUDIT_ID = UR.FOREST_CLIENT_AUDIT_ID
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON_CODE RC
            ON UR.CLIENT_UPDATE_REASON_CODE = RC.CLIENT_UPDATE_REASON_CODE
        WHERE AL.CLIENT_NUMBER = :clientNumber
  
        UNION ALL
  
        SELECT
            'ClientInformation',
            AL.FOREST_CLIENT_AUDIT_ID,
            'clientIdTypeDesc',
            IDTC.DESCRIPTION,
            LAG(IDTC.DESCRIPTION) OVER (
                PARTITION BY AL.CLIENT_NUMBER
                ORDER BY AL.FOREST_CLIENT_AUDIT_ID
            ),
            AL.UPDATE_TIMESTAMP,
            AL.UPDATE_USERID,
            AL.CLIENT_AUDIT_CODE,
            UR.CLIENT_UPDATE_ACTION_CODE,
            RC.DESCRIPTION,
            7 AS FIELD_ORDER
        FROM THE.FOR_CLI_AUDIT AL
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON UR
            ON AL.FOREST_CLIENT_AUDIT_ID = UR.FOREST_CLIENT_AUDIT_ID
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON_CODE RC
            ON UR.CLIENT_UPDATE_REASON_CODE = RC.CLIENT_UPDATE_REASON_CODE
        LEFT OUTER JOIN THE.CLIENT_ID_TYPE_CODE IDTC
            ON AL.CLIENT_ID_TYPE_CODE = IDTC.CLIENT_ID_TYPE_CODE
        WHERE AL.CLIENT_NUMBER = :clientNumber
  
        UNION ALL
  
        SELECT
            'ClientInformation',
            AL.FOREST_CLIENT_AUDIT_ID,
            'clientIdentification',
            CLIENT_IDENTIFICATION,
            LAG(CLIENT_IDENTIFICATION) OVER (
                PARTITION BY AL.CLIENT_NUMBER
                ORDER BY AL.FOREST_CLIENT_AUDIT_ID
            ),
            AL.UPDATE_TIMESTAMP,
            AL.UPDATE_USERID,
            AL.CLIENT_AUDIT_CODE,
            UR.CLIENT_UPDATE_ACTION_CODE,
            RC.DESCRIPTION,
            8 AS FIELD_ORDER
        FROM THE.FOR_CLI_AUDIT AL
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON UR
            ON AL.FOREST_CLIENT_AUDIT_ID = UR.FOREST_CLIENT_AUDIT_ID
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON_CODE RC
            ON UR.CLIENT_UPDATE_REASON_CODE = RC.CLIENT_UPDATE_REASON_CODE
        WHERE AL.CLIENT_NUMBER = :clientNumber
  
        UNION ALL
  
        SELECT
            'ClientInformation',
            AL.FOREST_CLIENT_AUDIT_ID,
            'corpRegnNmbr',
            REGISTRY_COMPANY_TYPE_CODE || CORP_REGN_NMBR,
            LAG(REGISTRY_COMPANY_TYPE_CODE) OVER (
                PARTITION BY AL.CLIENT_NUMBER
                ORDER BY AL.FOREST_CLIENT_AUDIT_ID
            ) || LAG(CORP_REGN_NMBR) OVER (
                PARTITION BY AL.CLIENT_NUMBER
                ORDER BY AL.FOREST_CLIENT_AUDIT_ID
            ),
            AL.UPDATE_TIMESTAMP,
            AL.UPDATE_USERID,
            AL.CLIENT_AUDIT_CODE,
            UR.CLIENT_UPDATE_ACTION_CODE,
            RC.DESCRIPTION,
            9 AS FIELD_ORDER
        FROM THE.FOR_CLI_AUDIT AL
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON UR
            ON AL.FOREST_CLIENT_AUDIT_ID = UR.FOREST_CLIENT_AUDIT_ID
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON_CODE RC
            ON UR.CLIENT_UPDATE_REASON_CODE = RC.CLIENT_UPDATE_REASON_CODE
        WHERE AL.CLIENT_NUMBER = :clientNumber
  
        UNION ALL
  
        SELECT
            'ClientInformation',
            AL.FOREST_CLIENT_AUDIT_ID,
            'wcbFirmNumber',
            WCB_FIRM_NUMBER,
            LAG(WCB_FIRM_NUMBER) OVER (
                PARTITION BY AL.CLIENT_NUMBER
                ORDER BY AL.FOREST_CLIENT_AUDIT_ID
            ),
            AL.UPDATE_TIMESTAMP,
            AL.UPDATE_USERID,
            AL.CLIENT_AUDIT_CODE,
            UR.CLIENT_UPDATE_ACTION_CODE,
            RC.DESCRIPTION,
            10 AS FIELD_ORDER
        FROM THE.FOR_CLI_AUDIT AL
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON UR
            ON AL.FOREST_CLIENT_AUDIT_ID = UR.FOREST_CLIENT_AUDIT_ID
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON_CODE RC
            ON UR.CLIENT_UPDATE_REASON_CODE = RC.CLIENT_UPDATE_REASON_CODE
        WHERE AL.CLIENT_NUMBER = :clientNumber
  
        UNION ALL
  
        SELECT
            'ClientInformation',
            AL.FOREST_CLIENT_AUDIT_ID,
            'ocgSupplierNmbr',
            OCG_SUPPLIER_NMBR,
            LAG(OCG_SUPPLIER_NMBR) OVER (
                PARTITION BY AL.CLIENT_NUMBER
                ORDER BY AL.FOREST_CLIENT_AUDIT_ID
            ),
            AL.UPDATE_TIMESTAMP,
            AL.UPDATE_USERID,
            AL.CLIENT_AUDIT_CODE,
            UR.CLIENT_UPDATE_ACTION_CODE,
            RC.DESCRIPTION,
            11 AS FIELD_ORDER
        FROM THE.FOR_CLI_AUDIT AL
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON UR
            ON AL.FOREST_CLIENT_AUDIT_ID = UR.FOREST_CLIENT_AUDIT_ID
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON_CODE RC
            ON UR.CLIENT_UPDATE_REASON_CODE = RC.CLIENT_UPDATE_REASON_CODE
        WHERE AL.CLIENT_NUMBER = :clientNumber
  
        UNION ALL
  
        SELECT
            'ClientInformation',
            AL.FOREST_CLIENT_AUDIT_ID,
            'clientStatusDesc',
            SC.DESCRIPTION,
            LAG(SC.DESCRIPTION) OVER (
                PARTITION BY AL.CLIENT_NUMBER
                ORDER BY AL.FOREST_CLIENT_AUDIT_ID
            ),
            AL.UPDATE_TIMESTAMP,
            AL.UPDATE_USERID,
            AL.CLIENT_AUDIT_CODE,
            UR.CLIENT_UPDATE_ACTION_CODE,
            RC.DESCRIPTION,
            12 AS FIELD_ORDER
        FROM THE.FOR_CLI_AUDIT AL
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON UR
            ON AL.FOREST_CLIENT_AUDIT_ID = UR.FOREST_CLIENT_AUDIT_ID
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON_CODE RC
            ON UR.CLIENT_UPDATE_REASON_CODE = RC.CLIENT_UPDATE_REASON_CODE
        LEFT OUTER JOIN THE.CLIENT_STATUS_CODE SC
            ON AL.CLIENT_STATUS_CODE = SC.CLIENT_STATUS_CODE
        WHERE AL.CLIENT_NUMBER = :clientNumber
  
        UNION ALL
  
        SELECT
            'ClientInformation',
            AL.FOREST_CLIENT_AUDIT_ID,
            'notes',
            CLIENT_COMMENT,
            LAG(CLIENT_COMMENT) OVER (
                PARTITION BY AL.CLIENT_NUMBER
                ORDER BY AL.FOREST_CLIENT_AUDIT_ID
            ),
            AL.UPDATE_TIMESTAMP,
            AL.UPDATE_USERID,
            AL.CLIENT_AUDIT_CODE,
            UR.CLIENT_UPDATE_ACTION_CODE,
            RC.DESCRIPTION,
            13 AS FIELD_ORDER
        FROM THE.FOR_CLI_AUDIT AL
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON UR
            ON AL.FOREST_CLIENT_AUDIT_ID = UR.FOREST_CLIENT_AUDIT_ID
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON_CODE RC
            ON UR.CLIENT_UPDATE_REASON_CODE = RC.CLIENT_UPDATE_REASON_CODE
        WHERE AL.CLIENT_NUMBER = :clientNumber
      )

      SELECT
      A.TABLE_NAME,
      A.IDX,
      CASE
          WHEN A.CHANGE_TYPE = 'INS' THEN 'Client created'
          WHEN A.CHANGE_TYPE = 'UPD' THEN 'Client summary updated'
      END AS IDENTIFIER_LABEL,
      A.COLUMN_NAME,
      A.OLD_VALUE,
      A.NEW_VALUE,
      A.UPDATE_TIMESTAMP,
      A.UPDATE_USERID,
      A.CHANGE_TYPE,
      A.ACTION_CODE,
      A.REASON
      FROM AUDIT_DATA A
      WHERE (
          (OLD_VALUE IS NULL AND TRIM(NEW_VALUE) IS NOT NULL) OR
          (OLD_VALUE IS NOT NULL AND NEW_VALUE IS NULL) OR
          (TRIM(OLD_VALUE) <> TRIM(NEW_VALUE))
      )
      ORDER BY A.IDX DESC, A.FIELD_ORDER ASC
      """;
  
  public static final String LOCATION_HISTORY = """
      WITH AUDIT_DATA AS (
        SELECT
            'ClientLocation' AS TABLE_NAME,
            AL.CLIENT_LOCATION_AUDIT_ID || '-' || CLIENT_LOCN_CODE AS IDX,
            'locnExpiredInd' AS COLUMN_NAME,
            CASE
                WHEN AL.LOCN_EXPIRED_IND = 'Y' THEN 'Active'
                ELSE 'Deactivated'
            END AS NEW_VALUE,
            LAG(
                CASE
                    WHEN AL.LOCN_EXPIRED_IND = 'Y' THEN 'Active'
                    ELSE 'Deactivated'
                END
            ) OVER (
                PARTITION BY AL.CLIENT_LOCN_CODE 
                ORDER BY AL.CLIENT_LOCATION_AUDIT_ID
            ) AS OLD_VALUE,
            AL.UPDATE_TIMESTAMP,
            AL.UPDATE_USERID,
            AL.CLIENT_AUDIT_CODE AS CHANGE_TYPE,
            AL.CLIENT_UPDATE_ACTION_CODE AS ACTION_CODE,
            RC.DESCRIPTION AS REASON,
            1 AS FIELD_ORDER
        FROM THE.CLI_LOCN_AUDIT AL
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON_CODE RC
            ON AL.CLIENT_UPDATE_REASON_CODE = RC.CLIENT_UPDATE_REASON_CODE
        WHERE AL.CLIENT_NUMBER = :clientNumber
        
        UNION ALL
        
        SELECT
            'ClientLocation' AS TABLE_NAME,
            AL.CLIENT_LOCATION_AUDIT_ID || '-' || CLIENT_LOCN_CODE AS IDX,
            'locationName' AS COLUMN_NAME,
            AL.CLIENT_LOCN_NAME AS NEW_VALUE,
            LAG(AL.CLIENT_LOCN_NAME) OVER (
                PARTITION BY AL.CLIENT_LOCN_CODE 
                ORDER BY AL.CLIENT_LOCATION_AUDIT_ID
            ) AS OLD_VALUE,
            AL.UPDATE_TIMESTAMP,
            AL.UPDATE_USERID,
            AL.CLIENT_AUDIT_CODE AS CHANGE_TYPE,
            AL.CLIENT_UPDATE_ACTION_CODE AS ACTION_CODE,
            RC.DESCRIPTION AS REASON,
            2 AS FIELD_ORDER
        FROM THE.CLI_LOCN_AUDIT AL
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON_CODE RC
            ON AL.CLIENT_UPDATE_REASON_CODE = RC.CLIENT_UPDATE_REASON_CODE
        WHERE AL.CLIENT_NUMBER = :clientNumber
        
        UNION ALL
        
        SELECT
            'ClientLocation' AS TABLE_NAME,
            AL.CLIENT_LOCATION_AUDIT_ID || '-' || CLIENT_LOCN_CODE AS IDX,
            'addressTwo' AS COLUMN_NAME,
            AL.ADDRESS_2 AS NEW_VALUE,
            LAG(AL.ADDRESS_2) OVER (
                PARTITION BY AL.CLIENT_LOCN_CODE 
                ORDER BY AL.CLIENT_LOCATION_AUDIT_ID
            ) AS OLD_VALUE,
            AL.UPDATE_TIMESTAMP,
            AL.UPDATE_USERID,
            AL.CLIENT_AUDIT_CODE AS CHANGE_TYPE,
            AL.CLIENT_UPDATE_ACTION_CODE AS ACTION_CODE,
            RC.DESCRIPTION AS REASON,
            3 AS FIELD_ORDER
        FROM THE.CLI_LOCN_AUDIT AL
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON_CODE RC
            ON AL.CLIENT_UPDATE_REASON_CODE = RC.CLIENT_UPDATE_REASON_CODE
        WHERE AL.CLIENT_NUMBER = :clientNumber
        
        UNION ALL
        
        SELECT
            'ClientLocation' AS TABLE_NAME,
            AL.CLIENT_LOCATION_AUDIT_ID || '-' || CLIENT_LOCN_CODE AS IDX,
            'addressThree' AS COLUMN_NAME,
            AL.ADDRESS_3 AS NEW_VALUE,
            LAG(AL.ADDRESS_3) OVER (
                PARTITION BY AL.CLIENT_LOCN_CODE 
                ORDER BY AL.CLIENT_LOCATION_AUDIT_ID
            ) AS OLD_VALUE,
            AL.UPDATE_TIMESTAMP,
            AL.UPDATE_USERID,
            AL.CLIENT_AUDIT_CODE AS CHANGE_TYPE,
            AL.CLIENT_UPDATE_ACTION_CODE AS ACTION_CODE,
            RC.DESCRIPTION AS REASON,
            4 AS FIELD_ORDER
        FROM THE.CLI_LOCN_AUDIT AL
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON_CODE RC
            ON AL.CLIENT_UPDATE_REASON_CODE = RC.CLIENT_UPDATE_REASON_CODE
        WHERE AL.CLIENT_NUMBER = :clientNumber
        
        UNION ALL
        
        SELECT
            'ClientLocation' AS TABLE_NAME,
            AL.CLIENT_LOCATION_AUDIT_ID || '-' || CLIENT_LOCN_CODE AS IDX,
            'addressOne' AS COLUMN_NAME,
            AL.ADDRESS_1 AS NEW_VALUE,
            LAG(AL.ADDRESS_1) OVER (
                PARTITION BY AL.CLIENT_LOCN_CODE 
                ORDER BY AL.CLIENT_LOCATION_AUDIT_ID
            ) AS OLD_VALUE,
            AL.UPDATE_TIMESTAMP,
            AL.UPDATE_USERID,
            AL.CLIENT_AUDIT_CODE AS CHANGE_TYPE,
            AL.CLIENT_UPDATE_ACTION_CODE AS ACTION_CODE,
            RC.DESCRIPTION AS REASON,
            5 AS FIELD_ORDER
        FROM THE.CLI_LOCN_AUDIT AL
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON_CODE RC
            ON AL.CLIENT_UPDATE_REASON_CODE = RC.CLIENT_UPDATE_REASON_CODE
        WHERE AL.CLIENT_NUMBER = :clientNumber
        
        UNION ALL
        
        SELECT
            'ClientLocation' AS TABLE_NAME,
            AL.CLIENT_LOCATION_AUDIT_ID || '-' || CLIENT_LOCN_CODE AS IDX,
            'city' AS COLUMN_NAME,
            AL.CITY AS NEW_VALUE,
            LAG(AL.CITY) OVER (
                PARTITION BY AL.CLIENT_LOCN_CODE 
                ORDER BY AL.CLIENT_LOCATION_AUDIT_ID
            ) AS OLD_VALUE,
            AL.UPDATE_TIMESTAMP,
            AL.UPDATE_USERID,
            AL.CLIENT_AUDIT_CODE AS CHANGE_TYPE,
            AL.CLIENT_UPDATE_ACTION_CODE AS ACTION_CODE,
            RC.DESCRIPTION AS REASON,
            6 AS FIELD_ORDER
        FROM THE.CLI_LOCN_AUDIT AL
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON_CODE RC
            ON AL.CLIENT_UPDATE_REASON_CODE = RC.CLIENT_UPDATE_REASON_CODE
        WHERE AL.CLIENT_NUMBER = :clientNumber
        
        UNION ALL
        
        SELECT
            'ClientLocation' AS TABLE_NAME,
            AL.CLIENT_LOCATION_AUDIT_ID || '-' || CLIENT_LOCN_CODE AS IDX,
            'provinceDesc' AS COLUMN_NAME,
            CASE
                WHEN PC.PROVINCE_STATE_NAME IS NULL THEN AL.PROVINCE
                ELSE PC.PROVINCE_STATE_NAME
            END AS NEW_VALUE,
            LAG(
                CASE
                    WHEN PC.PROVINCE_STATE_NAME IS NULL THEN AL.PROVINCE
                    ELSE PC.PROVINCE_STATE_NAME
                END
            ) OVER (
                PARTITION BY AL.CLIENT_LOCN_CODE 
                ORDER BY AL.CLIENT_LOCATION_AUDIT_ID
            ) AS OLD_VALUE,
            AL.UPDATE_TIMESTAMP,
            AL.UPDATE_USERID,
            AL.CLIENT_AUDIT_CODE AS CHANGE_TYPE,
            AL.CLIENT_UPDATE_ACTION_CODE AS ACTION_CODE,
            RC.DESCRIPTION AS REASON,
            7 AS FIELD_ORDER
        FROM THE.CLI_LOCN_AUDIT AL
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON_CODE RC
            ON AL.CLIENT_UPDATE_REASON_CODE = RC.CLIENT_UPDATE_REASON_CODE
        LEFT OUTER JOIN THE.MAILING_PROVINCE_STATE PC
            ON AL.PROVINCE = PC.PROVINCE_STATE_CODE
        WHERE AL.CLIENT_NUMBER = :clientNumber
        
        UNION ALL
        
        SELECT
            'ClientLocation' AS TABLE_NAME,
            AL.CLIENT_LOCATION_AUDIT_ID || '-' || CLIENT_LOCN_CODE AS IDX,
            'country' AS COLUMN_NAME,
            AL.COUNTRY AS NEW_VALUE,
            LAG(AL.COUNTRY) OVER (
                PARTITION BY AL.CLIENT_LOCN_CODE 
                ORDER BY AL.CLIENT_LOCATION_AUDIT_ID
            ) AS OLD_VALUE,
            AL.UPDATE_TIMESTAMP,
            AL.UPDATE_USERID,
            AL.CLIENT_AUDIT_CODE AS CHANGE_TYPE,
            AL.CLIENT_UPDATE_ACTION_CODE AS ACTION_CODE,
            RC.DESCRIPTION AS REASON,
            8 AS FIELD_ORDER
        FROM THE.CLI_LOCN_AUDIT AL
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON_CODE RC
            ON AL.CLIENT_UPDATE_REASON_CODE = RC.CLIENT_UPDATE_REASON_CODE
        WHERE AL.CLIENT_NUMBER = :clientNumber
        
        UNION ALL
        
        SELECT
            'ClientLocation' AS TABLE_NAME,
            AL.CLIENT_LOCATION_AUDIT_ID || '-' || CLIENT_LOCN_CODE AS IDX,
            'postalCode' AS COLUMN_NAME,
            AL.POSTAL_CODE AS NEW_VALUE,
            LAG(AL.POSTAL_CODE) OVER (
                PARTITION BY AL.CLIENT_LOCN_CODE 
                ORDER BY AL.CLIENT_LOCATION_AUDIT_ID
            ) AS OLD_VALUE,
            AL.UPDATE_TIMESTAMP,
            AL.UPDATE_USERID,
            AL.CLIENT_AUDIT_CODE AS CHANGE_TYPE,
            AL.CLIENT_UPDATE_ACTION_CODE AS ACTION_CODE,
            RC.DESCRIPTION AS REASON,
            9 AS FIELD_ORDER
        FROM THE.CLI_LOCN_AUDIT AL
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON_CODE RC
            ON AL.CLIENT_UPDATE_REASON_CODE = RC.CLIENT_UPDATE_REASON_CODE
        WHERE AL.CLIENT_NUMBER = :clientNumber
        
        UNION ALL
        
        SELECT
            'ClientLocation' AS TABLE_NAME,
            AL.CLIENT_LOCATION_AUDIT_ID || '-' || CLIENT_LOCN_CODE AS IDX,
            'emailAddress' AS COLUMN_NAME,
            AL.EMAIL_ADDRESS AS NEW_VALUE,
            LAG(AL.EMAIL_ADDRESS) OVER (
                PARTITION BY AL.CLIENT_LOCN_CODE 
                ORDER BY AL.CLIENT_LOCATION_AUDIT_ID
            ) AS OLD_VALUE,
            AL.UPDATE_TIMESTAMP,
            AL.UPDATE_USERID,
            AL.CLIENT_AUDIT_CODE AS CHANGE_TYPE,
            AL.CLIENT_UPDATE_ACTION_CODE AS ACTION_CODE,
            RC.DESCRIPTION AS REASON,
            10 AS FIELD_ORDER
        FROM THE.CLI_LOCN_AUDIT AL
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON_CODE RC
            ON AL.CLIENT_UPDATE_REASON_CODE = RC.CLIENT_UPDATE_REASON_CODE
        WHERE AL.CLIENT_NUMBER = :clientNumber
        
        UNION ALL
        
        SELECT
            'ClientLocation' AS TABLE_NAME,
            AL.CLIENT_LOCATION_AUDIT_ID || '-' || CLIENT_LOCN_CODE AS IDX,
            'businessPhone' AS COLUMN_NAME,
            AL.BUSINESS_PHONE AS NEW_VALUE,
            LAG(AL.BUSINESS_PHONE) OVER (
                PARTITION BY AL.CLIENT_LOCN_CODE 
                ORDER BY AL.CLIENT_LOCATION_AUDIT_ID
            ) AS OLD_VALUE,
            AL.UPDATE_TIMESTAMP,
            AL.UPDATE_USERID,
            AL.CLIENT_AUDIT_CODE AS CHANGE_TYPE,
            AL.CLIENT_UPDATE_ACTION_CODE AS ACTION_CODE,
            RC.DESCRIPTION AS REASON,
            11 AS FIELD_ORDER
        FROM THE.CLI_LOCN_AUDIT AL
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON_CODE RC
            ON AL.CLIENT_UPDATE_REASON_CODE = RC.CLIENT_UPDATE_REASON_CODE
        WHERE AL.CLIENT_NUMBER = :clientNumber
        
        UNION ALL
        
        SELECT
            'ClientLocation' AS TABLE_NAME,
            AL.CLIENT_LOCATION_AUDIT_ID || '-' || CLIENT_LOCN_CODE AS IDX,
            'cellPhone' AS COLUMN_NAME,
            AL.CELL_PHONE AS NEW_VALUE,
            LAG(AL.CELL_PHONE) OVER (
                PARTITION BY AL.CLIENT_LOCN_CODE 
                ORDER BY AL.CLIENT_LOCATION_AUDIT_ID
            ) AS OLD_VALUE,
            AL.UPDATE_TIMESTAMP,
            AL.UPDATE_USERID,
            AL.CLIENT_AUDIT_CODE AS CHANGE_TYPE,
            AL.CLIENT_UPDATE_ACTION_CODE AS ACTION_CODE,
            RC.DESCRIPTION AS REASON,
            12 AS FIELD_ORDER
        FROM THE.CLI_LOCN_AUDIT AL
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON_CODE RC
            ON AL.CLIENT_UPDATE_REASON_CODE = RC.CLIENT_UPDATE_REASON_CODE
        WHERE AL.CLIENT_NUMBER = :clientNumber
        
        UNION ALL
        
        SELECT
            'ClientLocation' AS TABLE_NAME,
            AL.CLIENT_LOCATION_AUDIT_ID || '-' || CLIENT_LOCN_CODE AS IDX,
            'homePhone' AS COLUMN_NAME,
            AL.HOME_PHONE AS NEW_VALUE,
            LAG(AL.HOME_PHONE) OVER (
                PARTITION BY AL.CLIENT_LOCN_CODE 
                ORDER BY AL.CLIENT_LOCATION_AUDIT_ID
            ) AS OLD_VALUE,
            AL.UPDATE_TIMESTAMP,
            AL.UPDATE_USERID,
            AL.CLIENT_AUDIT_CODE AS CHANGE_TYPE,
            AL.CLIENT_UPDATE_ACTION_CODE AS ACTION_CODE,
            RC.DESCRIPTION AS REASON,
            13 AS FIELD_ORDER
        FROM THE.CLI_LOCN_AUDIT AL
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON_CODE RC
            ON AL.CLIENT_UPDATE_REASON_CODE = RC.CLIENT_UPDATE_REASON_CODE
        WHERE AL.CLIENT_NUMBER = :clientNumber
        
        UNION ALL
        
        SELECT
            'ClientLocation' AS TABLE_NAME,
            AL.CLIENT_LOCATION_AUDIT_ID || '-' || CLIENT_LOCN_CODE AS IDX,
            'faxNumber' AS COLUMN_NAME,
            AL.FAX_NUMBER AS NEW_VALUE,
            LAG(AL.FAX_NUMBER) OVER (
                PARTITION BY AL.CLIENT_LOCN_CODE 
                ORDER BY AL.CLIENT_LOCATION_AUDIT_ID
            ) AS OLD_VALUE,
            AL.UPDATE_TIMESTAMP,
            AL.UPDATE_USERID,
            AL.CLIENT_AUDIT_CODE AS CHANGE_TYPE,
            AL.CLIENT_UPDATE_ACTION_CODE AS ACTION_CODE,
            RC.DESCRIPTION AS REASON,
            14 AS FIELD_ORDER
        FROM THE.CLI_LOCN_AUDIT AL
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON_CODE RC
            ON AL.CLIENT_UPDATE_REASON_CODE = RC.CLIENT_UPDATE_REASON_CODE
        WHERE AL.CLIENT_NUMBER = :clientNumber
        
        UNION ALL
        
        SELECT
            'ClientLocation' AS TABLE_NAME,
            AL.CLIENT_LOCATION_AUDIT_ID || '-' || CLIENT_LOCN_CODE AS IDX,
            'cliLocnComment' AS COLUMN_NAME,
            AL.CLI_LOCN_COMMENT AS NEW_VALUE,
            LAG(AL.CLI_LOCN_COMMENT) OVER (
                PARTITION BY AL.CLIENT_LOCN_CODE 
                ORDER BY AL.CLIENT_LOCATION_AUDIT_ID
            ) AS OLD_VALUE,
            AL.UPDATE_TIMESTAMP,
            AL.UPDATE_USERID,
            AL.CLIENT_AUDIT_CODE AS CHANGE_TYPE,
            AL.CLIENT_UPDATE_ACTION_CODE AS ACTION_CODE,
            RC.DESCRIPTION AS REASON,
            15 AS FIELD_ORDER
        FROM THE.CLI_LOCN_AUDIT AL
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON_CODE RC
            ON AL.CLIENT_UPDATE_REASON_CODE = RC.CLIENT_UPDATE_REASON_CODE
        WHERE AL.CLIENT_NUMBER = :clientNumber
        
        UNION ALL
        
        SELECT
            'ClientLocation' AS TABLE_NAME,
            AL.CLIENT_LOCATION_AUDIT_ID || '-' || CLIENT_LOCN_CODE AS IDX,
            'hdbsCompanyCode' AS COLUMN_NAME,
            AL.HDBS_COMPANY_CODE AS NEW_VALUE,
            LAG(AL.HDBS_COMPANY_CODE) OVER (
                PARTITION BY AL.CLIENT_LOCN_CODE 
                ORDER BY AL.CLIENT_LOCATION_AUDIT_ID
            ) AS OLD_VALUE,
            AL.UPDATE_TIMESTAMP,
            AL.UPDATE_USERID,
            AL.CLIENT_AUDIT_CODE AS CHANGE_TYPE,
            AL.CLIENT_UPDATE_ACTION_CODE AS ACTION_CODE,
            RC.DESCRIPTION AS REASON,
            16 AS FIELD_ORDER
        FROM THE.CLI_LOCN_AUDIT AL
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON_CODE RC
            ON AL.CLIENT_UPDATE_REASON_CODE = RC.CLIENT_UPDATE_REASON_CODE
        WHERE AL.CLIENT_NUMBER = :clientNumber
        
        UNION ALL
        
        SELECT
            'ClientLocation' AS TABLE_NAME,
            AL.CLIENT_LOCATION_AUDIT_ID || '-' || CLIENT_LOCN_CODE AS IDX,
            'returnedMailDate' AS COLUMN_NAME,
            TO_CHAR(AL.RETURNED_MAIL_DATE, 'YYYY-MM-DD') AS NEW_VALUE,
            LAG(TO_CHAR(AL.RETURNED_MAIL_DATE, 'YYYY-MM-DD')) OVER (
                PARTITION BY AL.CLIENT_LOCN_CODE 
                ORDER BY AL.CLIENT_LOCATION_AUDIT_ID
            ) AS OLD_VALUE,
            AL.UPDATE_TIMESTAMP,
            AL.UPDATE_USERID,
            AL.CLIENT_AUDIT_CODE AS CHANGE_TYPE,
            AL.CLIENT_UPDATE_ACTION_CODE AS ACTION_CODE,
            RC.DESCRIPTION AS REASON,
            17 AS FIELD_ORDER
        FROM THE.CLI_LOCN_AUDIT AL
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON_CODE RC
            ON AL.CLIENT_UPDATE_REASON_CODE = RC.CLIENT_UPDATE_REASON_CODE
        WHERE AL.CLIENT_NUMBER = :clientNumber
        
        UNION ALL
        
        SELECT
            'ClientLocation' AS TABLE_NAME,
            AL.CLIENT_LOCATION_AUDIT_ID || '-' || CLIENT_LOCN_CODE AS IDX,
            'trustLocationInd' AS COLUMN_NAME,
            AL.TRUST_LOCATION_IND AS NEW_VALUE,
            LAG(AL.TRUST_LOCATION_IND) OVER (
                PARTITION BY AL.CLIENT_LOCN_CODE 
                ORDER BY AL.CLIENT_LOCATION_AUDIT_ID
            ) AS OLD_VALUE,
            AL.UPDATE_TIMESTAMP,
            AL.UPDATE_USERID,
            AL.CLIENT_AUDIT_CODE AS CHANGE_TYPE,
            AL.CLIENT_UPDATE_ACTION_CODE AS ACTION_CODE,
            RC.DESCRIPTION AS REASON,
            18 AS FIELD_ORDER
        FROM THE.CLI_LOCN_AUDIT AL
        LEFT OUTER JOIN THE.CLIENT_UPDATE_REASON_CODE RC
            ON AL.CLIENT_UPDATE_REASON_CODE = RC.CLIENT_UPDATE_REASON_CODE
        WHERE AL.CLIENT_NUMBER = :clientNumber
      )
      
      SELECT
          A.TABLE_NAME,
          A.IDX,
          CASE
              WHEN A.CHANGE_TYPE = 'INS' THEN 
                  CASE 
                      WHEN CL.CLIENT_LOCN_NAME IS NOT NULL THEN 'Location "' || 
                           CL.CLIENT_LOCN_CODE || ' - ' || CL.CLIENT_LOCN_NAME || '" added'
                      ELSE 'Location "' || CL.CLIENT_LOCN_CODE || '" added'
                  END
              WHEN A.CHANGE_TYPE = 'UPD' THEN 
                  CASE 
                      WHEN CL.CLIENT_LOCN_NAME IS NOT NULL THEN 'Location "' || 
                           CL.CLIENT_LOCN_CODE || ' - ' || CL.CLIENT_LOCN_NAME || '" updated'
                      ELSE 'Location "' || CL.CLIENT_LOCN_CODE || '" updated'
                  END
          END AS IDENTIFIER_LABEL,
          A.COLUMN_NAME,
          A.OLD_VALUE,
          A.NEW_VALUE,
          A.UPDATE_TIMESTAMP,
          A.UPDATE_USERID,
          A.CHANGE_TYPE,
          A.ACTION_CODE,
          A.REASON
      FROM AUDIT_DATA A
      LEFT OUTER JOIN THE.CLIENT_LOCATION CL
          ON SUBSTR(A.IDX, -2) = CL.CLIENT_LOCN_CODE
      WHERE (
          (OLD_VALUE IS NULL AND TRIM(NEW_VALUE) IS NOT NULL) OR
          (OLD_VALUE IS NOT NULL AND NEW_VALUE IS NULL) OR
          (TRIM(OLD_VALUE) <> TRIM(NEW_VALUE))
      )
      AND CL.CLIENT_NUMBER = :clientNumber
      ORDER BY A.IDX DESC, A.FIELD_ORDER ASC    
      """;
}
